//
//  DataBank.swift
//  My Daily Portfolio Update
//
//  Created by Khashayar Abri on 04.08.20.
//  Copyright © 2020 Khashayar Abri. All rights reserved.
//

import Foundation

// MARK: -- For Name Loading
let myDic_Symb2Name: [String:String] =
    ["AMZN": "Amazon.com Inc.",
    "BA": "Boeing Company",
    "TSLA": "Tesla Inc.",
    "TLRY": "Tilray Inc.",
    "AAPL": "Apple Inc.",
    "NIO": "NIO Inc.",
    "AAL": "American Airlines Group Inc.",
    "DAL": "Delta Air Lines Inc.",
    "MSFT": "Microsoft Corporation",
    "KO": "Coca-Cola Company",
    "DIS": "Walt Disney Company",
    "BYND": "Beyond Meat Inc.",
    "FB": "Facebook Inc.",
    "MCD": "McDonald's Corporation",
    "NFLX": "Netflix Inc.",
    "SDC": "SmileDirectClub Inc.",
    "SNE": "Sony Corporation",
    "AMD": "Advanced Micro Devices Inc.",
    "NVDA": "NVIDIA Corporation",
    "UBER": "Uber Technologies Inc.",
    "UAA": "Under Armour Inc.",
    "BABA": "Alibaba Group Holding Limited",
    "T": "AT&T Inc.",
    "IVR": "INVESCO MORTGAGE CAPITAL INC",
    "RCL": "Royal Caribbean Cruises Ltd.",
    "WORK": "Slack Technologies Inc.",
    "SPCE": "Virgin Galactic Holdings Inc.",
    "CPE": "Callon Petroleum Company",
    "ZM": "Zoom Video Communications Inc.",
    "NKE": "Nike Inc.",
    "OXY": "Occidental Petroleum Corporatio",
    "V": "Visa Inc.",
    "APHA": "Aphria Inc.",
    "SNAP": "Snap Inc.",
    "BAC": "Bank of America Corporation",
    "CGC": "Canopy Growth Corporation",
    "JNJ": "Johnson & Johnson",
    "PYPL": "PayPal Holdings Inc.",
    "KOS": "Kosmos Energy Ltd.",
    "MA": "Mastercard Incorporated",
    "SBUX": "Starbucks Corporation",
    "VFF": "Village Farms International In",
    "GE": "General Electric Company",
    "PTON": "Peloton Interactive Inc.",
    "LUV": "Southwest Airlines Company",
    "IBM": "International Business Machines",
    "O": "Realty Income Corporation",
    "SQ": "Square Inc.",
    "PFE": "Pfizer Inc.",
    "TWTR": "Twitter Inc.",
    "ADBE": "Adobe Inc.",
    "CRON": "Cronos Group Inc. Common Share",
    "GILD": "Gilead Sciences Inc.",
    "HAL": "Halliburton Company",
    "GRUB": "GrubHub Inc.",
    "MRO": "Marathon Oil Corporation",
    "RIG": "Transocean Ltd (Switzerland)",
    "WMT": "Walmart Inc.",
    "SHOP": "Shopify Inc.",
    "SAVE": "Spirit Airlines Inc.",
    "AXP": "American Express Company",
    "INTC": "Intel Corporation",
    "QCOM": "QUALCOMM Incorporated",
    "NOK": "Nokia Corporation Sponsored",
    "PEP": "Pepsico Inc.",
    "ABBV": "AbbVie Inc.",
    "ATVI": "Activision Blizzard Inc",
    "EA": "Electronic Arts Inc.",
    "MDT": "Medtronic plc.",
    "GOOG": "Alphabet Inc.",
    "MO": "Altria Group Inc.",
    "TLRD": "Tailored Brands Inc.",
    "BMO": "Bank Of Montreal",
    "PK": "Park Hotels & Resorts Inc.",
    "CAR": "Avis Budget Group Inc.",
    "GWPH": "GW Pharmaceuticals Plc",
    "JD": "JD.com Inc.",
    "LTRPA": "Liberty TripAdvisor Holdings I",
    "MAC": "Macerich Company",
    "ZNGA": "Zynga Inc.",
    "GM": "General Motors Company",
    "MAR": "Marriott International",
    "STOR": "STORE Capital Corporation",
    "APA": "Apache Corporation",
    "CRBP": "Corbus Pharmaceuticals Holdings",
    "SPOT": "Spotify Technology S.A.",
    "CRWD": "CrowdStrike Holdings Inc.",
    "COTY": "Coty Inc.",
    "NAT": "Nordic American Tankers Limited",
    "PINS": "Pinterest Inc.",
    "COST": "Costco Wholesale Corporation",
    "TSM": "Taiwan Semiconductor Manufactur",
    "PRGS": "Progress Software Corporation",
    "AGNC": "AGNC Investment Corp.",
    "LAKE": "Lakeland Industries Inc.",
    "TSN": "Tyson Foods Inc.",
    "EBAY": "eBay Inc.",
    "OKTA": "Okta Inc.",
    "SYY": "Sysco Corporation",
    "ABT": "Abbott Laboratories",
    "GS": "Goldman Sachs Group Inc.",
    "LYFT": "Lyft Inc.",
    "WBA": "Walgreens Boots Alliance Inc.",
    "NET": "Cloudflare Inc.",
    "ROKU": "Roku Inc.",
    "HPE": "Hewlett Packard Enterprise Comp",
    "DXCM": "DexCom Inc.",
    "LVGO": "Livongo Health Inc.",
    "BCRX": "BioCryst Pharmaceuticals Inc.",
    "TDOC": "Teladoc Health Inc.",
    "BKNG": "Booking Holdings Inc. Common St",
    "EB": "Eventbrite Inc.",
    "GCI": "Gannett Co. Inc.",
    "RVLV": "Revolve Group Inc.",
    "KHC": "The Kraft Heinz Company",
    "ORCL": "Oracle Corporation",
    "ENPH": "Enphase Energy Inc.",
    "LMT": "Lockheed Martin Corporation",
    "PSX": "Phillips 66",
    "TTWO": "Take-Two Interactive Software ",
    "SABR": "Sabre Corporation",
    "PM": "Philip Morris International Inc",
    "GNPX": "Genprex Inc.",
    "CAT": "Caterpillar Inc.",
    "ELF": "e.l.f. Beauty Inc.",
    "MAIN": "Main Street Capital Corporation",
    "SONO": "Sonos Inc.",
    "DDOG": "Datadog Inc.",
    "FSLY": "Fastly Inc.",
    "KMI": "Kinder Morgan Inc.",
    "FUV": "Arcimoto Inc.",
    "EPD": "Enterprise Products Partners L.",
    "LTC": "LTC Properties Inc.",
    "CCI": "Crown Castle International Corp",
    "MANU": "Manchester",
    "MRVL": "Marvell Technology Group Ltd.",
    "SLB": "Schlumberger N.V.",
    "TWLO": "Twilio Inc.",
    "TRIP": "TripAdvisor Inc.",
    "IRM": "Iron Mountain Incorporated (Del",
    "SE": "Sea Limited",
    "AKTS": "Akoustis Technologies Inc.",
    "AMGN": "Amgen Inc.",
    "BE": "Bloom Energy Corporation",
    "PBA": "Pembina Pipeline Corp.",
    "BBBY": "Bed Bath & Beyond Inc.",
    "OMP": "Oasis Midstream Partners LP",
    "BIDU": "Baidu Inc.",
    "ENB": "Enbridge Inc",
    "FL": "Foot Locker Inc.",
    "GPRO": "GoPro Inc.",
    "HPQ": "HP Inc.",
    "SEDG": "SolarEdge Technologies Inc.",
    "AUY": "Yamana Gold Inc.",
    "EPR": "EPR Properties",
    "PSEC": "Prospect Capital Corporation",
    "STAG": "Stag Industrial Inc.",
    "AVGO": "Broadcom Inc.",
    "LLY": "Eli Lilly and Company",
    "KSS": "Kohl's Corporation",
    "FTI": "TechnipFMC plc",
    "BNTX": "BioNTech SE",
    "IRBT": "iRobot Corporation",
    "BTU": "Peabody Energy Corporation",
    "PBI": "Pitney Bowes Inc.",
    "LEG": "Leggett & Platt Incorporated",
    "SWKS": "Skyworks Solutions Inc.",
    "TXMD": "TherapeuticsMD Inc.",
    "CNK": "Cinemark Holdings Inc Cinemark ",
    "INMD": "InMode Ltd.",
    "JWN": "Nordstrom Inc.",
    "UNP": "Union Pacific Corporation",
    "COP": "ConocoPhillips",
    "MPC": "Marathon Petroleum Corporation",
    "UPS": "United Parcel Service Inc.",
    "CPTA": "Capitala Finance Corp.",
    "ENDP": "Endo International plc",
    "NEM": "Newmont Corporation",
    "PRU": "Prudential Financial Inc.",
    "SYK": "Stryker Corporation",
    "AAXN": "Axon Enterprise Inc.",
    "EOG": "EOG Resources Inc.",
    "APPN": "Appian Corporation",
    "KOPN": "Kopin Corporation",
    "GT": "The Goodyear Tire & Rubber Comp",
    "MDB": "MongoDB Inc.",
    "BEP": "Brookfield Renewable Partners L",
    "FSLR": "First Solar Inc.",
    "IVZ": "Invesco Ltd",
    "VSLR": "Vivint Solar Inc.",
    "SIRI": "Sirius XM Holdings Inc.",
    "AMT": "American Tower Corporation (REI",
    "CL": "Colgate-Palmolive Company",
    "PLYA": "Playa Hotels & Resorts N.V.",
    "APPS": "Digital Turbine Inc.",
    "EDIT": "Editas Medicine Inc.",
    "KMB": "Kimberly-Clark Corporation",
    "TXN": "Texas Instruments Incorporated",
    "BPY": "Brookfield Property Partners L.",
    "SO": "Southern Company (The)",
    "ACOR": "Acorda Therapeutics Inc.",
    "HRL": "Hormel Foods Corporation",
    "WDC": "Western Digital Corporation",
    "CHWY": "Chewy Inc.",
    "FANG": "Diamondback Energy Inc. - Comm",
    "FRT": "Federal Realty Investment Trust",
    "PNC": "PNC Financial Services Group I",
    "AFL": "AFLAC Incorporated",
    "NOV": "National Oilwell Varco Inc.",
    "CLX": "Clorox Company (The)",
    "TJX": "TJX Companies Inc. (The)",
    "ATRO": "Astronics Corporation",
    "VRTX": "Vertex Pharmaceuticals Incorpor",
    "ARCO": "Arcos Dorados Holdings Inc.",
    "DELL": "Dell Technologies Inc.",
    "D": "Dominion Energy Inc.",
    "JKS": "JinkoSolar Holding Company Limi",
    "PBR": "Petroleo Brasileiro S.A.- Petro",
    "SJR": "Shaw Communications Inc.",
    "RY": "Royal Bank Of Canada",
    "CRSP": "CRISPR Therapeutics AG",
    "FIT": "Fitbit Inc.",
    "GERN": "Geron Corporation",
    "MAXR": "Maxar Technologies Inc.",
    "RGLD": "Royal Gold Inc.",
    "SWN": "Southwestern Energy Company",
    "TMUS": "T-Mobile US Inc.",
    "NVTA": "Invitae Corporation",
    "MPW": "Medical Properties Trust Inc.",
    "SFIX": "Stitch Fix Inc.",
    "WSR": "Whitestone REIT",
    "ANIP": "ANI Pharmaceuticals Inc.",
    "CQP": "Cheniere Energy Partners LP Ch",
    "GLW": "Corning Incorporated",
    "ESTC": "Elastic N.V.",
    "HAS": "Hasbro Inc.",
    "STNE": "StoneCo Ltd.",
    "TEVA": "Teva Pharmaceutical Industries ",
    "WATT": "Energous Corporation",
    "IIPR": "Innovative Industrial Propertie",
    "PVH": "PVH Corp.",
    "BGFV": "Big 5 Sporting Goods Corporatio",
    "CCEP": "Coca-Cola European Partners plc",
    "ED": "Consolidated Edison Inc.",
    "DRI": "Darden Restaurants Inc.",
    "LADR": "Ladder Capital Corp",
    "NEP": "NextEra Energy Partners LP",
    "ADPT": "Adaptive Biotechnologies Corpor",
    "BIIB": "Biogen Inc.",
    "ILMN": "Illumina Inc.",
    "LOW": "Lowe's Companies Inc.",
    "PCG": "Pacific Gas & Electric Co.",
    "PDD": "Pinduoduo Inc.",
    "QD": "Qudian Inc.",
    "BNS": "Bank Nova Scotia Halifax Pfd 3",
    "ZTS": "Zoetis Inc.",
    "ARLP": "Alliance Resource Partners L.P",
    "ADP": "Automatic Data Processing Inc.",
    "BKR": "Baker Hughes Company",
    "LYB": "LyondellBasell Industries NV",
    "NRG": "NRG Energy Inc.",
    "SMAR": "Smartsheet Inc.",
    "XBIT": "XBiotech Inc.",
    "AA": "Alcoa Corporation",
    "DISCA": "Discovery Inc. - Series A",
    "EMR": "Emerson Electric Company",
    "EL": "Estee Lauder Companies Inc. (T",
    "SLG": "SL Green Realty Corp",
    "ZS": "Zscaler Inc.",
    "ALB": "Albemarle Corporation",
    "BBY": "Best Buy Co. Inc.",
    "BPYU": "Brookfield Property REIT Inc.",
    "CAN": "Canaan Inc.",
    "DOW": "Dow Inc.",
    "GPC": "Genuine Parts Company",
    "INSG": "Inseego Corp.",
    "OHI": "Omega Healthcare Investors Inc",
    "UNM": "Unum Group",
    "VNOM": "Viper Energy Partners LP",
    "WRTC": "Wrap Technologies Inc.",
    "AIR": "AAR Corp.",
    "BIP": "Brookfield Infrastructure Partn",
    "CHL": "China Mobile Limited",
    "GIS": "General Mills Inc.",
    "GEOS": "Geospace Technologies Corporati",
    "LIN": "Linde plc",
    "NPTN": "NeoPhotonics Corporation",
    "NVO": "Novo Nordisk A/S",
    "RUTH": "Ruth's Hospitality Group Inc.",
    "SCM": "Stellus Capital Investment Corp",
    "REAL": "The RealReal Inc.",
    "VERI": "Veritone Inc.",
    "AVAV": "AeroVironment Inc.",
    "ADM": "Archer-Daniels-Midland Company",
    "TEAM": "Atlassian Corporation Plc",
    "GLOG": "GasLog Ltd.",
    "MMP": "Magellan Midstream Partners L.P",
    "NUE": "Nucor Corporation",
    "VIR": "Vir Biotechnology Inc.",
    "AMAT": "Applied Materials Inc.",
    "DFS": "Discover Financial Services",
    "GAIN": "Gladstone Investment Corporatio",
    "LBTYA": "Liberty Global plc",
    "LTHM": "Livent Corporation",
    "MET": "MetLife Inc.",
    "NMRK": "Newmark Group Inc.",
    "PING": "Ping Identity Holding Corp.",
    "TM": "Toyota Motor Corporation",
    "XLNX": "Xilinx Inc.",
    "AER": "AerCap Holdings N.V.",
    "ADSK": "Autodesk Inc.",
    "BCEI": "Bonanza Creek Energy Inc.",
    "CPRI": "Capri Holdings Limited",
    "ECL": "Ecolab Inc.",
    "GOGO": "Gogo Inc.",
    "INTU": "Intuit Inc.",
    "LEVI": "Levi Strauss & Co",
    "NK": "NantKwest Inc.",
    "SUNS": "Solar Senior Capital Ltd.",
    "SPWR": "SunPower Corporation",
    "CHEF": "The Chefs' Warehouse Inc.",
    "VMW": "Vmware Inc.",
    "WPC": "W. P. Carey Inc. REIT",
    "ADS": "Alliance Data Systems Corporati",
    "LAND": "Gladstone Land Corporation",
    "GLUU": "Glu Mobile Inc.",
    "TMO": "Thermo Fisher Scientific Inc",
    "UXIN": "Uxin Limited",
    "WWE": "World Wrestling Entertainment ",
    "AES": "The AES Corporation",
    "ARI": "Apollo Commercial Real Estate F",
    "CM": "Canadian Imperial Bank of Comme",
    "HOG": "Harley-Davidson Inc.",
    "SKYW": "SkyWest Inc.",
    "SSYS": "Stratasys Ltd.",
    "SNCR": "Synchronoss Technologies Inc.",
    "ZEN": "Zendesk Inc.",
    "Z": "Zillow Group Inc.",
    "BZUN": "Baozun Inc.",
    "BSM": "Black Stone Minerals L.P.",
    "BYD": "Boyd Gaming Corporation",
    "CNP": "CenterPoint Energy Inc (Holdin",
    "COUP": "Coupa Software Incorporated",
    "GFL": "GFL Environmental Inc. Subordin",
    "EAF": "GrafTech International Ltd.",
    "HUYA": "HUYA Inc.",
    "IMMU": "Immunomedics Inc.",
    "MAT": "Mattel Inc.",
    "NOW": "ServiceNow Inc.",
    "SRT": "StarTek Inc.",
    "TD": "Toronto Dominion Bank (The)",
    "WRK": "Westrock Company",
    "AGRX": "Agile Therapeutics Inc.",
    "COG": "Cabot Oil & Gas Corporation",
    "GOOS": "Canada Goose Holdings Inc. Subo",
    "COF": "Capital One Financial Corporati",
    "CRT": "Cross Timbers Royalty Trust",
    "FIVN": "Five9 Inc.",
    "GLOP": "GasLog Partners LP",
    "HP": "Helmerich & Payne Inc.",
    "NLOK": "NortonLifeLock Inc.",
    "URBN": "Urban Outfitters Inc.",
    "WB": "Weibo Corporation",
    "ANF": "Abercrombie & Fitch Company",
    "AEM": "Agnico Eagle Mines Limited",
    "NLY": "Annaly Capital Management Inc",
    "CINF": "Cincinnati Financial Corporatio",
    "BEN": "Franklin Resources Inc.",
    "MNK": "Mallinckrodt plc",
    "NTES": "NetEase Inc.",
    "PBCT": "People's",
    "DTIL": "Precision BioSciences Inc.",
    "PBYI": "Puma Biotechnology Inc",
    "TWOU": "2U Inc.",
    "AKAM": "Akamai Technologies Inc.",
    "ANSS": "ANSYS Inc.",
    "BHC": "Bausch Health Companies Inc.",
    "BDSI": "BioDelivery Sciences Internatio",
    "BG": "Bunge Limited Bunge Limited",
    "CWH": "Camping World Holdings Inc.",
    "FUN": "Cedar Fair L.P.",
    "CMG": "Chipotle Mexican Grill Inc.",
    "EXC": "Exelon Corporation",
    "HBI": "Hanesbrands Inc.",
    "HRZN": "Horizon Technology Finance Corp",
    "MKC": "McCormick & Company Incorporat",
    "PDLI": "PDL BioPharma Inc.",
    "QRVO": "Qorvo Inc.",
    "SHAK": "Shake Shack Inc.",
    "SPLK": "Splunk Inc.",
    "SPT": "Sprout Social Inc",
    "STWD": "STARWOOD PROPERTY TRUST INC. S",
    "UVV": "Universal Corporation",
    "ALXN": "Alexion Pharmaceuticals Inc.",
    "BB": "BlackBerry Limited",
    "CRDF": "Cardiff Oncology Inc.",
    "CHU": "China Unicom (Hong Kong) Ltd",
    "CXW": "CoreCivic Inc.",
    "DLPH": "Delphi Technologies PLC",
    "EMN": "Eastman Chemical Company",
    "FTCH": "Farfetch Limited",
    "FIS": "Fidelity National Information S",
    "FLIR": "FLIR Systems Inc.",
    "GOOD": "Gladstone Commercial Corporatio",
    "LB": "L Brands Inc.",
    "MYL": "Mylan N.V.",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "RESN": "Resonant Inc.",
    "SPH": "Suburban Propane Partners L.P.",
    "VICI": "VICI Properties Inc.",
    "AL": "Air Lease Corporation",
    "KERN": "Akerna Corp.",
    "BNFT": "Benefitfocus Inc.",
    "BGSF": "BG Staffing Inc",
    "BXP": "Boston Properties Inc.",
    "SCHW": "Charles Schwab Corporation (The",
    "CLVS": "Clovis Oncology Inc.",
    "CME": "CME Group Inc.",
    "DLTR": "Dollar Tree Inc.",
    "EHTH": "eHealth Inc.",
    "FISV": "Fiserv Inc.",
    "FLR": "Fluor Corporation",
    "HASI": "Hannon Armstrong Sustainable In",
    "HBIO": "Harvard Bioscience Inc.",
    "IRDM": "Iridium Communications Inc",
    "JCI": "Johnson Controls International ",
    "NTAP": "NetApp Inc.",
    "PANW": "Palo Alto Networks Inc.",
    "TRUE": "TrueCar Inc.",
    "WSG": "Wanda Sports Group Company Limi",
    "W": "Wayfair Inc.",
    "WYND": "Wyndham Destinations Inc.",
    "APD": "Air Products and Chemicals Inc",
    "AZRE": "Azure Power Global Limited",
    "BBSI": "Barrett Business Services Inc.",
    "BLMN": "Bloomin' Brands Inc.",
    "CI": "Cigna Corporation",
    "CSX": "CSX Corporation",
    "DE": "Deere & Company",
    "EW": "Edwards Lifesciences Corporatio",
    "ENIA": "Enel Americas S.A.",
    "FTNT": "Fortinet Inc.",
    "FNV": "Franco-Nevada Corporation",
    "ITW": "Illinois Tool Works Inc.",
    "NTLA": "Intellia Therapeutics Inc.",
    "LAUR": "Laureate Education Inc.",
    "LAZ": "Lazard LTD. Lazard LTD.",
    "LEN": "Lennar Corporation",
    "LX": "LexinFintech Holdings Ltd.",
    "MELI": "MercadoLibre Inc.",
    "MCRI": "Monarch Casino & Resort Inc.",
    "NTGR": "NETGEAR Inc.",
    "PD": "PagerDuty Inc.",
    "PAA": "Plains All American Pipeline L",
    "QTT": "Qutoutiao Inc.",
    "SHO": "Sunstone Hotel Investors Inc. ",
    "TER": "Teradyne Inc.",
    "MOS": "Mosaic Company (The)",
    "TIF": "Tiffany & Co.",
    "VLY": "Valley National Bancorp",
    "VKTX": "Viking Therapeutics Inc.",
    "WES": "Western Midstream Partners LP",
    "ALEX": "Alexander & Baldwin Inc.",
    "AMBA": "Ambarella Inc.",
    "AWR": "American States Water Company",
    "ANET": "Arista Networks Inc.",
    "BIG": "Big Lots Inc.",
    "CHRS": "Coherus BioSciences Inc.",
    "CONE": "CyrusOne Inc",
    "EQT": "EQT Corporation",
    "EXTR": "Extreme Networks Inc.",
    "HEP": "Holly Energy Partners L.P.",
    "IMGN": "ImmunoGen Inc.",
    "IPHI": "Inphi Corporation",
    "ICE": "Intercontinental Exchange Inc.",
    "JEF": "Jefferies Financial Group Inc.",
    "JNPR": "Juniper Networks Inc.",
    "LSCC": "Lattice Semiconductor Corporati",
    "LIZI": "LIZHI INC.",
    "LITE": "Lumentum Holdings Inc.",
    "MCY": "Mercury General Corporation",
    "MDP": "Meredith Corporation",
    "MHK": "Mohawk Industries Inc.",
    "NDAQ": "Nasdaq Inc.",
    "NAVI": "Navient Corporation",
    "PACB": "Pacific Biosciences of Californ",
    "PAVM": "PAVmed Inc.",
    "PAYX": "Paychex Inc.",
    "PRFT": "Perficient Inc.",
    "QIWI": "QIWI plc",
    "SSTI": "ShotSpotter Inc.",
    "SPWH": "Sportsman's Warehouse Holdings",
    "SUPN": "Supernus Pharmaceuticals Inc.",
    "VRNT": "Verint Systems Inc.",
    "VIRT": "Virtu Financial Inc.",
    "WY": "Weyerhaeuser Company",
    "YNDX": "Yandex N.V.",
    "YJ": "Yunji Inc. - American Depositor",
    "ACCO": "Acco Brands Corporation",
    "ALRM": "Alarm.com Holdings Inc.",
    "MDRX": "Allscripts Healthcare Solutions",
    "ARCT": "Arcturus Therapeutics Holdings ",
    "ARLO": "Arlo Technologies Inc.",
    "ATRA": "Atara Biotherapeutics Inc.",
    "AVDL": "Avadel Pharmaceuticals plc",
    "AVID": "Avid Technology Inc.",
    "BBDC": "Barings BDC Inc.",
    "BLUE": "bluebird bio Inc.",
    "BSX": "Boston Scientific Corporation",
    "BOX": "Box Inc.",
    "CCJ": "Cameco Corporation",
    "CARG": "CarGurus Inc.",
    "KMX": "CarMax Inc",
    "CTSH": "Cognizant Technology Solutions ",
    "COMM": "CommScope Holding Company Inc.",
    "TACO": "Del Taco Restaurants Inc.",
    "DKS": "Dick's Sporting Goods Inc",
    "EPAM": "EPAM Systems Inc.",
    "FCPT": "Four Corners Property Trust In",
    "FOXA": "Fox Corporation",
    "HRB": "H&R Block Inc.",
    "IVAC": "Intevac Inc.",
    "LILA": "Liberty Latin America Ltd.",
    "LPSN": "LivePerson Inc.",
    "L": "Loews Corporation",
    "MDU": "MDU Resources Group Inc.",
    "VIVO": "Meridian Bioscience Inc.",
    "MNR": "Monmouth Real Estate Investment",
    "MYGN": "Myriad Genetics Inc.",
    "NC": "NACCO Industries Inc.",
    "NH": "NantHealth Inc.",
    "PH": "Parker-Hannifin Corporation",
    "PT": "Pintec Technology Holdings Limi",
    "QTNT": "Quotient Limited",
    "ROST": "Ross Stores Inc.",
    "SEAC": "SeaChange International Inc.",
    "SYNC": "Synacor Inc.",
    "TRP": "TC Energy Corporation",
    "TDC": "Teradata Corporation",
    "VFC": "V.F. Corporation",
    "VRSK": "Verisk Analytics Inc.",
    "XYL": "Xylem Inc.",
    "ACIU": "AC Immune SA",
    "AMRC": "Ameresco Inc.",
    "AEP": "American Electric Power Company",
    "AFIN": "American Finance Trust Inc.",
    "AMKR": "Amkor Technology Inc.",
    "AMPH": "Amphastar Pharmaceuticals Inc.",
    "ATRS": "Antares Pharma Inc.",
    "AON": "Aon plc",
    "ARC": "ARC Document Solutions Inc.",
    "ATHX": "Athersys Inc.",
    "AVA": "Avista Corporation",
    "BAND": "Bandwidth Inc.",
    "BYSI": "BeyondSpring Inc.",
    "BHP": "BHP Group Limited",
    "BJ": "BJ's Wholesale Club Holdings I",
    "BBIO": "BridgeBio Pharma Inc.",
    "CVGW": "Calavo Growers Inc.",
    "CVNA": "Carvana Co.",
    "CRNT": "Ceragon Networks Ltd.",
    "XEC": "Cimarex Energy Co",
    "CTXS": "Citrix Systems Inc.",
    "CODI": "Compass Diversified Holdings Sh",
    "CEIX": "CONSOL Energy Inc.",
    "CRTO": "Criteo S.A.",
    "CCRN": "Cross Country Healthcare Inc.",
    "CMI": "Cummins Inc.",
    "DAR": "Darling Ingredients Inc.",
    "DISCK": "Discovery Inc. - Series C",
    "EQR": "Equity Residential",
    "ESPR": "Esperion Therapeutics Inc.",
    "ESS": "Essex Property Trust Inc.",
    "EVR": "Evercore Inc.",
    "ES": "Eversource Energy (D/B/A)",
    "EXTN": "Exterran Corporation",
    "FRG": "Franchise Group Inc.",
    "HEES": "H&E Equipment Services Inc.",
    "HSIC": "Henry Schein Inc.",
    "HBAN": "Huntington Bancshares Incorpora",
    "IDXX": "IDEXX Laboratories Inc.",
    "IHRT": "iHeartMedia Inc.",
    "IMMR": "Immersion Corporation",
    "IP": "International Paper Company",
    "KEY": "KeyCorp",
    "KIM": "Kimco Realty Corporation",
    "KKR": "KKR & Co. Inc.",
    "KTB": "Kontoor Brands Inc.",
    "LMRK": "Landmark Infrastructure Partner",
    "LGC": "Legacy Acquisition Corp.",
    "LBTYK": "Liberty Global plc",
    "LILAK": "Liberty Latin America Ltd.",
    "MTSI": "MACOM Technology Solutions Hold",
    "MRUS": "Merus N.V.",
    "MCHP": "Microchip Technology Incorporat",
    "MTSC": "MTS Systems Corporation",
    "NREF": "NexPoint Real Estate Finance I",
    "NTR": "Nutrien Ltd.",
    "ORA": "Ormat Technologies Inc.",
    "PLAB": "Photronics Inc.",
    "PLD": "Prologis Inc.",
    "PSA": "Public Storage",
    "QRTEA": "Liberty Interactive Corporation",
    "RGP": "Resources Connection Inc.",
    "R": "Ryder System Inc.",
    "SAGE": "Sage Therapeutics Inc.",
    "SBGI": "Sinclair Broadcast Group Inc.",
    "SNA": "Snap-On Incorporated",
    "TRGP": "Targa Resources Inc.",
    "TH": "Target Hospitality Corp.",
    "TMDX": "TransMedics Group Inc.",
    "TRUP": "Trupanion Inc.",
    "UCTT": "Ultra Clean Holdings Inc.",
    "UMH": "UMH Properties Inc.",
    "GWW": "W.W. Grainger Inc.",
    "WTS": "Watts Water Technologies Inc.",
    "WWD": "Woodward Inc.",
    "YUMC": "Yum China Holdings Inc.",
    "JFU": "9F Inc.",
    "ATEN": "A10 Networks Inc.",
    "ACHC": "Acadia Healthcare Company Inc.",
    "ADNT": "Adient plc",
    "AEIS": "Advanced Energy Industries Inc",
    "ACM": "AECOM",
    "A": "Agilent Technologies Inc.",
    "AMED": "Amedisys Inc",
    "AMN": "AMN Healthcare Services Inc AMN",
    "PLAN": "Anaplan Inc.",
    "ANAB": "AnaptysBio Inc.",
    "ANIK": "Anika Therapeutics Inc.",
    "APPF": "AppFolio Inc.",
    "AROC": "Archrock Inc.",
    "AIZ": "Assurant Inc.",
    "ATOM": "Atomera Incorporated",
    "AVT": "Avnet Inc.",
    "AXS": "Axis Capital Holdings Limited",
    "BGS": "B&G Foods Inc. B&G Foods Inc.",
    "BMRN": "BioMarin Pharmaceutical Inc.",
    "BJRI": "BJ's Restaurants Inc.",
    "BKH": "Black Hills Corporation",
    "EPAY": "Bottomline Technologies Inc.",
    "BV": "BrightView Holdings Inc.",
    "CDNS": "Cadence Design Systems Inc.",
    "CAMP": "CalAmp Corp.",
    "CARA": "Cara Therapeutics Inc.",
    "CF": "CF Industries Holdings Inc.",
    "CHTR": "Charter Communications Inc.",
    "COLL": "Collegium Pharmaceutical Inc.",
    "CAG": "ConAgra Brands Inc.",
    "BAP": "Credicorp Ltd.",
    "CRESY": "Cresud S.A.C.I.F. y A.",
    "CUE": "Cue Biopharma Inc.",
    "DAKT": "Daktronics Inc.",
    "DISH": "DISH Network Corporation",
    "DEI": "Douglas Emmett Inc.",
    "SATS": "EchoStar Corporation",
    "ENIC": "Enel Chile S.A.",
    "MRAM": "Everspin Technologies Inc.",
    "EXR": "Extra Space Storage Inc",
    "FDS": "FactSet Research Systems Inc.",
    "FAST": "Fastenal Company",
    "FLT": "FleetCor Technologies Inc.",
    "GTHX": "G1 Therapeutics Inc.",
    "GTX": "Garrett Motion Inc.",
    "GNTX": "Gentex Corporation",
    "HLNE": "Hamilton Lane Incorporated",
    "HCA": "HCA Healthcare Inc.",
    "HUBS": "HubSpot Inc.",
    "INVH": "Invitation Homes Inc.",
    "IQ": "iQIYI Inc.",
    "KW": "Kennedy-Wilson Holdings Inc.",
    "KBAL": "Kimball International Inc.",
    "KNSA": "Kiniksa Pharmaceuticals Ltd.",
    "KEP": "Korea Electric Power Corporatio",
    "LRCX": "Lam Research Corporation",
    "LORL": "Loral Space and Communications",
    "LUNA": "Luna Innovations Incorporated",
    "MNTX": "Manitex International Inc.",
    "MCHX": "Marchex Inc.",
    "MATW": "Matthews International Corporat",
    "MITK": "Mitek Systems Inc.",
    "MIXT": "MiX Telematics Limited",
    "MPLX": "MPLX LP",
    "NBIX": "Neurocrine Biosciences Inc.",
    "NXTC": "NextCure Inc.",
    "NICE": "NICE Ltd",
    "NSC": "Norfolk Southern Corporation",
    "NTRS": "Northern Trust Corporation",
    "OMER": "Omeros Corporation",
    "OSW": "OneSpaWorld Holdings Limited",
    "PDCO": "Patterson Companies Inc.",
    "PSXP": "Phillips 66 Partners LP",
    "DOC": "Physicians Realty Trust",
    "PFPT": "Proofpoint Inc.",
    "QADB": "QAD Inc.",
    "QLYS": "Qualys Inc.",
    "RDUS": "Radius Health Inc.",
    "RPD": "Rapid7 Inc.",
    "RDVT": "Red Violet Inc.",
    "RDHL": "Redhill Biopharma Ltd.",
    "RPAY": "Repay Holdings Corporation",
    "KRMD": "Repro Med Systems Inc.",
    "SPNS": "Sapiens International Corporati",
    "SCSC": "ScanSource Inc.",
    "SCWX": "SecureWorks Corp.",
    "SRE": "Sempra Energy",
    "SREV": "ServiceSource International In",
    "SLP": "Simulations Plus Inc.",
    "SLM": "SLM Corporation",
    "SGH": "SMART Global Holdings Inc.",
    "SMCI": "Super Micro Computer Inc.",
    "SYKE": "Sykes Enterprises Incorporated",
    "TAL": "TAL Education Group",
    "BX": "The Blackstone Group Inc.",
    "PLCE": "Children's Place Inc. (The)",
    "SHYF": "The Shyft Group Inc.",
    "TSCO": "Tractor Supply Company",
    "WCN": "Waste Connections Inc.",
    "WHR": "Whirlpool Corporation",
    "WIX": "Wix.com Ltd.",
    "WDAY": "Workday Inc.",
    "XNET": "Xunlei Limited",
    "SRCE": "1st Source Corporation",
    "AOS": "A.O. Smith Corporation",
    "ABMD": "ABIOMED Inc.",
    "ASIX": "AdvanSix Inc.",
    "ADVM": "Adverum Biotechnologies Inc.",
    "AGYS": "Agilysys Inc.",
    "AIMT": "Aimmune Therapeutics Inc.",
    "AIRG": "Airgain Inc.",
    "ALG": "Alamo Group Inc.",
    "ALBO": "Albireo Pharma Inc.",
    "ARE": "Alexandria Real Estate Equities",
    "ALL": "Allstate Corporation (The)",
    "AOSL": "Alpha and Omega Semiconductor L",
    "APLT": "Applied Therapeutics Inc.",
    "ARQT": "Arcutis Biotherapeutics Inc.",
    "AROW": "Arrow Financial Corporation",
    "ASB": "Associated Banc-Corp",
    "ASUR": "Asure Software Inc",
    "ATO": "Atmos Energy Corporation",
    "AN": "AutoNation Inc.",
    "AVY": "Avery Dennison Corporation",
    "AVRO": "AVROBIO Inc.",
    "AWRE": "Aware Inc.",
    "BMI": "Badger Meter Inc.",
    "BAX": "Baxter International Inc.",
    "BILL": "Bill.com Holdings Inc.",
    "BEAT": "BioTelemetry Inc.",
    "BAH": "Booz Allen Hamilton Holding Cor",
    "BRC": "Brady Corporation",
    "BRX": "Brixmor Property Group Inc.",
    "BRO": "Brown & Brown Inc.",
    "BC": "Brunswick Corporation",
    "BKE": "Buckle Inc. (The)",
    "BLDR": "Builders FirstSource Inc.",
    "CAI": "CAI International Inc.",
    "CPB": "Campbell Soup Company",
    "CATY": "Cathay General Bancorp",
    "CE": "Celanese Corporation Celanese C",
    "COLB": "Columbia Banking System Inc.",
    "CPRT": "Copart Inc.",
    "COR": "CoreSite Realty Corporation",
    "CTVA": "Corteva Inc.",
    "CRVL": "CorVel Corp.",
    "CZZ": "Cosan Limited",
    "CSGP": "CoStar Group Inc.",
    "CACC": "Credit Acceptance Corporation",
    "CREE": "Cree Inc.",
    "CSGS": "CSG Systems International Inc.",
    "CW": "Curtiss-Wright Corporation",
    "CYBE": "CyberOptics Corporation",
    "CTMX": "CytomX Therapeutics Inc.",
    "DVA": "DaVita Inc.",
    "DGII": "Digi International Inc.",
    "DMRC": "Digimarc Corporation",
    "DOV": "Dover Corporation",
    "DSPG": "DSP Group Inc.",
    "EGBN": "Eagle Bancorp Inc.",
    "EIX": "Edison International",
    "ESI": "Element Solutions Inc.",
    "ECPG": "Encore Capital Group Inc",
    "DAVA": "Endava plc",
    "FFIN": "First Financial Bankshares Inc",
    "FTS": "Fortis Inc.",
    "FEIM": "Frequency Electronics Inc.",
    "FREQ": "Frequency Therapeutics Inc.",
    "FULT": "Fulton Financial Corporation",
    "FUTU": "Futu Holdings Limited",
    "GDDY": "GoDaddy Inc.",
    "GDEN": "Golden Entertainment Inc.",
    "AJX": "Great Ajax Corp.",
    "HTLF": "Heartland Financial USA Inc.",
    "HLF": "Herbalife Nutrition Ltd.",
    "HCCI": "Heritage-Crystal Clean Inc.",
    "HNP": "Huaneng Power Intl",
    "HPP": "Hudson Pacific Properties Inc.",
    "HUM": "Humana Inc.",
    "INFO": "IHS Markit Ltd.",
    "INCY": "Incyte Corporation",
    "IPG": "Interpublic Group of Companies",
    "KALA": "Kala Pharmaceuticals Inc.",
    "K": "Kellogg Company",
    "KEQU": "Kewaunee Scientific Corporation",
    "KLAC": "KLA Corporation",
    "KFY": "Korn Ferry",
    "KRYS": "Krystal Biotech Inc.",
    "LNTH": "Lantheus Holdings Inc.",
    "LDOS": "Leidos Holdings Inc.",
    "MKTX": "MarketAxess Holdings Inc.",
    "MXIM": "Maxim Integrated Products Inc.",
    "MGTX": "MeiraGTx Holdings plc",
    "MIME": "Mimecast Limited",
    "MC": "Moelis & Company",
    "MPWR": "Monolithic Power Systems Inc.",
    "NSTG": "NanoString Technologies Inc.",
    "EDU": "New Oriental Education & Techno",
    "NWSA": "News Corporation",
    "ORLY": "O'Reilly Automotive Inc.",
    "ON": "ON Semiconductor Corporation",
    "KIDS": "OrthoPediatrics Corp.",
    "PLMR": "Palomar Holdings Inc.",
    "PASG": "Passage Bio Inc.",
    "PCTI": "PCTEL Inc.",
    "PLXS": "Plexus Corp.",
    "PRVB": "Provention Bio Inc.",
    "QADA": "QAD Inc.",
    "RMBS": "Rambus Inc.",
    "RF": "Regions Financial Corporation",
    "RCII": "Rent-A-Center Inc.",
    "RGCO": "RGC Resources Inc.",
    "RYTM": "Rhythm Pharmaceuticals Inc.",
    "RCKT": "Rocket Pharmaceuticals Inc.",
    "RUHN": "Ruhnn Holding Limited",
    "BFS": "Saul Centers Inc.",
    "SIGI": "Selective Insurance Group Inc.",
    "SSTK": "Shutterstock Inc.",
    "SWIR": "Sierra Wireless Inc.",
    "SWK": "Stanley Black & Decker Inc.",
    "STOK": "Stoke Therapeutics Inc.",
    "SYNA": "Synaptics Incorporated",
    "SNPS": "Synopsys Inc.",
    "TROW": "T. Rowe Price Group Inc.",
    "TXRH": "Texas Roadhouse Inc.",
    "GBX": "Greenbrier Companies Inc. (The",
    "TSBK": "Timberland Bancorp Inc.",
    "TKR": "Timken Company (The)",
    "TSC": "TriState Capital Holdings Inc.",
    "TTMI": "TTM Technologies Inc.",
    "ULTA": "Ulta Beauty Inc.",
    "URI": "United Rentals Inc.",
    "USM": "United States Cellular Corporat",
    "VREX": "Varex Imaging Corporation",
    "VRNS": "Varonis Systems Inc.",
    "VECO": "Veeco Instruments Inc.",
    "VRTU": "Virtusa Corporation",
    "VYGR": "Voyager Therapeutics Inc.",
    "VMC": "Vulcan Materials Company (Holdi",
    "WAFD": "Washington Federal Inc.",
    "WK": "Workiva Inc.",
    "ZION": "Zions Bancorporation N.A.",
    "QFIN": "360 Finance Inc.",
    "ACIW": "ACI Worldwide Inc.",
    "ADUS": "Addus HomeCare Corporation",
    "AAP": "Advance Auto Parts Inc Advance ",
    "AERI": "Aerie Pharmaceuticals Inc.",
    "AMG": "Affiliated Managers Group Inc.",
    "AGIO": "Agios Pharmaceuticals Inc.",
    "ADC": "Agree Realty Corporation",
    "AKCA": "Akcea Therapeutics Inc.",
    "AKRO": "Akero Therapeutics Inc.",
    "ALC": "Alcon Inc.",
    "ALX": "Alexander's Inc.",
    "ALLK": "Allakos Inc.",
    "ALLE": "Allegion plc",
    "LNT": "Alliant Energy Corporation",
    "APEI": "American Public Education Inc.",
    "AMSWA": "American Software Inc.",
    "CRMT": "America's Car-Mart Inc.",
    "AMSF": "AMERISAFE Inc.",
    "AME": "AMETEK Inc.",
    "ADI": "Analog Devices Inc.",
    "ATEX": "Anterix Inc.",
    "AMEH": "Apollo Medical Holdings Inc.",
    "APRE": "Aprea Therapeutics Inc.",
    "ARDX": "Ardelyx Inc.",
    "AGX": "Argan Inc.",
    "ASGN": "ASGN Incorporated",
    "AC": "Associated Capital Group Inc.",
    "ATNX": "Athenex Inc.",
    "AUB": "Atlantic Union Bankshares Corpo",
    "ATNI": "ATN International Inc.",
    "ATHM": "Autohome Inc.",
    "AZO": "AutoZone Inc.",
    "AVNS": "Avanos Medical Inc.",
    "AVTR": "Avantor Inc.",
    "AXNX": "Axonics Modulation Technologies",
    "BCPC": "Balchem Corporation",
    "BLL": "Ball Corporation",
    "BECN": "Beacon Roofing Supply Inc.",
    "BEAM": "Beam Therapeutics Inc.",
    "BDC": "Belden Inc",
    "BHE": "Benchmark Electronics Inc.",
    "BTAI": "BioXcel Therapeutics Inc.",
    "BCOR": "Blucora Inc.",
    "BOKF": "BOK Financial Corporation",
    "BWA": "BorgWarner Inc.",
    "BOMN": "Boston Omaha Corporation",
    "BDGE": "Bridge Bancorp Inc.",
    "BCOV": "Brightcove Inc.",
    "BRKS": "Brooks Automation Inc.",
    "BURL": "Burlington Stores Inc.",
    "CABO": "Cable One Inc.",
    "CCMP": "Cabot Microelectronics Corporat",
    "CATM": "Cardtronics plc",
    "CDNA": "CareDx Inc.",
    "CSL": "Carlisle Companies Incorporated",
    "CSTL": "Castle Biosciences Inc.",
    "CNTG": "Centogene N.V.",
    "CERN": "Cerner Corporation",
    "CEVA": "CEVA Inc.",
    "CHUY": "Chuy's Holdings Inc.",
    "CTAS": "Cintas Corporation",
    "CHCO": "City Holding Company",
    "CMS": "CMS Energy Corporation",
    "COHR": "Coherent Inc.",
    "CFX": "Colfax Corporation",
    "CBU": "Community Bank System Inc.",
    "CPSI": "Computer Programs and Systems ",
    "CTG": "Computer Task Group Incorporat",
    "CRNX": "Crinetics Pharmaceuticals Inc.",
    "CTS": "CTS Corporation",
    "CVBF": "CVB Financial Corporation",
    "DHI": "D.R. Horton Inc.",
    "DJCO": "Daily Journal Corp. (S.C.)",
    "DMTK": "DermTech Inc.",
    "DIOD": "Diodes Incorporated",
    "DTE": "DTE Energy Company",
    "EGRX": "Eagle Pharmaceuticals Inc.",
    "LOCO": "El Pollo Loco Holdings Inc.",
    "ENTA": "Enanta Pharmaceuticals Inc.",
    "ENV": "Envestnet Inc",
    "EVA": "Enviva Partners LP",
    "PLUS": "ePlus inc.",
    "EFX": "Equifax Inc.",
    "ERIE": "Erie Indemnity Company",
    "ESTA": "Establishment Labs Holdings Inc",
    "EXPI": "eXp World Holdings Inc.",
    "EXPO": "Exponent Inc.",
    "FFIV": "F5 Networks Inc.",
    "FGEN": "FibroGen Inc",
    "FITB": "Fifth Third Bancorp",
    "FCNCA": "First Citizens BancShares Inc.",
    "FHB": "First Hawaiian Inc.",
    "FORM": "FormFactor Inc.",
    "FORR": "Forrester Research Inc.",
    "FTDR": "frontdoor inc.",
    "GATX": "GATX Corporation",
    "GCP": "GCP Applied Technologies Inc.",
    "GFN": "General Finance Corporation",
    "GL": "Globe Life Inc.",
    "GSHD": "Goosehead Insurance Inc.",
    "GHG": "GreenTree Hospitality Group Ltd",
    "GDYN": "Grid Dynamics Holdings Inc.",
    "GSIT": "GSI Technology Inc.",
    "HIG": "Hartford Financial Services Gro",
    "HSTM": "HealthStream Inc.",
    "HSII": "Heidrick & Struggles Internatio",
    "HMSY": "HMS Holdings Corp",
    "HUBB": "Hubbell Inc",
    "IMAB": "I-MAB",
    "ICHR": "Ichor Holdings",
    "IBKR": "Interactive Brokers Group Inc.",
    "IFF": "Internationa Flavors & Fragranc",
    "ISBC": "Investors Bancorp Inc.",
    "IPGP": "IPG Photonics Corporation",
    "ITRI": "Itron Inc.",
    "JBHT": "J.B. Hunt Transport Services I",
    "MAYS": "J. W. Mays Inc.",
    "JBL": "Jabil Inc.",
    "J": "Jacobs Engineering Group Inc.",
    "JRVR": "James River Group Holdings Ltd",
    "JBT": "John Bean Technologies Corporat",
    "KAI": "Kadant Inc",
    "KE": "Kimball Electronics Inc.",
    "KURA": "Kura Oncology Inc.",
    "LKFN": "Lakeland Financial Corporation",
    "TREE": "LendingTree Inc.",
    "LNC": "Lincoln National Corporation",
    "LFUS": "Littelfuse Inc.",
    "RAMP": "LiveRamp Holdings Inc.",
    "MANH": "Manhattan Associates Inc.",
    "MAN": "ManpowerGroup",
    "MLM": "Martin Marietta Materials Inc.",
    "MAS": "Masco Corporation",
    "MXL": "MaxLinear Inc.",
    "MGEE": "MGE Energy Inc.",
    "MTEM": "Molecular Templates Inc.",
    "MORF": "Morphic Holding Inc.",
    "COOP": "Mr. Cooper Group Inc.",
    "MUSA": "Murphy USA Inc.",
    "NSSC": "NAPCO Security Technologies In",
    "NTCT": "NetScout Systems Inc.",
    "NEWR": "New Relic Inc.",
    "NWS": "News Corporation",
    "NGM": "NGM Biopharmaceuticals Inc.",
    "NLSN": "Nielsen N.V.",
    "NWBI": "Northwest Bancshares Inc.",
    "NUAN": "Nuance Communications Inc.",
    "NUVA": "NuVasive Inc.",
    "ODT": "Odonate Therapeutics Inc.",
    "ODFL": "Old Dominion Freight Line Inc.",
    "ONB": "Old National Bancorp",
    "OLLI": "Ollie's Bargain Outlet Holdings",
    "OFIX": "Orthofix Medical Inc.",
    "OSIS": "OSI Systems Inc.",
    "OI": "O-I Glass Inc.",
    "OYST": "Oyster Point Pharma Inc.",
    "PCAR": "PACCAR Inc.",
    "PKE": "Park Aerospace Corp.",
    "PTNR": "Partner Communications Company ",
    "PCTY": "Paylocity Holding Corporation",
    "PDFS": "PDF Solutions Inc.",
    "PEGA": "Pegasystems Inc.",
    "PRGO": "Perrigo Company plc",
    "PPD": "PPD Inc.",
    "PAHC": "Phibro Animal Health Corporatio",
    "PNFP": "Pinnacle Financial Partners In",
    "POR": "Portland General Electric Co",
    "POWL": "Powell Industries Inc.",
    "POWI": "Power Integrations Inc.",
    "PRVL": "Prevail Therapeutics Inc.",
    "PGR": "Progressive Corporation (The)",
    "PRO": "PROS Holdings Inc.",
    "PRTA": "Prothena Corporation plc",
    "PWR": "Quanta Services Inc.",
    "RAPT": "RAPT Therapeutics Inc.",
    "RP": "RealPage Inc.",
    "REPL": "Replimune Group Inc.",
    "RVNC": "Revance Therapeutics Inc.",
    "RXN": "Rexnord Corporation",
    "RMNI": "Rimini Street Inc.",
    "RMR": "The RMR Group Inc.",
    "ROK": "Rockwell Automation Inc.",
    "ROP": "Roper Technologies Inc.",
    "RUBY": "Rubius Therapeutics Inc.",
    "SAFT": "Safety Insurance Group Inc.",
    "SAFM": "Sanderson Farms Inc.",
    "SASR": "Sandy Spring Bancorp Inc.",
    "SCHN": "Schnitzer Steel Industries Inc",
    "SRRK": "Scholar Rock Holding Corporatio",
    "SMTC": "Semtech Corporation",
    "SHW": "Sherwin-Williams Company (The)",
    "SCVL": "Shoe Carnival Inc.",
    "SIBN": "SI-BONE Inc.",
    "SIGA": "SIGA Technologies Inc.",
    "SIGM": "SIFCO Industries Inc. Common S",
    "SILC": "Silicom Ltd",
    "SLAB": "Silicon Laboratories Inc.",
    "SINA": "Sina Corporation",
    "SITE": "SiteOne Landscape Supply Inc.",
    "SITM": "SiTime Corporation",
    "SOHU": "Sohu.com Limited",
    "SBSI": "Southside Bancshares Inc.",
    "SWX": "Southwest Gas Holdings Inc.",
    "SPSC": "SPS Commerce Inc.",
    "SPXC": "SPX Corporation",
    "FLOW": "SPX FLOW Inc.",
    "SSNC": "SS&C Technologies Holdings Inc",
    "SXI": "Standex International Corporati",
    "SRCL": "Stericycle Inc.",
    "STRA": "Strategic Education Inc.",
    "SUI": "Sun Communities Inc.",
    "SGRY": "Surgery Partners Inc.",
    "SRDX": "Surmodics Inc.",
    "SNDX": "Syndax Pharmaceuticals Inc.",
    "SNX": "Synnex Corporation",
    "TARO": "Taro Pharmaceutical Industries ",
    "TNC": "Tennant Company",
    "TTEK": "Tetra Tech Inc.",
    "TCBI": "Texas Capital Bancshares Inc.",
    "HSY": "The Hershey Company",
    "BLD": "TopBuild Corp.",
    "TRNS": "Transcat Inc.",
    "TBIO": "Translate Bio Inc.",
    "TRU": "TransUnion",
    "TCDA": "Tricida Inc.",
    "TRMB": "Trimble Inc.",
    "UMBF": "UMB Financial Corporation",
    "UBSI": "United Bankshares Inc.",
    "UIHC": "United Insurance Holdings Corp.",
    "UTL": "UNITIL Corporation",
    "UHS": "Universal Health Services Inc.",
    "VCYT": "Veracyte Inc.",
    "VRSN": "VeriSign Inc.",
    "VSEC": "VSE Corporation",
    "WAT": "Waters Corporation",
    "WLDN": "Willdan Group Inc.",
    "WING": "Wingstop Inc.",
    "WTFC": "Wintrust Financial Corporation",
    "ZBRA": "Zebra Technologies Corporation",
    "ZBH": "Zimmer Biomet Holdings Inc.",
    "ZUMZ": "Zumiez Inc."]

// MARK: -- For Logo Loading

let myDic_Symb2Img: [String:String] =
    ["AMZN": "amazon.com",
    "BA": "boeing.com",
    "TSLA": "tesla.com",
    "TLRY": "tilray.com",
    "AAPL": "apple.com",
    "NIO": "nio.com",
    "AAL": "aa.com",
    "DAL": "deltaairlines-flights.com",
    "MSFT": "microsoft.com",
    "KO": "coca-colacompany.com",
    "DIS": "waltdisney.org",
    "GOOGL": "google.com",
    "BYND": "beyondmeat.com",
    "FB": "facebook.com",
    "MCD": "mcdonalds.com.au",
    "NFLX": "netflix.com",
    "SDC": "smiledirectclub.com",
    "SNE": "sony.net",
    "AMD": "amd.com",
    "NVDA": "nvidia.com",
    "UBER": "uber.com",
    "UAA": "underarmour.com",
    "BABA": "alibabagroup.com",
    "T": "att.com",
    "IVR": "invesco.com",
    "RCL": "rccl.com",
    "WORK": "slack.com",
    "SPCE": "virgingalactic.com",
    "CPE": "callon.com",
    "ZM": "zoom.us",
    "NKE": "nike.com",
    "OXY": "oxy.com",
    "V": "visa.com",
    "APHA": "aphriainc.com",
    "SNAP": "snapchat.com",
    "BAC": "bankofamerica.com",
    "CGC": "canopygrowth.com",
    "JNJ": "jnj.com",
    "PYPL": "paypal.com",
    "KOS": "kosmosenergy.com",
    "MA": "mastercard.com.au",
    "SBUX": "starbucks.com",
    "VFF": "villagefarms.com",
    "GE": "generalelectric-eg.com",
    "PTON": "onepeloton.com",
    "LUV": "southwest.com",
    "IBM": "ibm.com",
    "O": "realtyincome.com",
    "SQ": "squareup.com",
    "PFE": "pfizer.com",
    "TWTR": "twitter.com",
    "ADBE": "adobe.com",
    "CRON": "thecronosgroup.com",
    "GILD": "gilead.com",
    "HAL": "halliburton.com",
    "GRUB": "grubhub.com",
    "MRO": "marathonoil.com",
    "RIG": "deepwater.com",
    "WMT": "walmart.com",
    "SHOP": "shopify.com",
    "SAVE": "spirit.com",
    "AXP": "americanexpress.com",
    "INTC": "intel.com",
    "QCOM": "qualcomm.com",
    "NOK": "nokia.com",
    "PEP": "pepsico.com",
    "ABBV": "abbvie.com.",
    "ATVI": "activisionblizzard.com",
    "EA": "ea.com",
    "MDT": "medtronic.com",
    "GOOG": "google.com",
    "MO": "altria.com",
    "TLRD": "tailoredbrands.com",
    "BMO": "bmo.com",
    "PK": "pkhotelsandresorts.com",
    "CAR": "avisbudgetgroup.com",
    "GWPH": "gwpharm.com",
    "JD": "jd.com",
    "LTRPA": "tripadvisor.com",
    "MAC": "macerich.com",
    "ZNGA": "zynga.com",
    "GM": "gm.com",
    "MAR": "marriott.com",
    "STOR": "storecapital.com",
    "APA": "apachecorp.com",
    "CRBP": "corbuspharma.com",
    "SPOT": "spotify.com",
    "CRWD": "crowdstrike.com",
    "COTY": "coty.com",
    "NAT": "###",
    "PINS": "pinterest.com",
    "COST": "costco.com",
    "TSM": "tsmc.com",
    "PRGS": "progress.com",
    "AGNC": "###",
    "LAKE": "lakeland.com",
    "TSN": "tysonfoodservice.com",
    "EBAY": "ebay.com",
    "OKTA": "okta.com",
    "SYY": "sysco.com",
    "ABT": "abbott.com",
    "GS": "goldmansachs.com",
    "LYFT": "lyft.com",
    "WBA": "walgreensbootsalliance.com",
    "NET": "cloudflare.com",
    "ROKU": "roku.com",
    "HPE": "hpe.com",
    "DXCM": "dexcom.com",
    "LVGO": "livongo.com",
    "BCRX": "biocryst.com",
    "TDOC": "teladochealth.com",
    "BKNG": "bookingholdings.com",
    "EB": "eventbrite.com",
    "GCI": "gannett.com",
    "RVLV": "revolve.com",
    "KHC": "kraftheinzcompany.com",
    "ORCL": "oracle.com",
    "ENPH": "enphase.com",
    "LMT": "lmco.com",
    "PSX": "phillips.com",
    "TTWO": "take2games.com",
    "SABR": "sabre.com",
    "PM": "pmi.com",
    "GNPX": "genprex.com",
    "CAT": "caterpillar.com",
    "ELF": "elfcosmetics.com",
    "MAIN": "mainstcapital.com",
    "SONO": "sonos.com",
    "DDOG": "datadoghq.com",
    "FSLY": "fastly.com",
    "KMI": "kindermorgan.com",
    "FUV": "arcimoto.com",
    "EPD": "enterpriseproducts.com",
    "LTC": "ltcreit.com",
    "CCI": "crowncastle.com",
    "MANU": "manutd.com",
    "MRVL": "marvell.com",
    "SLB": "slb.com",
    "TWLO": "twilio.com",
    "TRIP": "tripadvisor.com",
    "IRM": "ironmountain.com",
    "SE": "sealimited.com",
    "AKTS": "akoustis.com",
    "AMGN": "amgen.com",
    "BE": "bloomenergy.com",
    "PBA": "pembina.com",
    "BBBY": "bedbathandbeyond.com",
    "OMP": "###",
    "BIDU": "baidu.com",
    "ENB": "enbridge.com",
    "FL": "footlocker.com",
    "GPRO": "gopro.com",
    "HPQ": "hp.com",
    "SEDG": "solaredge.com",
    "AUY": "yamana.com",
    "EPR": "eprkc.com",
    "PSEC": "prospectcap.com",
    "STAG": "stagindustrial.com",
    "AVGO": "broadcom.com",
    "LLY": "lilly.com",
    "KSS": "kohls.com",
    "FTI": "technipfmc.com",
    "BNTX": "biontech.de",
    "IRBT": "irobot.com",
    "BTU": "peabodyenergy.com",
    "PBI": "pitneybowes.com",
    "LEG": "leggett.com",
    "SWKS": "skyworksinc.com",
    "TXMD": "therapeuticsmd.com",
    "CNK": "cinemark.com ",
    "INMD": "inmode.com",
    "JWN": "nordstrom.com",
    "UNP": "up.com",
    "COP": "conocophillips.com",
    "MPC": "marathonpetroleum.com",
    "UPS": "ups.com",
    "CPTA": "capitalagroup.com",
    "ENDP": "endicia.com",
    "NEM": "newmont.com",
    "PRU": "prudential.com",
    "SYK": "stryker.com",
    "AAXN": "enterprises.co.uk",
    "EOG": "eogresources.com",
    "APPN": "appian.com",
    "KOPN": "kopin.com",
    "GT": "goodyeartrucktires.com",
    "MDB": "mongodb.com",
    "BEP": "evolugen.com",
    "FSLR": "firstsolar.com",
    "IVZ": "invesco.com",
    "VSLR": "vivintsolar.com",
    "SIRI": "siriusxm.com",
    "AMT": "americantower.com",
    "CL": "colgatepalmolive.com",
    "PLYA": "playaresorts.com",
    "APPS": "digitalturbine.com",
    "EDIT": "editasmedicine.com",
    "KMB": "kimberly-clark.com",
    "TXN": "ti.com",
    "BPY": "###",
    "SO": "southerncompany.com",
    "ACOR": "acorda.com",
    "HRL": "hormelfoods.com",
    "WDC": "westerndigital.com",
    "CHWY": "chewy.com",
    "FANG": "diamondback.com",
    "FRT": "federalrealty.com",
    "PNC": "pnc.com",
    "AFL": "aflac.com",
    "NOV": "nov.com",
    "CLX": "thecloroxcompany.com",
    "TJX": "tjx.com",
    "ATRO": "astronics.com",
    "VRTX": "vrtx.com",
    "ARCO": "arcosdorados.com",
    "DELL": "delltechnologies.com",
    "D": "dominionenergy.com",
    "JKS": "jinkosolar.com",
    "PBR": "petrobras.com.br",
    "SJR": "shaw.ca",
    "RY": "rbcroyalbank.com",
    "CRSP": "crisprtx.com",
    "FIT": "fitbit.com",
    "GERN": "geron.com",
    "MAXR": "maxar.com",
    "RGLD": "royalgold.com",
    "SWN": "swn.com",
    "TMUS": "t-mobile.pl",
    "NVTA": "invitae.com",
    "MPW": "medicalpropertiestrust.com",
    "SFIX": "stitchfix.com",
    "WSR": "whitestonereit.com",
    "ANIP": "###",
    "CQP": "cheniere.com",
    "GLW": "corning.com",
    "ESTC": "elastic.co",
    "HAS": "hasbro.com",
    "STNE": "###",
    "TEVA": "tevausa.com",
    "WATT": "energous.com",
    "IIPR": "innovativeindustrialproperties.com",
    "PVH": "pvh.com",
    "BGFV": "big5sportinggoods.com",
    "CCEP": "cokecce.com",
    "ED": "coned.com",
    "DRI": "darden.com",
    "LADR": "ladderfunds.com",
    "NEP": "nexteraenergypartners.com",
    "ADPT": "adaptivebiotech.com",
    "BIIB": "biogen.com",
    "ILMN": "illumina.com",
    "LOW": "lowes.com",
    "PCG": "Pacific Gas & Electric Co.",
    "PDD": "Pinduoduo Inc.",
    "QD": "Qudian Inc.",
    "BNS": "Bank Nova Scotia Halifax Pfd 3",
    "ZTS": "Zoetis Inc.",
    "ARLP": "Alliance Resource Partners L.P",
    "ADP": "Automatic Data Processing Inc.",
    "BKR": "Baker Hughes Company",
    "LYB": "LyondellBasell Industries NV",
    "NRG": "NRG Energy Inc.",
    "SMAR": "Smartsheet Inc.",
    "XBIT": "XBiotech Inc.",
    "AA": "Alcoa Corporation",
    "DISCA": "Discovery Inc. - Series A",
    "EMR": "Emerson Electric Company",
    "EL": "Estee Lauder Companies Inc. (T",
    "SLG": "SL Green Realty Corp",
    "ZS": "Zscaler Inc.",
    "ALB": "Albemarle Corporation",
    "BBY": "Best Buy Co. Inc.",
    "BPYU": "Brookfield Property REIT Inc.",
    "CAN": "Canaan Inc.",
    "DOW": "Dow Inc.",
    "GPC": "Genuine Parts Company",
    "INSG": "Inseego Corp.",
    "OHI": "Omega Healthcare Investors Inc",
    "UNM": "Unum Group",
    "VNOM": "Viper Energy Partners LP",
    "WRTC": "Wrap Technologies Inc.",
    "AIR": "AAR Corp.",
    "BIP": "Brookfield Infrastructure Partn",
    "CHL": "China Mobile Limited",
    "GIS": "General Mills Inc.",
    "GEOS": "Geospace Technologies Corporati",
    "LIN": "Linde plc",
    "NPTN": "NeoPhotonics Corporation",
    "NVO": "Novo Nordisk A/S",
    "RUTH": "Ruth's Hospitality Group Inc.",
    "SCM": "Stellus Capital Investment Corp",
    "REAL": "The RealReal Inc.",
    "VERI": "Veritone Inc.",
    "AVAV": "AeroVironment Inc.",
    "ADM": "Archer-Daniels-Midland Company",
    "TEAM": "Atlassian Corporation Plc",
    "GLOG": "GasLog Ltd.",
    "MMP": "Magellan Midstream Partners L.P",
    "NUE": "Nucor Corporation",
    "VIR": "Vir Biotechnology Inc.",
    "AMAT": "Applied Materials Inc.",
    "DFS": "Discover Financial Services",
    "GAIN": "Gladstone Investment Corporatio",
    "LBTYA": "Liberty Global plc",
    "LTHM": "Livent Corporation",
    "MET": "MetLife Inc.",
    "NMRK": "Newmark Group Inc.",
    "PING": "Ping Identity Holding Corp.",
    "TM": "Toyota Motor Corporation",
    "XLNX": "Xilinx Inc.",
    "AER": "AerCap Holdings N.V.",
    "ADSK": "Autodesk Inc.",
    "BCEI": "Bonanza Creek Energy Inc.",
    "CPRI": "Capri Holdings Limited",
    "ECL": "Ecolab Inc.",
    "GOGO": "Gogo Inc.",
    "INTU": "Intuit Inc.",
    "LEVI": "Levi Strauss & Co",
    "NK": "NantKwest Inc.",
    "SUNS": "Solar Senior Capital Ltd.",
    "SPWR": "SunPower Corporation",
    "CHEF": "The Chefs' Warehouse Inc.",
    "VMW": "Vmware Inc.",
    "WPC": "W. P. Carey Inc. REIT",
    "ADS": "Alliance Data Systems Corporati",
    "LAND": "Gladstone Land Corporation",
    "GLUU": "Glu Mobile Inc.",
    "TMO": "Thermo Fisher Scientific Inc",
    "UXIN": "Uxin Limited",
    "WWE": "World Wrestling Entertainment ",
    "AES": "The AES Corporation",
    "ARI": "Apollo Commercial Real Estate F",
    "CM": "Canadian Imperial Bank of Comme",
    "HOG": "Harley-Davidson Inc.",
    "SKYW": "SkyWest Inc.",
    "SSYS": "Stratasys Ltd.",
    "SNCR": "Synchronoss Technologies Inc.",
    "ZEN": "Zendesk Inc.",
    "Z": "Zillow Group Inc.",
    "BZUN": "Baozun Inc.",
    "BSM": "Black Stone Minerals L.P.",
    "BYD": "Boyd Gaming Corporation",
    "CNP": "CenterPoint Energy Inc (Holdin",
    "COUP": "Coupa Software Incorporated",
    "GFL": "GFL Environmental Inc. Subordin",
    "EAF": "GrafTech International Ltd.",
    "HUYA": "HUYA Inc.",
    "IMMU": "Immunomedics Inc.",
    "MAT": "Mattel Inc.",
    "NOW": "ServiceNow Inc.",
    "SRT": "StarTek Inc.",
    "TD": "Toronto Dominion Bank (The)",
    "WRK": "Westrock Company",
    "AGRX": "Agile Therapeutics Inc.",
    "COG": "Cabot Oil & Gas Corporation",
    "GOOS": "Canada Goose Holdings Inc. Subo",
    "COF": "Capital One Financial Corporati",
    "CRT": "Cross Timbers Royalty Trust",
    "FIVN": "Five9 Inc.",
    "GLOP": "GasLog Partners LP",
    "HP": "Helmerich & Payne Inc.",
    "NLOK": "NortonLifeLock Inc.",
    "URBN": "Urban Outfitters Inc.",
    "WB": "Weibo Corporation",
    "ANF": "Abercrombie & Fitch Company",
    "AEM": "Agnico Eagle Mines Limited",
    "NLY": "Annaly Capital Management Inc",
    "CINF": "Cincinnati Financial Corporatio",
    "BEN": "Franklin Resources Inc.",
    "MNK": "Mallinckrodt plc",
    "NTES": "NetEase Inc.",
    "PBCT": "People's",
    "DTIL": "Precision BioSciences Inc.",
    "PBYI": "Puma Biotechnology Inc",
    "TWOU": "2U Inc.",
    "AKAM": "Akamai Technologies Inc.",
    "ANSS": "ANSYS Inc.",
    "BHC": "Bausch Health Companies Inc.",
    "BDSI": "BioDelivery Sciences Internatio",
    "BG": "Bunge Limited Bunge Limited",
    "CWH": "Camping World Holdings Inc.",
    "FUN": "Cedar Fair L.P.",
    "CMG": "Chipotle Mexican Grill Inc.",
    "EXC": "Exelon Corporation",
    "HBI": "Hanesbrands Inc.",
    "HRZN": "Horizon Technology Finance Corp",
    "MKC": "McCormick & Company Incorporat",
    "PDLI": "PDL BioPharma Inc.",
    "QRVO": "Qorvo Inc.",
    "SHAK": "Shake Shack Inc.",
    "SPLK": "Splunk Inc.",
    "SPT": "Sprout Social Inc",
    "STWD": "STARWOOD PROPERTY TRUST INC. S",
    "UVV": "Universal Corporation",
    "ALXN": "Alexion Pharmaceuticals Inc.",
    "BB": "BlackBerry Limited",
    "CRDF": "Cardiff Oncology Inc.",
    "CHU": "China Unicom (Hong Kong) Ltd",
    "CXW": "CoreCivic Inc.",
    "DLPH": "Delphi Technologies PLC",
    "EMN": "Eastman Chemical Company",
    "FTCH": "Farfetch Limited",
    "FIS": "Fidelity National Information S",
    "FLIR": "FLIR Systems Inc.",
    "GOOD": "Gladstone Commercial Corporatio",
    "LB": "L Brands Inc.",
    "MYL": "Mylan N.V.",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "RESN": "Resonant Inc.",
    "SPH": "Suburban Propane Partners L.P.",
    "VICI": "VICI Properties Inc.",
    "AL": "Air Lease Corporation",
    "KERN": "Akerna Corp.",
    "BNFT": "Benefitfocus Inc.",
    "BGSF": "BG Staffing Inc",
    "BXP": "Boston Properties Inc.",
    "SCHW": "Charles Schwab Corporation (The",
    "CLVS": "Clovis Oncology Inc.",
    "CME": "CME Group Inc.",
    "DLTR": "Dollar Tree Inc.",
    "EHTH": "eHealth Inc.",
    "FISV": "Fiserv Inc.",
    "FLR": "Fluor Corporation",
    "HASI": "Hannon Armstrong Sustainable In",
    "HBIO": "Harvard Bioscience Inc.",
    "IRDM": "Iridium Communications Inc",
    "JCI": "Johnson Controls International ",
    "NTAP": "NetApp Inc.",
    "PANW": "Palo Alto Networks Inc.",
    "TRUE": "TrueCar Inc.",
    "WSG": "Wanda Sports Group Company Limi",
    "W": "Wayfair Inc.",
    "WYND": "Wyndham Destinations Inc.",
    "APD": "Air Products and Chemicals Inc",
    "AZRE": "Azure Power Global Limited",
    "BBSI": "Barrett Business Services Inc.",
    "BLMN": "Bloomin' Brands Inc.",
    "CI": "Cigna Corporation",
    "CSX": "CSX Corporation",
    "DE": "Deere & Company",
    "EW": "Edwards Lifesciences Corporatio",
    "ENIA": "Enel Americas S.A.",
    "FTNT": "Fortinet Inc.",
    "FNV": "Franco-Nevada Corporation",
    "ITW": "Illinois Tool Works Inc.",
    "NTLA": "Intellia Therapeutics Inc.",
    "LAUR": "Laureate Education Inc.",
    "LAZ": "Lazard LTD. Lazard LTD.",
    "LEN": "Lennar Corporation",
    "LX": "LexinFintech Holdings Ltd.",
    "MELI": "MercadoLibre Inc.",
    "MCRI": "Monarch Casino & Resort Inc.",
    "NTGR": "NETGEAR Inc.",
    "PD": "PagerDuty Inc.",
    "PAA": "Plains All American Pipeline L",
    "QTT": "Qutoutiao Inc.",
    "SHO": "Sunstone Hotel Investors Inc. ",
    "TER": "Teradyne Inc.",
    "MOS": "Mosaic Company (The)",
    "TIF": "Tiffany & Co.",
    "VLY": "Valley National Bancorp",
    "VKTX": "Viking Therapeutics Inc.",
    "WES": "Western Midstream Partners LP",
    "ALEX": "Alexander & Baldwin Inc.",
    "AMBA": "Ambarella Inc.",
    "AWR": "American States Water Company",
    "ANET": "Arista Networks Inc.",
    "BIG": "Big Lots Inc.",
    "CHRS": "Coherus BioSciences Inc.",
    "CONE": "CyrusOne Inc",
    "EQT": "EQT Corporation",
    "EXTR": "Extreme Networks Inc.",
    "HEP": "Holly Energy Partners L.P.",
    "IMGN": "ImmunoGen Inc.",
    "IPHI": "Inphi Corporation",
    "ICE": "Intercontinental Exchange Inc.",
    "JEF": "Jefferies Financial Group Inc.",
    "JNPR": "Juniper Networks Inc.",
    "LSCC": "Lattice Semiconductor Corporati",
    "LIZI": "LIZHI INC.",
    "LITE": "Lumentum Holdings Inc.",
    "MCY": "Mercury General Corporation",
    "MDP": "Meredith Corporation",
    "MHK": "Mohawk Industries Inc.",
    "NDAQ": "Nasdaq Inc.",
    "NAVI": "Navient Corporation",
    "PACB": "Pacific Biosciences of Californ",
    "PAVM": "PAVmed Inc.",
    "PAYX": "Paychex Inc.",
    "PRFT": "Perficient Inc.",
    "QIWI": "QIWI plc",
    "SSTI": "ShotSpotter Inc.",
    "SPWH": "Sportsman's Warehouse Holdings",
    "SUPN": "Supernus Pharmaceuticals Inc.",
    "VRNT": "Verint Systems Inc.",
    "VIRT": "Virtu Financial Inc.",
    "WY": "Weyerhaeuser Company",
    "YNDX": "Yandex N.V.",
    "YJ": "Yunji Inc. - American Depositor",
    "ACCO": "Acco Brands Corporation",
    "ALRM": "Alarm.com Holdings Inc.",
    "MDRX": "Allscripts Healthcare Solutions",
    "ARCT": "Arcturus Therapeutics Holdings ",
    "ARLO": "Arlo Technologies Inc.",
    "ATRA": "Atara Biotherapeutics Inc.",
    "AVDL": "Avadel Pharmaceuticals plc",
    "AVID": "Avid Technology Inc.",
    "BBDC": "Barings BDC Inc.",
    "BLUE": "bluebird bio Inc.",
    "BSX": "Boston Scientific Corporation",
    "BOX": "Box Inc.",
    "CCJ": "Cameco Corporation",
    "CARG": "CarGurus Inc.",
    "KMX": "CarMax Inc",
    "CTSH": "Cognizant Technology Solutions ",
    "COMM": "CommScope Holding Company Inc.",
    "TACO": "Del Taco Restaurants Inc.",
    "DKS": "Dick's Sporting Goods Inc",
    "EPAM": "EPAM Systems Inc.",
    "FCPT": "Four Corners Property Trust In",
    "FOXA": "Fox Corporation",
    "HRB": "H&R Block Inc.",
    "IVAC": "Intevac Inc.",
    "LILA": "Liberty Latin America Ltd.",
    "LPSN": "LivePerson Inc.",
    "L": "Loews Corporation",
    "MDU": "MDU Resources Group Inc.",
    "VIVO": "Meridian Bioscience Inc.",
    "MNR": "Monmouth Real Estate Investment",
    "MYGN": "Myriad Genetics Inc.",
    "NC": "NACCO Industries Inc.",
    "NH": "NantHealth Inc.",
    "PH": "Parker-Hannifin Corporation",
    "PT": "Pintec Technology Holdings Limi",
    "QTNT": "Quotient Limited",
    "ROST": "Ross Stores Inc.",
    "SEAC": "SeaChange International Inc.",
    "SYNC": "Synacor Inc.",
    "TRP": "TC Energy Corporation",
    "TDC": "Teradata Corporation",
    "VFC": "V.F. Corporation",
    "VRSK": "Verisk Analytics Inc.",
    "XYL": "Xylem Inc.",
    "ACIU": "AC Immune SA",
    "AMRC": "Ameresco Inc.",
    "AEP": "American Electric Power Company",
    "AFIN": "American Finance Trust Inc.",
    "AMKR": "Amkor Technology Inc.",
    "AMPH": "Amphastar Pharmaceuticals Inc.",
    "ATRS": "Antares Pharma Inc.",
    "AON": "Aon plc",
    "ARC": "ARC Document Solutions Inc.",
    "ATHX": "Athersys Inc.",
    "AVA": "Avista Corporation",
    "BAND": "Bandwidth Inc.",
    "BYSI": "BeyondSpring Inc.",
    "BHP": "BHP Group Limited",
    "BJ": "BJ's Wholesale Club Holdings I",
    "BBIO": "BridgeBio Pharma Inc.",
    "CVGW": "Calavo Growers Inc.",
    "CVNA": "Carvana Co.",
    "CRNT": "Ceragon Networks Ltd.",
    "XEC": "Cimarex Energy Co",
    "CTXS": "Citrix Systems Inc.",
    "CODI": "Compass Diversified Holdings Sh",
    "CEIX": "CONSOL Energy Inc.",
    "CRTO": "Criteo S.A.",
    "CCRN": "Cross Country Healthcare Inc.",
    "CMI": "Cummins Inc.",
    "DAR": "Darling Ingredients Inc.",
    "DISCK": "Discovery Inc. - Series C",
    "EQR": "Equity Residential",
    "ESPR": "Esperion Therapeutics Inc.",
    "ESS": "Essex Property Trust Inc.",
    "EVR": "Evercore Inc.",
    "ES": "Eversource Energy (D/B/A)",
    "EXTN": "Exterran Corporation",
    "FRG": "Franchise Group Inc.",
    "HEES": "H&E Equipment Services Inc.",
    "HSIC": "Henry Schein Inc.",
    "HBAN": "Huntington Bancshares Incorpora",
    "IDXX": "IDEXX Laboratories Inc.",
    "IHRT": "iHeartMedia Inc.",
    "IMMR": "Immersion Corporation",
    "IP": "International Paper Company",
    "KEY": "KeyCorp",
    "KIM": "Kimco Realty Corporation",
    "KKR": "KKR & Co. Inc.",
    "KTB": "Kontoor Brands Inc.",
    "LMRK": "Landmark Infrastructure Partner",
    "LGC": "Legacy Acquisition Corp.",
    "LBTYK": "Liberty Global plc",
    "LILAK": "Liberty Latin America Ltd.",
    "MTSI": "MACOM Technology Solutions Hold",
    "MRUS": "Merus N.V.",
    "MCHP": "Microchip Technology Incorporat",
    "MTSC": "MTS Systems Corporation",
    "NREF": "NexPoint Real Estate Finance I",
    "NTR": "Nutrien Ltd.",
    "ORA": "Ormat Technologies Inc.",
    "PLAB": "Photronics Inc.",
    "PLD": "Prologis Inc.",
    "PSA": "Public Storage",
    "QRTEA": "Liberty Interactive Corporation",
    "RGP": "Resources Connection Inc.",
    "R": "Ryder System Inc.",
    "SAGE": "Sage Therapeutics Inc.",
    "SBGI": "Sinclair Broadcast Group Inc.",
    "SNA": "Snap-On Incorporated",
    "TRGP": "Targa Resources Inc.",
    "TH": "Target Hospitality Corp.",
    "TMDX": "TransMedics Group Inc.",
    "TRUP": "Trupanion Inc.",
    "UCTT": "Ultra Clean Holdings Inc.",
    "UMH": "UMH Properties Inc.",
    "GWW": "W.W. Grainger Inc.",
    "WTS": "Watts Water Technologies Inc.",
    "WWD": "Woodward Inc.",
    "YUMC": "Yum China Holdings Inc.",
    "JFU": "9F Inc.",
    "ATEN": "A10 Networks Inc.",
    "ACHC": "Acadia Healthcare Company Inc.",
    "ADNT": "Adient plc",
    "AEIS": "Advanced Energy Industries Inc",
    "ACM": "AECOM",
    "A": "Agilent Technologies Inc.",
    "AMED": "Amedisys Inc",
    "AMN": "AMN Healthcare Services Inc AMN",
    "PLAN": "Anaplan Inc.",
    "ANAB": "AnaptysBio Inc.",
    "ANIK": "Anika Therapeutics Inc.",
    "APPF": "AppFolio Inc.",
    "AROC": "Archrock Inc.",
    "AIZ": "Assurant Inc.",
    "ATOM": "Atomera Incorporated",
    "AVT": "Avnet Inc.",
    "AXS": "Axis Capital Holdings Limited",
    "BGS": "B&G Foods Inc. B&G Foods Inc.",
    "BMRN": "BioMarin Pharmaceutical Inc.",
    "BJRI": "BJ's Restaurants Inc.",
    "BKH": "Black Hills Corporation",
    "EPAY": "Bottomline Technologies Inc.",
    "BV": "BrightView Holdings Inc.",
    "CDNS": "Cadence Design Systems Inc.",
    "CAMP": "CalAmp Corp.",
    "CARA": "Cara Therapeutics Inc.",
    "CF": "CF Industries Holdings Inc.",
    "CHTR": "Charter Communications Inc.",
    "COLL": "Collegium Pharmaceutical Inc.",
    "CAG": "ConAgra Brands Inc.",
    "BAP": "Credicorp Ltd.",
    "CRESY": "Cresud S.A.C.I.F. y A.",
    "CUE": "Cue Biopharma Inc.",
    "DAKT": "Daktronics Inc.",
    "DISH": "DISH Network Corporation",
    "DEI": "Douglas Emmett Inc.",
    "SATS": "EchoStar Corporation",
    "ENIC": "Enel Chile S.A.",
    "MRAM": "Everspin Technologies Inc.",
    "EXR": "Extra Space Storage Inc",
    "FDS": "FactSet Research Systems Inc.",
    "FAST": "Fastenal Company",
    "FLT": "FleetCor Technologies Inc.",
    "GTHX": "G1 Therapeutics Inc.",
    "GTX": "Garrett Motion Inc.",
    "GNTX": "Gentex Corporation",
    "HLNE": "Hamilton Lane Incorporated",
    "HCA": "HCA Healthcare Inc.",
    "HUBS": "HubSpot Inc.",
    "INVH": "Invitation Homes Inc.",
    "IQ": "iQIYI Inc.",
    "KW": "Kennedy-Wilson Holdings Inc.",
    "KBAL": "Kimball International Inc.",
    "KNSA": "Kiniksa Pharmaceuticals Ltd.",
    "KEP": "Korea Electric Power Corporatio",
    "LRCX": "Lam Research Corporation",
    "LORL": "Loral Space and Communications",
    "LUNA": "Luna Innovations Incorporated",
    "MNTX": "Manitex International Inc.",
    "MCHX": "Marchex Inc.",
    "MATW": "Matthews International Corporat",
    "MITK": "Mitek Systems Inc.",
    "MIXT": "MiX Telematics Limited",
    "MPLX": "MPLX LP",
    "NBIX": "Neurocrine Biosciences Inc.",
    "NXTC": "NextCure Inc.",
    "NICE": "NICE Ltd",
    "NSC": "Norfolk Southern Corporation",
    "NTRS": "Northern Trust Corporation",
    "OMER": "Omeros Corporation",
    "OSW": "OneSpaWorld Holdings Limited",
    "PDCO": "Patterson Companies Inc.",
    "PSXP": "Phillips 66 Partners LP",
    "DOC": "Physicians Realty Trust",
    "PFPT": "Proofpoint Inc.",
    "QADB": "QAD Inc.",
    "QLYS": "Qualys Inc.",
    "RDUS": "Radius Health Inc.",
    "RPD": "Rapid7 Inc.",
    "RDVT": "Red Violet Inc.",
    "RDHL": "Redhill Biopharma Ltd.",
    "RPAY": "Repay Holdings Corporation",
    "KRMD": "Repro Med Systems Inc.",
    "SPNS": "Sapiens International Corporati",
    "SCSC": "ScanSource Inc.",
    "SCWX": "SecureWorks Corp.",
    "SRE": "Sempra Energy",
    "SREV": "ServiceSource International In",
    "SLP": "Simulations Plus Inc.",
    "SLM": "SLM Corporation",
    "SGH": "SMART Global Holdings Inc.",
    "SMCI": "Super Micro Computer Inc.",
    "SYKE": "Sykes Enterprises Incorporated",
    "TAL": "TAL Education Group",
    "BX": "The Blackstone Group Inc.",
    "PLCE": "Children's Place Inc. (The)",
    "SHYF": "The Shyft Group Inc.",
    "TSCO": "Tractor Supply Company",
    "WCN": "Waste Connections Inc.",
    "WHR": "Whirlpool Corporation",
    "WIX": "Wix.com Ltd.",
    "WDAY": "Workday Inc.",
    "XNET": "Xunlei Limited",
    "SRCE": "1st Source Corporation",
    "AOS": "A.O. Smith Corporation",
    "ABMD": "ABIOMED Inc.",
    "ASIX": "AdvanSix Inc.",
    "ADVM": "Adverum Biotechnologies Inc.",
    "AGYS": "Agilysys Inc.",
    "AIMT": "Aimmune Therapeutics Inc.",
    "AIRG": "Airgain Inc.",
    "ALG": "Alamo Group Inc.",
    "ALBO": "Albireo Pharma Inc.",
    "ARE": "Alexandria Real Estate Equities",
    "ALL": "Allstate Corporation (The)",
    "AOSL": "Alpha and Omega Semiconductor L",
    "APLT": "Applied Therapeutics Inc.",
    "ARQT": "Arcutis Biotherapeutics Inc.",
    "AROW": "Arrow Financial Corporation",
    "ASB": "Associated Banc-Corp",
    "ASUR": "Asure Software Inc",
    "ATO": "Atmos Energy Corporation",
    "AN": "AutoNation Inc.",
    "AVY": "Avery Dennison Corporation",
    "AVRO": "AVROBIO Inc.",
    "AWRE": "Aware Inc.",
    "BMI": "Badger Meter Inc.",
    "BAX": "Baxter International Inc.",
    "BILL": "Bill.com Holdings Inc.",
    "BEAT": "BioTelemetry Inc.",
    "BAH": "Booz Allen Hamilton Holding Cor",
    "BRC": "Brady Corporation",
    "BRX": "Brixmor Property Group Inc.",
    "BRO": "Brown & Brown Inc.",
    "BC": "Brunswick Corporation",
    "BKE": "Buckle Inc. (The)",
    "BLDR": "Builders FirstSource Inc.",
    "CAI": "CAI International Inc.",
    "CPB": "Campbell Soup Company",
    "CATY": "Cathay General Bancorp",
    "CE": "Celanese Corporation Celanese C",
    "COLB": "Columbia Banking System Inc.",
    "CPRT": "Copart Inc.",
    "COR": "CoreSite Realty Corporation",
    "CTVA": "Corteva Inc.",
    "CRVL": "CorVel Corp.",
    "CZZ": "Cosan Limited",
    "CSGP": "CoStar Group Inc.",
    "CACC": "Credit Acceptance Corporation",
    "CREE": "Cree Inc.",
    "CSGS": "CSG Systems International Inc.",
    "CW": "Curtiss-Wright Corporation",
    "CYBE": "CyberOptics Corporation",
    "CTMX": "CytomX Therapeutics Inc.",
    "DVA": "DaVita Inc.",
    "DGII": "Digi International Inc.",
    "DMRC": "Digimarc Corporation",
    "DOV": "Dover Corporation",
    "DSPG": "DSP Group Inc.",
    "EGBN": "Eagle Bancorp Inc.",
    "EIX": "Edison International",
    "ESI": "Element Solutions Inc.",
    "ECPG": "Encore Capital Group Inc",
    "DAVA": "Endava plc",
    "FFIN": "First Financial Bankshares Inc",
    "FTS": "Fortis Inc.",
    "FEIM": "Frequency Electronics Inc.",
    "FREQ": "Frequency Therapeutics Inc.",
    "FULT": "Fulton Financial Corporation",
    "FUTU": "Futu Holdings Limited",
    "GDDY": "GoDaddy Inc.",
    "GDEN": "Golden Entertainment Inc.",
    "AJX": "Great Ajax Corp.",
    "HTLF": "Heartland Financial USA Inc.",
    "HLF": "Herbalife Nutrition Ltd.",
    "HCCI": "Heritage-Crystal Clean Inc.",
    "HNP": "Huaneng Power Intl",
    "HPP": "Hudson Pacific Properties Inc.",
    "HUM": "Humana Inc.",
    "INFO": "IHS Markit Ltd.",
    "INCY": "Incyte Corporation",
    "IPG": "Interpublic Group of Companies",
    "KALA": "Kala Pharmaceuticals Inc.",
    "K": "Kellogg Company",
    "KEQU": "Kewaunee Scientific Corporation",
    "KLAC": "KLA Corporation",
    "KFY": "Korn Ferry",
    "KRYS": "Krystal Biotech Inc.",
    "LNTH": "Lantheus Holdings Inc.",
    "LDOS": "Leidos Holdings Inc.",
    "MKTX": "MarketAxess Holdings Inc.",
    "MXIM": "Maxim Integrated Products Inc.",
    "MGTX": "MeiraGTx Holdings plc",
    "MIME": "Mimecast Limited",
    "MC": "Moelis & Company",
    "MPWR": "Monolithic Power Systems Inc.",
    "NSTG": "NanoString Technologies Inc.",
    "EDU": "New Oriental Education & Techno",
    "NWSA": "News Corporation",
    "ORLY": "O'Reilly Automotive Inc.",
    "ON": "ON Semiconductor Corporation",
    "KIDS": "OrthoPediatrics Corp.",
    "PLMR": "Palomar Holdings Inc.",
    "PASG": "Passage Bio Inc.",
    "PCTI": "PCTEL Inc.",
    "PLXS": "Plexus Corp.",
    "PRVB": "Provention Bio Inc.",
    "QADA": "QAD Inc.",
    "RMBS": "Rambus Inc.",
    "RF": "Regions Financial Corporation",
    "RCII": "Rent-A-Center Inc.",
    "RGCO": "RGC Resources Inc.",
    "RYTM": "Rhythm Pharmaceuticals Inc.",
    "RCKT": "Rocket Pharmaceuticals Inc.",
    "RUHN": "Ruhnn Holding Limited",
    "BFS": "Saul Centers Inc.",
    "SIGI": "Selective Insurance Group Inc.",
    "SSTK": "Shutterstock Inc.",
    "SWIR": "Sierra Wireless Inc.",
    "SWK": "Stanley Black & Decker Inc.",
    "STOK": "Stoke Therapeutics Inc.",
    "SYNA": "Synaptics Incorporated",
    "SNPS": "Synopsys Inc.",
    "TROW": "T. Rowe Price Group Inc.",
    "TXRH": "Texas Roadhouse Inc.",
    "GBX": "Greenbrier Companies Inc. (The",
    "TSBK": "Timberland Bancorp Inc.",
    "TKR": "Timken Company (The)",
    "TSC": "TriState Capital Holdings Inc.",
    "TTMI": "TTM Technologies Inc.",
    "ULTA": "Ulta Beauty Inc.",
    "URI": "United Rentals Inc.",
    "USM": "United States Cellular Corporat",
    "VREX": "Varex Imaging Corporation",
    "VRNS": "Varonis Systems Inc.",
    "VECO": "Veeco Instruments Inc.",
    "VRTU": "Virtusa Corporation",
    "VYGR": "Voyager Therapeutics Inc.",
    "VMC": "Vulcan Materials Company (Holdi",
    "WAFD": "Washington Federal Inc.",
    "WK": "Workiva Inc.",
    "ZION": "Zions Bancorporation N.A.",
    "QFIN": "360 Finance Inc.",
    "ACIW": "ACI Worldwide Inc.",
    "ADUS": "Addus HomeCare Corporation",
    "AAP": "Advance Auto Parts Inc Advance ",
    "AERI": "Aerie Pharmaceuticals Inc.",
    "AMG": "Affiliated Managers Group Inc.",
    "AGIO": "Agios Pharmaceuticals Inc.",
    "ADC": "Agree Realty Corporation",
    "AKCA": "Akcea Therapeutics Inc.",
    "AKRO": "Akero Therapeutics Inc.",
    "ALC": "Alcon Inc.",
    "ALX": "Alexander's Inc.",
    "ALLK": "Allakos Inc.",
    "ALLE": "Allegion plc",
    "LNT": "Alliant Energy Corporation",
    "APEI": "American Public Education Inc.",
    "AMSWA": "American Software Inc.",
    "CRMT": "America's Car-Mart Inc.",
    "AMSF": "AMERISAFE Inc.",
    "AME": "AMETEK Inc.",
    "ADI": "Analog Devices Inc.",
    "ATEX": "Anterix Inc.",
    "AMEH": "Apollo Medical Holdings Inc.",
    "APRE": "Aprea Therapeutics Inc.",
    "ARDX": "Ardelyx Inc.",
    "AGX": "Argan Inc.",
    "ASGN": "ASGN Incorporated",
    "AC": "Associated Capital Group Inc.",
    "ATNX": "Athenex Inc.",
    "AUB": "Atlantic Union Bankshares Corpo",
    "ATNI": "ATN International Inc.",
    "ATHM": "Autohome Inc.",
    "AZO": "AutoZone Inc.",
    "AVNS": "Avanos Medical Inc.",
    "AVTR": "Avantor Inc.",
    "AXNX": "Axonics Modulation Technologies",
    "BCPC": "Balchem Corporation",
    "BLL": "Ball Corporation",
    "BECN": "Beacon Roofing Supply Inc.",
    "BEAM": "Beam Therapeutics Inc.",
    "BDC": "Belden Inc",
    "BHE": "Benchmark Electronics Inc.",
    "BTAI": "BioXcel Therapeutics Inc.",
    "BCOR": "Blucora Inc.",
    "BOKF": "BOK Financial Corporation",
    "BWA": "BorgWarner Inc.",
    "BOMN": "Boston Omaha Corporation",
    "BDGE": "Bridge Bancorp Inc.",
    "BCOV": "Brightcove Inc.",
    "BRKS": "Brooks Automation Inc.",
    "BURL": "Burlington Stores Inc.",
    "CABO": "Cable One Inc.",
    "CCMP": "Cabot Microelectronics Corporat",
    "CATM": "Cardtronics plc",
    "CDNA": "CareDx Inc.",
    "CSL": "Carlisle Companies Incorporated",
    "CSTL": "Castle Biosciences Inc.",
    "CNTG": "Centogene N.V.",
    "CERN": "Cerner Corporation",
    "CEVA": "CEVA Inc.",
    "CHUY": "Chuy's Holdings Inc.",
    "CTAS": "Cintas Corporation",
    "CHCO": "City Holding Company",
    "CMS": "CMS Energy Corporation",
    "COHR": "Coherent Inc.",
    "CFX": "Colfax Corporation",
    "CBU": "Community Bank System Inc.",
    "CPSI": "Computer Programs and Systems ",
    "CTG": "Computer Task Group Incorporat",
    "CRNX": "Crinetics Pharmaceuticals Inc.",
    "CTS": "CTS Corporation",
    "CVBF": "CVB Financial Corporation",
    "DHI": "D.R. Horton Inc.",
    "DJCO": "Daily Journal Corp. (S.C.)",
    "DMTK": "DermTech Inc.",
    "DIOD": "Diodes Incorporated",
    "DTE": "DTE Energy Company",
    "EGRX": "Eagle Pharmaceuticals Inc.",
    "LOCO": "El Pollo Loco Holdings Inc.",
    "ENTA": "Enanta Pharmaceuticals Inc.",
    "ENV": "Envestnet Inc",
    "EVA": "Enviva Partners LP",
    "PLUS": "ePlus inc.",
    "EFX": "Equifax Inc.",
    "ERIE": "Erie Indemnity Company",
    "ESTA": "Establishment Labs Holdings Inc",
    "EXPI": "eXp World Holdings Inc.",
    "EXPO": "Exponent Inc.",
    "FFIV": "F5 Networks Inc.",
    "FGEN": "FibroGen Inc",
    "FITB": "Fifth Third Bancorp",
    "FCNCA": "First Citizens BancShares Inc.",
    "FHB": "First Hawaiian Inc.",
    "FORM": "FormFactor Inc.",
    "FORR": "Forrester Research Inc.",
    "FTDR": "frontdoor inc.",
    "GATX": "GATX Corporation",
    "GCP": "GCP Applied Technologies Inc.",
    "GFN": "General Finance Corporation",
    "GL": "Globe Life Inc.",
    "GSHD": "Goosehead Insurance Inc.",
    "GHG": "GreenTree Hospitality Group Ltd",
    "GDYN": "Grid Dynamics Holdings Inc.",
    "GSIT": "GSI Technology Inc.",
    "HIG": "Hartford Financial Services Gro",
    "HSTM": "HealthStream Inc.",
    "HSII": "Heidrick & Struggles Internatio",
    "HMSY": "HMS Holdings Corp",
    "HUBB": "Hubbell Inc",
    "IMAB": "I-MAB",
    "ICHR": "Ichor Holdings",
    "IBKR": "Interactive Brokers Group Inc.",
    "IFF": "Internationa Flavors & Fragranc",
    "ISBC": "Investors Bancorp Inc.",
    "IPGP": "IPG Photonics Corporation",
    "ITRI": "Itron Inc.",
    "JBHT": "J.B. Hunt Transport Services I",
    "MAYS": "J. W. Mays Inc.",
    "JBL": "Jabil Inc.",
    "J": "Jacobs Engineering Group Inc.",
    "JRVR": "James River Group Holdings Ltd",
    "JBT": "John Bean Technologies Corporat",
    "KAI": "Kadant Inc",
    "KE": "Kimball Electronics Inc.",
    "KURA": "Kura Oncology Inc.",
    "LKFN": "Lakeland Financial Corporation",
    "TREE": "LendingTree Inc.",
    "LNC": "Lincoln National Corporation",
    "LFUS": "Littelfuse Inc.",
    "RAMP": "LiveRamp Holdings Inc.",
    "MANH": "Manhattan Associates Inc.",
    "MAN": "ManpowerGroup",
    "MLM": "Martin Marietta Materials Inc.",
    "MAS": "Masco Corporation",
    "MXL": "MaxLinear Inc.",
    "MGEE": "MGE Energy Inc.",
    "MTEM": "Molecular Templates Inc.",
    "MORF": "Morphic Holding Inc.",
    "COOP": "Mr. Cooper Group Inc.",
    "MUSA": "Murphy USA Inc.",
    "NSSC": "NAPCO Security Technologies In",
    "NTCT": "NetScout Systems Inc.",
    "NEWR": "New Relic Inc.",
    "NWS": "News Corporation",
    "NGM": "NGM Biopharmaceuticals Inc.",
    "NLSN": "Nielsen N.V.",
    "NWBI": "Northwest Bancshares Inc.",
    "NUAN": "Nuance Communications Inc.",
    "NUVA": "NuVasive Inc.",
    "ODT": "Odonate Therapeutics Inc.",
    "ODFL": "Old Dominion Freight Line Inc.",
    "ONB": "Old National Bancorp",
    "OLLI": "Ollie's Bargain Outlet Holdings",
    "OFIX": "Orthofix Medical Inc.",
    "OSIS": "OSI Systems Inc.",
    "OI": "O-I Glass Inc.",
    "OYST": "Oyster Point Pharma Inc.",
    "PCAR": "PACCAR Inc.",
    "PKE": "Park Aerospace Corp.",
    "PTNR": "Partner Communications Company ",
    "PCTY": "Paylocity Holding Corporation",
    "PDFS": "PDF Solutions Inc.",
    "PEGA": "Pegasystems Inc.",
    "PRGO": "Perrigo Company plc",
    "PPD": "PPD Inc.",
    "PAHC": "Phibro Animal Health Corporatio",
    "PNFP": "Pinnacle Financial Partners In",
    "POR": "Portland General Electric Co",
    "POWL": "Powell Industries Inc.",
    "POWI": "Power Integrations Inc.",
    "PRVL": "Prevail Therapeutics Inc.",
    "PGR": "Progressive Corporation (The)",
    "PRO": "PROS Holdings Inc.",
    "PRTA": "Prothena Corporation plc",
    "PWR": "Quanta Services Inc.",
    "RAPT": "RAPT Therapeutics Inc.",
    "RP": "RealPage Inc.",
    "REPL": "Replimune Group Inc.",
    "RVNC": "Revance Therapeutics Inc.",
    "RXN": "Rexnord Corporation",
    "RMNI": "Rimini Street Inc.",
    "RMR": "The RMR Group Inc.",
    "ROK": "Rockwell Automation Inc.",
    "ROP": "Roper Technologies Inc.",
    "RUBY": "Rubius Therapeutics Inc.",
    "SAFT": "Safety Insurance Group Inc.",
    "SAFM": "Sanderson Farms Inc.",
    "SASR": "Sandy Spring Bancorp Inc.",
    "SCHN": "Schnitzer Steel Industries Inc",
    "SRRK": "Scholar Rock Holding Corporatio",
    "SMTC": "Semtech Corporation",
    "SHW": "Sherwin-Williams Company (The)",
    "SCVL": "Shoe Carnival Inc.",
    "SIBN": "SI-BONE Inc.",
    "SIGA": "SIGA Technologies Inc.",
    "SIGM": "SIFCO Industries Inc. Common S",
    "SILC": "Silicom Ltd",
    "SLAB": "Silicon Laboratories Inc.",
    "SINA": "Sina Corporation",
    "SITE": "SiteOne Landscape Supply Inc.",
    "SITM": "SiTime Corporation",
    "SOHU": "Sohu.com Limited",
    "SBSI": "Southside Bancshares Inc.",
    "SWX": "Southwest Gas Holdings Inc.",
    "SPSC": "SPS Commerce Inc.",
    "SPXC": "SPX Corporation",
    "FLOW": "SPX FLOW Inc.",
    "SSNC": "SS&C Technologies Holdings Inc",
    "SXI": "Standex International Corporati",
    "SRCL": "Stericycle Inc.",
    "STRA": "Strategic Education Inc.",
    "SUI": "Sun Communities Inc.",
    "SGRY": "Surgery Partners Inc.",
    "SRDX": "Surmodics Inc.",
    "SNDX": "Syndax Pharmaceuticals Inc.",
    "SNX": "Synnex Corporation",
    "TARO": "Taro Pharmaceutical Industries ",
    "TNC": "Tennant Company",
    "TTEK": "Tetra Tech Inc.",
    "TCBI": "Texas Capital Bancshares Inc.",
    "HSY": "The Hershey Company",
    "BLD": "TopBuild Corp.",
    "TRNS": "Transcat Inc.",
    "TBIO": "Translate Bio Inc.",
    "TRU": "TransUnion",
    "TCDA": "Tricida Inc.",
    "TRMB": "Trimble Inc.",
    "UMBF": "UMB Financial Corporation",
    "UBSI": "United Bankshares Inc.",
    "UIHC": "United Insurance Holdings Corp.",
    "UTL": "UNITIL Corporation",
    "UHS": "Universal Health Services Inc.",
    "VCYT": "Veracyte Inc.",
    "VRSN": "VeriSign Inc.",
    "VSEC": "VSE Corporation",
    "WAT": "Waters Corporation",
    "WLDN": "Willdan Group Inc.",
    "WING": "Wingstop Inc.",
    "WTFC": "Wintrust Financial Corporation",
    "ZBRA": "Zebra Technologies Corporation",
    "ZBH": "Zimmer Biomet Holdings Inc.",
    "ZUMZ": "Zumiez Inc."]


var SampledataEntry = ["SNAP": [CompPortfolioOutput(lastRefreshed: "2020-08-27", compName: "Snap Inc.", compSymbol: "SNAP", purchaseDate: "2017-07-01", purchasePrice: 17.59, purchaseAmount: 15.0, totalInvestment: 263.85, totalCurrentValue: 326.09999999999997, gainHistory: [62.25000000000001, 56.55, 52.949999999999996, 49.199999999999996, 60.15, 63.6, 64.95, 62.699999999999996, 63.0, 61.49999999999999, 64.64999999999999, 64.05, 60.15, 66.44999999999999, 59.85, 56.4, 61.650000000000006, 62.55, 54.449999999999996, 72.45, 72.30000000000001, 79.64999999999999, 75.0, 78.75, 68.39999999999999, 65.7, 84.15, 107.25, 115.19999999999999, 104.25, 94.64999999999999, 104.25, 92.25, 100.19999999999999, 119.10000000000001, 125.25, 132.3, 108.3, 87.45, 84.45, 91.95, 88.5, 82.5, 82.2, 103.35, 90.6, 91.2, 84.15, 76.05000000000001, 66.0, 63.45, 49.65, 47.400000000000006, 38.849999999999994, 31.8, 54.15, 52.5, 45.9, 41.1, 25.049999999999997, 32.1, 32.400000000000006, 29.4, 20.25, 9.9, -8.85, -2.6999999999999997, 1.2, -0.6, 9.6, -1.65, -1.5, -7.35, -9.9, -12.299999999999999, -3.15, 7.5, 9.6, 8.4, -3.9000000000000004, -1.2, -7.35, -12.0, 0.3, 3.5999999999999996, -17.7, -10.200000000000001, -23.85, -22.95, -8.7, -77.25, -70.05, -69.15, -68.55000000000001, -60.15, -57.15, -60.75, -59.7, -65.55, -82.35000000000001, -81.44999999999999, -97.95, -94.80000000000001, -95.7, -85.5, -86.10000000000001, -81.15, -84.6, -95.4, -98.85, -104.10000000000001, -112.5, -121.79999999999998, -138.3, -130.2, -127.94999999999999, -93.60000000000001, -107.55, -101.7, -84.0, -92.1, -68.85, -56.1, -59.4, -60.6, -48.0, -51.3, -43.95, -28.799999999999997, -25.5, -21.599999999999998, -13.35, -10.05, -5.8500000000000005, -6.3, -0.44999999999999996, 0.0, -2.85, 0.3, 0.15, -6.9, -8.85, -21.0, 20.849999999999998, 9.6, 11.850000000000001, 19.35, 23.25, 21.0, 15.450000000000001, 21.9, 24.9, 22.65, 21.15, 22.8, 9.9, 9.0, 6.0, 6.1499999999999995, -2.6999999999999997, -3.45, -13.8, -8.4, -12.15, -12.6, -12.15, -18.9, -25.5, -23.400000000000002, -24.3, -29.7, -31.5, -30.6, -31.95, -37.2, -37.35, -37.2, -37.5, -47.1, -50.4, -52.5, -50.4, -42.75, -43.650000000000006, -38.849999999999994, -40.05, -44.85, -35.099999999999994, -33.6, -31.95, -31.349999999999998, -34.95, -37.65, -34.199999999999996, -36.45, -43.5, -54.75, -48.300000000000004, -46.800000000000004, -48.15, -48.0, -51.0, -51.45, -47.7, -41.4, -33.6, -36.150000000000006, -37.949999999999996, -40.95, -44.25, -43.650000000000006, -54.449999999999996, -61.050000000000004, -66.15, -53.849999999999994, -45.15, -61.050000000000004, -57.15, -58.8, -52.5, -57.45, -51.45, -52.65, -50.699999999999996, -51.6, -46.800000000000004, -46.05, -49.35, -41.85, -31.049999999999997, -26.85, -23.55, -8.85, -7.199999999999999, -8.25, -7.05, -8.25, -10.649999999999999, -10.35, -11.4, -27.450000000000003, -23.85, -27.3, -34.199999999999996, -38.55, -34.199999999999996, -14.549999999999999, -25.8, -26.85, -24.9, -26.4, -27.150000000000002, -30.6, -31.200000000000003, -22.2, -30.6, -22.65, -21.75, -22.65, -21.45, -24.150000000000002, -24.0, -18.45, -8.85, -11.700000000000001, -9.15, -12.45, -25.2, -19.5, -16.95, -8.4, -13.65, -11.850000000000001, -9.9, -1.3499999999999999, 4.5, 1.5, 0.3, -41.4, -51.6, -53.55, -45.6, -39.900000000000006, -38.849999999999994, -31.349999999999998, -29.7, -30.3, -34.95, -35.099999999999994, -36.75, -35.4, -42.45, -52.35, -48.6, -49.35, -45.15, -43.199999999999996, -45.9, -42.45, -45.449999999999996, -41.25, -43.8, -40.95, -60.6, -54.449999999999996, -52.2, -57.599999999999994, -60.75, -57.3, -55.800000000000004, -56.55, -69.75, -69.6, -88.5, -85.5, -84.0, -88.65, -90.3, -90.45, -97.05, -94.2, -90.75, -96.0, -91.5, -92.55, -103.94999999999999, -106.5, -112.2, -106.5, -99.15, -101.55, -96.3, -87.30000000000001, -86.85, -95.25, -95.85, -96.75, -95.55, -100.19999999999999, -102.0, -94.95, -84.0, -90.89999999999999, -88.8, -87.6, -88.5, -86.10000000000001, -84.3, -85.35000000000001, -83.55000000000001, -78.60000000000001, -79.80000000000001, -86.25, -94.64999999999999, -96.44999999999999, -95.55, -93.45, -98.55000000000001, -102.0, -104.25, -102.45, -103.05, -102.9, -98.7, -99.75, -104.4, -99.75, -96.44999999999999, -94.64999999999999, -113.1, -115.65, -114.45, -121.64999999999999, -121.5, -115.8, -112.64999999999999, -115.05, -116.85, -116.85, -116.7, -112.64999999999999, -112.05, -118.2, -122.99999999999999, -125.25, -124.65, -127.05000000000001, -126.0, -127.8, -131.85, -129.0, -127.35000000000001, -135.29999999999998, -135.0, -158.25, -159.9, -160.2, -163.65, -165.29999999999998, -167.4, -168.75, -167.85, -171.3, -174.0, -174.9, -171.15, -177.75, -179.25, -165.75, -169.2, -169.65, -170.54999999999998, -169.65, -167.85, -170.70000000000002, -174.60000000000002, -178.65, -177.0, -181.2, -178.20000000000002, -183.6, -182.55, -186.15, -189.0, -187.79999999999998, -182.7, -179.1, -180.15, -175.05, -175.95000000000002, -175.2, -177.6, -178.8, -176.85, -174.29999999999998, -170.70000000000002, -168.45000000000002, -166.2, -167.85, -166.2, -167.85, -166.35, -170.85000000000002, -168.6, -172.5, -173.1, -166.5, -161.54999999999998, -166.64999999999998, -163.20000000000002, -164.1, -162.0, -158.55, -155.85000000000002, -157.5, -160.35, -161.54999999999998, -155.85000000000002, -164.70000000000002, -167.4, -174.0, -169.65, -159.0, -165.0, -161.54999999999998, -161.25, -161.7, -161.7, -157.95, -155.1, -152.85, -156.15, -161.7, -165.0, -158.85, -151.64999999999998, -147.3, -146.85, -140.39999999999998, -141.15, -138.45000000000002, -136.64999999999998, -131.85, -129.0, -128.1, -129.60000000000002, -126.74999999999999, -125.70000000000002, -126.44999999999999, -126.9, -126.15, -124.50000000000001, -123.60000000000001, -125.85000000000001, -115.5, -117.75, -114.9, -116.85, -112.2, -105.0, -100.35000000000001, -97.64999999999999, -96.3, -94.5, -86.7, -89.4, -92.85000000000001, -92.25, -92.25, -87.9, -85.5, -81.3, -81.15, -78.75, -75.3, -79.2, -79.2, -80.4, -67.05, -68.1, -72.9, -73.35, -78.15, -76.35, -79.80000000000001, -71.39999999999999, -63.3, -63.0, -66.75, -63.0, -64.80000000000001, -62.400000000000006, -63.6, -62.55, -67.8, -63.45, -59.1, -62.85000000000001, -64.2, -59.1, -60.89999999999999, -65.7, -66.60000000000001, -66.60000000000001, -67.5, -62.85000000000001, -71.55, -68.85, -67.35000000000001, -65.85, -65.25, -71.85, -64.2, -53.1, -53.55, -55.800000000000004, -59.550000000000004, -62.55, -66.3, -67.64999999999999, -72.9, -66.9, -69.9, -79.05, -89.4, -93.0, -99.3, -105.6, -103.2, -104.85000000000001, -104.10000000000001, -102.75, -103.2, -105.14999999999999, -105.3, -105.14999999999999, -104.10000000000001, -99.15, -98.25, -98.7, -98.7, -99.3, -102.75, -102.0, -99.3, -98.39999999999999, -51.9, -48.9, -50.4, -43.35, -45.75, -29.4, -30.749999999999996, -35.85, -41.25, -44.1, -40.65, -45.15, -40.65, -40.05, -41.85, -46.65, -51.6, -50.099999999999994, -48.0, -45.0, -52.65, -46.949999999999996, -25.8, -24.599999999999998, -20.849999999999998, -20.1, -18.45, -15.3, -15.3, -23.85, -17.549999999999997, -8.7, -5.8500000000000005, 3.9000000000000004, -1.2, 7.800000000000001, 4.35, 0.8999999999999999, 6.45, 6.3, 9.9, 6.3, -5.7, -4.050000000000001, -19.05, -7.5, -2.1, -1.2, 15.75, 20.1, 42.45, 32.400000000000006, 29.55, 14.85, 15.600000000000001, 18.15, 27.0, 47.400000000000006, -52.949999999999996, -56.1, -58.199999999999996, -55.05, -61.050000000000004, -64.95, -61.800000000000004, -60.45, -58.199999999999996, -47.25, -50.099999999999994, -51.3, -53.25, -53.7, -61.050000000000004, -61.349999999999994, -52.2, -44.85, -44.1, -52.35, -52.949999999999996, -46.349999999999994, -45.0, -34.199999999999996, -39.6, -44.7, -41.1, -41.25, -38.7, -36.6, -33.300000000000004, -31.349999999999998, -27.3, -22.35, -27.6, -23.25, -24.45, -24.9, -20.55, -37.8, -43.35, -44.85, -39.75, -60.3, -55.800000000000004, -57.15, -58.35, -59.7, -67.95, -69.3, -74.55, -78.75, -77.69999999999999, -69.0, -75.45, -76.95, -75.3, -77.85000000000001, -72.45, -78.15, -70.19999999999999, -37.050000000000004, -41.4, -34.8, -45.6, -46.2, -33.75, -28.65, -32.25, -48.0, -51.45, -45.0, -39.300000000000004, -30.449999999999996, -35.099999999999994, -27.6, -22.5, -22.8, -16.35, -15.600000000000001, -24.150000000000002, -48.75, -43.199999999999996, -42.0, -46.65, -45.9, -44.25, -40.65, -45.75, -47.1, -52.050000000000004, -55.2, -65.55, -58.35, -57.3, -51.45, -43.050000000000004, -40.05, -35.099999999999994, -40.2, -38.4, -36.9, -34.8, -33.75, -36.6, -46.349999999999994, -46.5, -49.8, -46.2, -39.449999999999996, -39.0, -36.0, -42.15, -45.9, -37.5, -45.9, -60.15, -53.7, -63.6, -67.05, -72.75, -74.85000000000001, -86.39999999999999, -57.3, -60.45, -68.55000000000001, -63.0, -61.050000000000004, -69.9, -74.10000000000001, -67.35000000000001, -58.8, -56.699999999999996, -53.849999999999994, -62.85000000000001, -55.5, -52.65, -46.65, -40.5, -39.300000000000004, -42.9, -36.9, -34.8, -28.5, -35.25, -31.8, -9.0, -6.1499999999999995, -4.2, -4.050000000000001, 0.0], currentGain: 23.59, priceHistory: [21.74, 21.36, 21.12, 20.87, 21.6, 21.83, 21.92, 21.77, 21.79, 21.69, 21.9, 21.86, 21.6, 22.02, 21.58, 21.35, 21.7, 21.76, 21.22, 22.42, 22.41, 22.9, 22.59, 22.84, 22.15, 21.97, 23.2, 24.74, 25.27, 24.54, 23.9, 24.54, 23.74, 24.27, 25.53, 25.94, 26.41, 24.81, 23.42, 23.22, 23.72, 23.49, 23.09, 23.07, 24.48, 23.63, 23.67, 23.2, 22.66, 21.99, 21.82, 20.9, 20.75, 20.18, 19.71, 21.2, 21.09, 20.65, 20.33, 19.26, 19.73, 19.75, 19.55, 18.94, 18.25, 17.0, 17.41, 17.67, 17.55, 18.23, 17.48, 17.49, 17.1, 16.93, 16.77, 17.38, 18.09, 18.23, 18.15, 17.33, 17.51, 17.1, 16.79, 17.61, 17.83, 16.41, 16.91, 16.0, 16.06, 17.01, 12.44, 12.92, 12.98, 13.02, 13.58, 13.78, 13.54, 13.61, 13.22, 12.1, 12.16, 11.06, 11.27, 11.21, 11.89, 11.85, 12.18, 11.95, 11.23, 11.0, 10.65, 10.09, 9.47, 8.37, 8.91, 9.06, 11.35, 10.42, 10.81, 11.99, 11.45, 13.0, 13.85, 13.63, 13.55, 14.39, 14.17, 14.66, 15.67, 15.89, 16.15, 16.7, 16.92, 17.2, 17.17, 17.56, 17.59, 17.4, 17.61, 17.6, 17.13, 17.0, 16.19, 18.98, 18.23, 18.38, 18.88, 19.14, 18.99, 18.62, 19.05, 19.25, 19.1, 19.0, 19.11, 18.25, 18.19, 17.99, 18.0, 17.41, 17.36, 16.67, 17.03, 16.78, 16.75, 16.78, 16.33, 15.89, 16.03, 15.97, 15.61, 15.49, 15.55, 15.46, 15.11, 15.1, 15.11, 15.09, 14.45, 14.23, 14.09, 14.23, 14.74, 14.68, 15.0, 14.92, 14.6, 15.25, 15.35, 15.46, 15.5, 15.26, 15.08, 15.31, 15.16, 14.69, 13.94, 14.37, 14.47, 14.38, 14.39, 14.19, 14.16, 14.41, 14.83, 15.35, 15.18, 15.06, 14.86, 14.64, 14.68, 13.96, 13.52, 13.18, 14.0, 14.58, 13.52, 13.78, 13.67, 14.09, 13.76, 14.16, 14.08, 14.21, 14.15, 14.47, 14.52, 14.3, 14.8, 15.52, 15.8, 16.02, 17.0, 17.11, 17.04, 17.12, 17.04, 16.88, 16.9, 16.83, 15.76, 16.0, 15.77, 15.31, 15.02, 15.31, 16.62, 15.87, 15.8, 15.93, 15.83, 15.78, 15.55, 15.51, 16.11, 15.55, 16.08, 16.14, 16.08, 16.16, 15.98, 15.99, 16.36, 17.0, 16.81, 16.98, 16.76, 15.91, 16.29, 16.46, 17.03, 16.68, 16.8, 16.93, 17.5, 17.89, 17.69, 17.61, 14.83, 14.15, 14.02, 14.55, 14.93, 15.0, 15.5, 15.61, 15.57, 15.26, 15.25, 15.14, 15.23, 14.76, 14.1, 14.35, 14.3, 14.58, 14.71, 14.53, 14.76, 14.56, 14.84, 14.67, 14.86, 13.55, 13.96, 14.11, 13.75, 13.54, 13.77, 13.87, 13.82, 12.94, 12.95, 11.69, 11.89, 11.99, 11.68, 11.57, 11.56, 11.12, 11.31, 11.54, 11.19, 11.49, 11.42, 10.66, 10.49, 10.11, 10.49, 10.98, 10.82, 11.17, 11.77, 11.8, 11.24, 11.2, 11.14, 11.22, 10.91, 10.79, 11.26, 11.99, 11.53, 11.67, 11.75, 11.69, 11.85, 11.97, 11.9, 12.02, 12.35, 12.27, 11.84, 11.28, 11.16, 11.22, 11.36, 11.02, 10.79, 10.64, 10.76, 10.72, 10.73, 11.01, 10.94, 10.63, 10.94, 11.16, 11.28, 10.05, 9.88, 9.96, 9.48, 9.49, 9.87, 10.08, 9.92, 9.8, 9.8, 9.81, 10.08, 10.12, 9.71, 9.39, 9.24, 9.28, 9.12, 9.19, 9.07, 8.8, 8.99, 9.1, 8.57, 8.59, 7.04, 6.93, 6.91, 6.68, 6.57, 6.43, 6.34, 6.4, 6.17, 5.99, 5.93, 6.18, 5.74, 5.64, 6.54, 6.31, 6.28, 6.22, 6.28, 6.4, 6.21, 5.95, 5.68, 5.79, 5.51, 5.71, 5.35, 5.42, 5.18, 4.99, 5.07, 5.41, 5.65, 5.58, 5.92, 5.86, 5.91, 5.75, 5.67, 5.8, 5.97, 6.21, 6.36, 6.51, 6.4, 6.51, 6.4, 6.5, 6.2, 6.35, 6.09, 6.05, 6.49, 6.82, 6.48, 6.71, 6.65, 6.79, 7.02, 7.2, 7.09, 6.9, 6.82, 7.2, 6.61, 6.43, 5.99, 6.28, 6.99, 6.59, 6.82, 6.84, 6.81, 6.81, 7.06, 7.25, 7.4, 7.18, 6.81, 6.59, 7.0, 7.48, 7.77, 7.8, 8.23, 8.18, 8.36, 8.48, 8.8, 8.99, 9.05, 8.95, 9.14, 9.21, 9.16, 9.13, 9.18, 9.29, 9.35, 9.2, 9.89, 9.74, 9.93, 9.8, 10.11, 10.59, 10.9, 11.08, 11.17, 11.29, 11.81, 11.63, 11.4, 11.44, 11.44, 11.73, 11.89, 12.17, 12.18, 12.34, 12.57, 12.31, 12.31, 12.23, 13.12, 13.05, 12.73, 12.7, 12.38, 12.5, 12.27, 12.83, 13.37, 13.39, 13.14, 13.39, 13.27, 13.43, 13.35, 13.42, 13.07, 13.36, 13.65, 13.4, 13.31, 13.65, 13.53, 13.21, 13.15, 13.15, 13.09, 13.4, 12.82, 13.0, 13.1, 13.2, 13.24, 12.8, 13.31, 14.05, 14.02, 13.87, 13.62, 13.42, 13.17, 13.08, 12.73, 13.13, 12.93, 12.32, 11.63, 11.39, 10.97, 10.55, 10.71, 10.6, 10.65, 10.74, 10.71, 10.58, 10.57, 10.58, 10.65, 10.98, 11.04, 11.01, 11.01, 10.97, 10.74, 10.79, 10.97, 11.03, 14.13, 14.33, 14.23, 14.7, 14.54, 15.63, 15.54, 15.2, 14.84, 14.65, 14.88, 14.58, 14.88, 14.92, 14.8, 14.48, 14.15, 14.25, 14.39, 14.59, 14.08, 14.46, 15.87, 15.95, 16.2, 16.25, 16.36, 16.57, 16.57, 16.0, 16.42, 17.01, 17.2, 17.85, 17.51, 18.11, 17.88, 17.65, 18.02, 18.01, 18.25, 18.01, 17.21, 17.32, 16.32, 17.09, 17.45, 17.51, 18.64, 18.93, 20.42, 19.75, 19.56, 18.58, 18.63, 18.8, 19.39, 20.75, 14.06, 13.85, 13.71, 13.92, 13.52, 13.26, 13.47, 13.56, 13.71, 14.44, 14.25, 14.17, 14.04, 14.01, 13.52, 13.5, 14.11, 14.6, 14.65, 14.1, 14.06, 14.5, 14.59, 15.31, 14.95, 14.61, 14.85, 14.84, 15.01, 15.15, 15.37, 15.5, 15.77, 16.1, 15.75, 16.04, 15.96, 15.93, 16.22, 15.07, 14.7, 14.6, 14.94, 13.57, 13.87, 13.78, 13.7, 13.61, 13.06, 12.97, 12.62, 12.34, 12.41, 12.99, 12.56, 12.46, 12.57, 12.4, 12.76, 12.38, 12.91, 15.12, 14.83, 15.27, 14.55, 14.51, 15.34, 15.68, 15.44, 14.39, 14.16, 14.59, 14.97, 15.56, 15.25, 15.75, 16.09, 16.07, 16.5, 16.55, 15.98, 14.34, 14.71, 14.79, 14.48, 14.53, 14.64, 14.88, 14.54, 14.45, 14.12, 13.91, 13.22, 13.7, 13.77, 14.16, 14.72, 14.92, 15.25, 14.91, 15.03, 15.13, 15.27, 15.34, 15.15, 14.5, 14.49, 14.27, 14.51, 14.96, 14.99, 15.19, 14.78, 14.53, 15.09, 14.53, 13.58, 14.01, 13.35, 13.12, 12.74, 12.6, 11.83, 13.77, 13.56, 13.02, 13.39, 13.52, 12.93, 12.65, 13.1, 13.67, 13.81, 14.0, 13.4, 13.89, 14.08, 14.48, 14.89, 14.97, 14.73, 15.13, 15.27, 15.69, 15.24, 15.47, 16.99, 17.18, 17.31, 17.32, 17.59], open: "21.5000", close: "21.7400", high: "22.1995", low: "20.8700", volume: "23754063", priceChange1D: 1.78, priceChange5D: -0.41, priceChange1M: -3.76, priceChange1Y: 29.33, volumeChange1D: 84.22, volumeChange5D: 173.26, volumeChange1M: 56.17, volumeChange1Y: 10.44)]]
