//
//  DataBank.swift
//  My Daily Portfolio Update
//
//  Created by Khashayar Abri on 04.08.20.
//  Copyright © 2020 Khashayar Abri. All rights reserved.
//

import Foundation

// MARK: -- For Name Loading
let myDic_Symb2Name: [String:String] =
    ["AMZN": "Amazon.com Inc.",
    "BA": "Boeing Company",
    "TSLA": "Tesla Inc.",
    "TLRY": "Tilray Inc.",
    "AAPL": "Apple Inc.",
    "NIO": "NIO Inc.",
    "AAL": "American Airlines Group Inc.",
    "DAL": "Delta Air Lines Inc.",
    "MSFT": "Microsoft Corporation",
    "KO": "Coca-Cola Company",
    "DIS": "Walt Disney Company",
    "GOOGL": "Alphabet Inc.",
    "BYND": "Beyond Meat Inc.",
    "FB": "Facebook Inc.",
    "MCD": "McDonald's Corporation",
    "NFLX": "Netflix Inc.",
    "SDC": "SmileDirectClub Inc.",
    "SNE": "Sony Corporation",
    "AMD": "Advanced Micro Devices Inc.",
    "NVDA": "NVIDIA Corporation",
    "UBER": "Uber Technologies Inc.",
    "UAA": "Under Armour Inc.",
    "BABA": "Alibaba Group Holding Limited",
    "T": "AT&T Inc.",
    "IVR": "INVESCO MORTGAGE CAPITAL INC",
    "RCL": "Royal Caribbean Cruises Ltd.",
    "WORK": "Slack Technologies Inc.",
    "SPCE": "Virgin Galactic Holdings Inc.",
    "CPE": "Callon Petroleum Company",
    "ZM": "Zoom Video Communications Inc.",
    "NKE": "Nike Inc.",
    "OXY": "Occidental Petroleum Corporatio",
    "V": "Visa Inc.",
    "APHA": "Aphria Inc.",
    "SNAP": "Snap Inc.",
    "BAC": "Bank of America Corporation",
    "CGC": "Canopy Growth Corporation",
    "JNJ": "Johnson & Johnson",
    "PYPL": "PayPal Holdings Inc.",
    "KOS": "Kosmos Energy Ltd.",
    "MA": "Mastercard Incorporated",
    "SBUX": "Starbucks Corporation",
    "VFF": "Village Farms International In",
    "GE": "General Electric Company",
    "PTON": "Peloton Interactive Inc.",
    "LUV": "Southwest Airlines Company",
    "IBM": "International Business Machines",
    "O": "Realty Income Corporation",
    "SQ": "Square Inc.",
    "PFE": "Pfizer Inc.",
    "TWTR": "Twitter Inc.",
    "ADBE": "Adobe Inc.",
    "CRON": "Cronos Group Inc. Common Share",
    "GILD": "Gilead Sciences Inc.",
    "HAL": "Halliburton Company",
    "GRUB": "GrubHub Inc.",
    "MRO": "Marathon Oil Corporation",
    "RIG": "Transocean Ltd (Switzerland)",
    "WMT": "Walmart Inc.",
    "SHOP": "Shopify Inc.",
    "SAVE": "Spirit Airlines Inc.",
    "AXP": "American Express Company",
    "INTC": "Intel Corporation",
    "QCOM": "QUALCOMM Incorporated",
    "NOK": "Nokia Corporation Sponsored",
    "PEP": "Pepsico Inc.",
    "ABBV": "AbbVie Inc.",
    "ATVI": "Activision Blizzard Inc",
    "EA": "Electronic Arts Inc.",
    "MDT": "Medtronic plc.",
    "GOOG": "Alphabet Inc.",
    "MO": "Altria Group Inc.",
    "TLRD": "Tailored Brands Inc.",
    "BMO": "Bank Of Montreal",
    "PK": "Park Hotels & Resorts Inc.",
    "CAR": "Avis Budget Group Inc.",
    "GWPH": "GW Pharmaceuticals Plc",
    "JD": "JD.com Inc.",
    "LTRPA": "Liberty TripAdvisor Holdings I",
    "MAC": "Macerich Company",
    "ZNGA": "Zynga Inc.",
    "GM": "General Motors Company",
    "MAR": "Marriott International",
    "STOR": "STORE Capital Corporation",
    "APA": "Apache Corporation",
    "CRBP": "Corbus Pharmaceuticals Holdings",
    "SPOT": "Spotify Technology S.A.",
    "CRWD": "CrowdStrike Holdings Inc.",
    "COTY": "Coty Inc.",
    "NAT": "Nordic American Tankers Limited",
    "PINS": "Pinterest Inc.",
    "COST": "Costco Wholesale Corporation",
    "TSM": "Taiwan Semiconductor Manufactur",
    "PRGS": "Progress Software Corporation",
    "AGNC": "AGNC Investment Corp.",
    "LAKE": "Lakeland Industries Inc.",
    "TSN": "Tyson Foods Inc.",
    "EBAY": "eBay Inc.",
    "OKTA": "Okta Inc.",
    "SYY": "Sysco Corporation",
    "ABT": "Abbott Laboratories",
    "GS": "Goldman Sachs Group Inc.",
    "LYFT": "Lyft Inc.",
    "WBA": "Walgreens Boots Alliance Inc.",
    "NET": "Cloudflare Inc.",
    "ROKU": "Roku Inc.",
    "HPE": "Hewlett Packard Enterprise Comp",
    "DXCM": "DexCom Inc.",
    "LVGO": "Livongo Health Inc.",
    "BCRX": "BioCryst Pharmaceuticals Inc.",
    "TDOC": "Teladoc Health Inc.",
    "BKNG": "Booking Holdings Inc. Common St",
    "EB": "Eventbrite Inc.",
    "GCI": "Gannett Co. Inc.",
    "RVLV": "Revolve Group Inc.",
    "KHC": "The Kraft Heinz Company",
    "ORCL": "Oracle Corporation",
    "ENPH": "Enphase Energy Inc.",
    "LMT": "Lockheed Martin Corporation",
    "PSX": "Phillips 66",
    "TTWO": "Take-Two Interactive Software ",
    "SABR": "Sabre Corporation",
    "PM": "Philip Morris International Inc",
    "GNPX": "Genprex Inc.",
    "CAT": "Caterpillar Inc.",
    "ELF": "e.l.f. Beauty Inc.",
    "MAIN": "Main Street Capital Corporation",
    "SONO": "Sonos Inc.",
    "DDOG": "Datadog Inc.",
    "FSLY": "Fastly Inc.",
    "KMI": "Kinder Morgan Inc.",
    "FUV": "Arcimoto Inc.",
    "EPD": "Enterprise Products Partners L.",
    "LTC": "LTC Properties Inc.",
    "CCI": "Crown Castle International Corp",
    "MANU": "Manchester",
    "MRVL": "Marvell Technology Group Ltd.",
    "SLB": "Schlumberger N.V.",
    "TWLO": "Twilio Inc.",
    "TRIP": "TripAdvisor Inc.",
    "IRM": "Iron Mountain Incorporated (Del",
    "SE": "Sea Limited",
    "AKTS": "Akoustis Technologies Inc.",
    "AMGN": "Amgen Inc.",
    "BE": "Bloom Energy Corporation",
    "PBA": "Pembina Pipeline Corp.",
    "BBBY": "Bed Bath & Beyond Inc.",
    "OMP": "Oasis Midstream Partners LP",
    "BIDU": "Baidu Inc.",
    "ENB": "Enbridge Inc",
    "FL": "Foot Locker Inc.",
    "GPRO": "GoPro Inc.",
    "HPQ": "HP Inc.",
    "SEDG": "SolarEdge Technologies Inc.",
    "AUY": "Yamana Gold Inc.",
    "EPR": "EPR Properties",
    "PSEC": "Prospect Capital Corporation",
    "STAG": "Stag Industrial Inc.",
    "AVGO": "Broadcom Inc.",
    "LLY": "Eli Lilly and Company",
    "KSS": "Kohl's Corporation",
    "FTI": "TechnipFMC plc",
    "BNTX": "BioNTech SE",
    "IRBT": "iRobot Corporation",
    "BTU": "Peabody Energy Corporation",
    "PBI": "Pitney Bowes Inc.",
    "LEG": "Leggett & Platt Incorporated",
    "SWKS": "Skyworks Solutions Inc.",
    "TXMD": "TherapeuticsMD Inc.",
    "CNK": "Cinemark Holdings Inc Cinemark ",
    "INMD": "InMode Ltd.",
    "JWN": "Nordstrom Inc.",
    "UNP": "Union Pacific Corporation",
    "COP": "ConocoPhillips",
    "MPC": "Marathon Petroleum Corporation",
    "UPS": "United Parcel Service Inc.",
    "CPTA": "Capitala Finance Corp.",
    "ENDP": "Endo International plc",
    "NEM": "Newmont Corporation",
    "PRU": "Prudential Financial Inc.",
    "SYK": "Stryker Corporation",
    "AAXN": "Axon Enterprise Inc.",
    "EOG": "EOG Resources Inc.",
    "APPN": "Appian Corporation",
    "KOPN": "Kopin Corporation",
    "GT": "The Goodyear Tire & Rubber Comp",
    "MDB": "MongoDB Inc.",
    "BEP": "Brookfield Renewable Partners L",
    "FSLR": "First Solar Inc.",
    "IVZ": "Invesco Ltd",
    "VSLR": "Vivint Solar Inc.",
    "SIRI": "Sirius XM Holdings Inc.",
    "AMT": "American Tower Corporation (REI",
    "CL": "Colgate-Palmolive Company",
    "PLYA": "Playa Hotels & Resorts N.V.",
    "APPS": "Digital Turbine Inc.",
    "EDIT": "Editas Medicine Inc.",
    "KMB": "Kimberly-Clark Corporation",
    "TXN": "Texas Instruments Incorporated",
    "BPY": "Brookfield Property Partners L.",
    "SO": "Southern Company (The)",
    "ACOR": "Acorda Therapeutics Inc.",
    "HRL": "Hormel Foods Corporation",
    "WDC": "Western Digital Corporation",
    "CHWY": "Chewy Inc.",
    "FANG": "Diamondback Energy Inc. - Comm",
    "FRT": "Federal Realty Investment Trust",
    "PNC": "PNC Financial Services Group I",
    "AFL": "AFLAC Incorporated",
    "NOV": "National Oilwell Varco Inc.",
    "CLX": "Clorox Company (The)",
    "TJX": "TJX Companies Inc. (The)",
    "ATRO": "Astronics Corporation",
    "VRTX": "Vertex Pharmaceuticals Incorpor",
    "ARCO": "Arcos Dorados Holdings Inc.",
    "DELL": "Dell Technologies Inc.",
    "D": "Dominion Energy Inc.",
    "JKS": "JinkoSolar Holding Company Limi",
    "PBR": "Petroleo Brasileiro S.A.- Petro",
    "SJR": "Shaw Communications Inc.",
    "RY": "Royal Bank Of Canada",
    "CRSP": "CRISPR Therapeutics AG",
    "FIT": "Fitbit Inc.",
    "GERN": "Geron Corporation",
    "MAXR": "Maxar Technologies Inc.",
    "RGLD": "Royal Gold Inc.",
    "SWN": "Southwestern Energy Company",
    "TMUS": "T-Mobile US Inc.",
    "NVTA": "Invitae Corporation",
    "MPW": "Medical Properties Trust Inc.",
    "SFIX": "Stitch Fix Inc.",
    "WSR": "Whitestone REIT",
    "ANIP": "ANI Pharmaceuticals Inc.",
    "CQP": "Cheniere Energy Partners LP Ch",
    "GLW": "Corning Incorporated",
    "ESTC": "Elastic N.V.",
    "HAS": "Hasbro Inc.",
    "STNE": "StoneCo Ltd.",
    "TEVA": "Teva Pharmaceutical Industries ",
    "WATT": "Energous Corporation",
    "IIPR": "Innovative Industrial Propertie",
    "PVH": "PVH Corp.",
    "BGFV": "Big 5 Sporting Goods Corporatio",
    "CCEP": "Coca-Cola European Partners plc",
    "ED": "Consolidated Edison Inc.",
    "DRI": "Darden Restaurants Inc.",
    "LADR": "Ladder Capital Corp",
    "NEP": "NextEra Energy Partners LP",
    "ADPT": "Adaptive Biotechnologies Corpor",
    "BIIB": "Biogen Inc.",
    "ILMN": "Illumina Inc.",
    "LOW": "Lowe's Companies Inc.",
    "PCG": "Pacific Gas & Electric Co.",
    "PDD": "Pinduoduo Inc.",
    "QD": "Qudian Inc.",
    "BNS": "Bank Nova Scotia Halifax Pfd 3",
    "ZTS": "Zoetis Inc.",
    "ARLP": "Alliance Resource Partners L.P",
    "ADP": "Automatic Data Processing Inc.",
    "BKR": "Baker Hughes Company",
    "LYB": "LyondellBasell Industries NV",
    "NRG": "NRG Energy Inc.",
    "SMAR": "Smartsheet Inc.",
    "XBIT": "XBiotech Inc.",
    "AA": "Alcoa Corporation",
    "DISCA": "Discovery Inc. - Series A",
    "EMR": "Emerson Electric Company",
    "EL": "Estee Lauder Companies Inc. (T",
    "SLG": "SL Green Realty Corp",
    "ZS": "Zscaler Inc.",
    "ALB": "Albemarle Corporation",
    "BBY": "Best Buy Co. Inc.",
    "BPYU": "Brookfield Property REIT Inc.",
    "CAN": "Canaan Inc.",
    "DOW": "Dow Inc.",
    "GPC": "Genuine Parts Company",
    "INSG": "Inseego Corp.",
    "OHI": "Omega Healthcare Investors Inc",
    "UNM": "Unum Group",
    "VNOM": "Viper Energy Partners LP",
    "WRTC": "Wrap Technologies Inc.",
    "AIR": "AAR Corp.",
    "BIP": "Brookfield Infrastructure Partn",
    "CHL": "China Mobile Limited",
    "GIS": "General Mills Inc.",
    "GEOS": "Geospace Technologies Corporati",
    "LIN": "Linde plc",
    "NPTN": "NeoPhotonics Corporation",
    "NVO": "Novo Nordisk A/S",
    "RUTH": "Ruth's Hospitality Group Inc.",
    "SCM": "Stellus Capital Investment Corp",
    "REAL": "The RealReal Inc.",
    "VERI": "Veritone Inc.",
    "AVAV": "AeroVironment Inc.",
    "ADM": "Archer-Daniels-Midland Company",
    "TEAM": "Atlassian Corporation Plc",
    "GLOG": "GasLog Ltd.",
    "MMP": "Magellan Midstream Partners L.P",
    "NUE": "Nucor Corporation",
    "VIR": "Vir Biotechnology Inc.",
    "AMAT": "Applied Materials Inc.",
    "DFS": "Discover Financial Services",
    "GAIN": "Gladstone Investment Corporatio",
    "LBTYA": "Liberty Global plc",
    "LTHM": "Livent Corporation",
    "MET": "MetLife Inc.",
    "NMRK": "Newmark Group Inc.",
    "PING": "Ping Identity Holding Corp.",
    "TM": "Toyota Motor Corporation",
    "XLNX": "Xilinx Inc.",
    "AER": "AerCap Holdings N.V.",
    "ADSK": "Autodesk Inc.",
    "BCEI": "Bonanza Creek Energy Inc.",
    "CPRI": "Capri Holdings Limited",
    "ECL": "Ecolab Inc.",
    "GOGO": "Gogo Inc.",
    "INTU": "Intuit Inc.",
    "LEVI": "Levi Strauss & Co",
    "NK": "NantKwest Inc.",
    "SUNS": "Solar Senior Capital Ltd.",
    "SPWR": "SunPower Corporation",
    "CHEF": "The Chefs' Warehouse Inc.",
    "VMW": "Vmware Inc.",
    "WPC": "W. P. Carey Inc. REIT",
    "ADS": "Alliance Data Systems Corporati",
    "LAND": "Gladstone Land Corporation",
    "GLUU": "Glu Mobile Inc.",
    "TMO": "Thermo Fisher Scientific Inc",
    "UXIN": "Uxin Limited",
    "WWE": "World Wrestling Entertainment ",
    "AES": "The AES Corporation",
    "ARI": "Apollo Commercial Real Estate F",
    "CM": "Canadian Imperial Bank of Comme",
    "HOG": "Harley-Davidson Inc.",
    "SKYW": "SkyWest Inc.",
    "SSYS": "Stratasys Ltd.",
    "SNCR": "Synchronoss Technologies Inc.",
    "ZEN": "Zendesk Inc.",
    "Z": "Zillow Group Inc.",
    "BZUN": "Baozun Inc.",
    "BSM": "Black Stone Minerals L.P.",
    "BYD": "Boyd Gaming Corporation",
    "CNP": "CenterPoint Energy Inc (Holdin",
    "COUP": "Coupa Software Incorporated",
    "GFL": "GFL Environmental Inc. Subordin",
    "EAF": "GrafTech International Ltd.",
    "HUYA": "HUYA Inc.",
    "IMMU": "Immunomedics Inc.",
    "MAT": "Mattel Inc.",
    "NOW": "ServiceNow Inc.",
    "SRT": "StarTek Inc.",
    "TD": "Toronto Dominion Bank (The)",
    "WRK": "Westrock Company",
    "AGRX": "Agile Therapeutics Inc.",
    "COG": "Cabot Oil & Gas Corporation",
    "GOOS": "Canada Goose Holdings Inc. Subo",
    "COF": "Capital One Financial Corporati",
    "CRT": "Cross Timbers Royalty Trust",
    "FIVN": "Five9 Inc.",
    "GLOP": "GasLog Partners LP",
    "HP": "Helmerich & Payne Inc.",
    "NLOK": "NortonLifeLock Inc.",
    "URBN": "Urban Outfitters Inc.",
    "WB": "Weibo Corporation",
    "ANF": "Abercrombie & Fitch Company",
    "AEM": "Agnico Eagle Mines Limited",
    "NLY": "Annaly Capital Management Inc",
    "CINF": "Cincinnati Financial Corporatio",
    "BEN": "Franklin Resources Inc.",
    "MNK": "Mallinckrodt plc",
    "NTES": "NetEase Inc.",
    "PBCT": "People's",
    "DTIL": "Precision BioSciences Inc.",
    "PBYI": "Puma Biotechnology Inc",
    "TWOU": "2U Inc.",
    "AKAM": "Akamai Technologies Inc.",
    "ANSS": "ANSYS Inc.",
    "BHC": "Bausch Health Companies Inc.",
    "BDSI": "BioDelivery Sciences Internatio",
    "BG": "Bunge Limited Bunge Limited",
    "CWH": "Camping World Holdings Inc.",
    "FUN": "Cedar Fair L.P.",
    "CMG": "Chipotle Mexican Grill Inc.",
    "EXC": "Exelon Corporation",
    "HBI": "Hanesbrands Inc.",
    "HRZN": "Horizon Technology Finance Corp",
    "MKC": "McCormick & Company Incorporat",
    "PDLI": "PDL BioPharma Inc.",
    "QRVO": "Qorvo Inc.",
    "SHAK": "Shake Shack Inc.",
    "SPLK": "Splunk Inc.",
    "SPT": "Sprout Social Inc",
    "STWD": "STARWOOD PROPERTY TRUST INC. S",
    "UVV": "Universal Corporation",
    "ALXN": "Alexion Pharmaceuticals Inc.",
    "BB": "BlackBerry Limited",
    "CRDF": "Cardiff Oncology Inc.",
    "CHU": "China Unicom (Hong Kong) Ltd",
    "CXW": "CoreCivic Inc.",
    "DLPH": "Delphi Technologies PLC",
    "EMN": "Eastman Chemical Company",
    "FTCH": "Farfetch Limited",
    "FIS": "Fidelity National Information S",
    "FLIR": "FLIR Systems Inc.",
    "GOOD": "Gladstone Commercial Corporatio",
    "LB": "L Brands Inc.",
    "MYL": "Mylan N.V.",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "RESN": "Resonant Inc.",
    "SPH": "Suburban Propane Partners L.P.",
    "VICI": "VICI Properties Inc.",
    "AL": "Air Lease Corporation",
    "KERN": "Akerna Corp.",
    "BNFT": "Benefitfocus Inc.",
    "BGSF": "BG Staffing Inc",
    "BXP": "Boston Properties Inc.",
    "SCHW": "Charles Schwab Corporation (The",
    "CLVS": "Clovis Oncology Inc.",
    "CME": "CME Group Inc.",
    "DLTR": "Dollar Tree Inc.",
    "EHTH": "eHealth Inc.",
    "FISV": "Fiserv Inc.",
    "FLR": "Fluor Corporation",
    "HASI": "Hannon Armstrong Sustainable In",
    "HBIO": "Harvard Bioscience Inc.",
    "IRDM": "Iridium Communications Inc",
    "JCI": "Johnson Controls International ",
    "NTAP": "NetApp Inc.",
    "PANW": "Palo Alto Networks Inc.",
    "TRUE": "TrueCar Inc.",
    "WSG": "Wanda Sports Group Company Limi",
    "W": "Wayfair Inc.",
    "WYND": "Wyndham Destinations Inc.",
    "APD": "Air Products and Chemicals Inc",
    "AZRE": "Azure Power Global Limited",
    "BBSI": "Barrett Business Services Inc.",
    "BLMN": "Bloomin' Brands Inc.",
    "CI": "Cigna Corporation",
    "CSX": "CSX Corporation",
    "DE": "Deere & Company",
    "EW": "Edwards Lifesciences Corporatio",
    "ENIA": "Enel Americas S.A.",
    "FTNT": "Fortinet Inc.",
    "FNV": "Franco-Nevada Corporation",
    "ITW": "Illinois Tool Works Inc.",
    "NTLA": "Intellia Therapeutics Inc.",
    "LAUR": "Laureate Education Inc.",
    "LAZ": "Lazard LTD. Lazard LTD.",
    "LEN": "Lennar Corporation",
    "LX": "LexinFintech Holdings Ltd.",
    "MELI": "MercadoLibre Inc.",
    "MCRI": "Monarch Casino & Resort Inc.",
    "NTGR": "NETGEAR Inc.",
    "PD": "PagerDuty Inc.",
    "PAA": "Plains All American Pipeline L",
    "QTT": "Qutoutiao Inc.",
    "SHO": "Sunstone Hotel Investors Inc. ",
    "TER": "Teradyne Inc.",
    "MOS": "Mosaic Company (The)",
    "TIF": "Tiffany & Co.",
    "VLY": "Valley National Bancorp",
    "VKTX": "Viking Therapeutics Inc.",
    "WES": "Western Midstream Partners LP",
    "ALEX": "Alexander & Baldwin Inc.",
    "AMBA": "Ambarella Inc.",
    "AWR": "American States Water Company",
    "ANET": "Arista Networks Inc.",
    "BIG": "Big Lots Inc.",
    "CHRS": "Coherus BioSciences Inc.",
    "CONE": "CyrusOne Inc",
    "EQT": "EQT Corporation",
    "EXTR": "Extreme Networks Inc.",
    "HEP": "Holly Energy Partners L.P.",
    "IMGN": "ImmunoGen Inc.",
    "IPHI": "Inphi Corporation",
    "ICE": "Intercontinental Exchange Inc.",
    "JEF": "Jefferies Financial Group Inc.",
    "JNPR": "Juniper Networks Inc.",
    "LSCC": "Lattice Semiconductor Corporati",
    "LIZI": "LIZHI INC.",
    "LITE": "Lumentum Holdings Inc.",
    "MCY": "Mercury General Corporation",
    "MDP": "Meredith Corporation",
    "MHK": "Mohawk Industries Inc.",
    "NDAQ": "Nasdaq Inc.",
    "NAVI": "Navient Corporation",
    "PACB": "Pacific Biosciences of Californ",
    "PAVM": "PAVmed Inc.",
    "PAYX": "Paychex Inc.",
    "PRFT": "Perficient Inc.",
    "QIWI": "QIWI plc",
    "SSTI": "ShotSpotter Inc.",
    "SPWH": "Sportsman's Warehouse Holdings",
    "SUPN": "Supernus Pharmaceuticals Inc.",
    "VRNT": "Verint Systems Inc.",
    "VIRT": "Virtu Financial Inc.",
    "WY": "Weyerhaeuser Company",
    "YNDX": "Yandex N.V.",
    "YJ": "Yunji Inc. - American Depositor",
    "ACCO": "Acco Brands Corporation",
    "ALRM": "Alarm.com Holdings Inc.",
    "MDRX": "Allscripts Healthcare Solutions",
    "ARCT": "Arcturus Therapeutics Holdings ",
    "ARLO": "Arlo Technologies Inc.",
    "ATRA": "Atara Biotherapeutics Inc.",
    "AVDL": "Avadel Pharmaceuticals plc",
    "AVID": "Avid Technology Inc.",
    "BBDC": "Barings BDC Inc.",
    "BLUE": "bluebird bio Inc.",
    "BSX": "Boston Scientific Corporation",
    "BOX": "Box Inc.",
    "CCJ": "Cameco Corporation",
    "CARG": "CarGurus Inc.",
    "KMX": "CarMax Inc",
    "CTSH": "Cognizant Technology Solutions ",
    "COMM": "CommScope Holding Company Inc.",
    "TACO": "Del Taco Restaurants Inc.",
    "DKS": "Dick's Sporting Goods Inc",
    "EPAM": "EPAM Systems Inc.",
    "FCPT": "Four Corners Property Trust In",
    "FOXA": "Fox Corporation",
    "HRB": "H&R Block Inc.",
    "IVAC": "Intevac Inc.",
    "LILA": "Liberty Latin America Ltd.",
    "LPSN": "LivePerson Inc.",
    "L": "Loews Corporation",
    "MDU": "MDU Resources Group Inc.",
    "VIVO": "Meridian Bioscience Inc.",
    "MNR": "Monmouth Real Estate Investment",
    "MYGN": "Myriad Genetics Inc.",
    "NC": "NACCO Industries Inc.",
    "NH": "NantHealth Inc.",
    "PH": "Parker-Hannifin Corporation",
    "PT": "Pintec Technology Holdings Limi",
    "QTNT": "Quotient Limited",
    "ROST": "Ross Stores Inc.",
    "SEAC": "SeaChange International Inc.",
    "SYNC": "Synacor Inc.",
    "TRP": "TC Energy Corporation",
    "TDC": "Teradata Corporation",
    "VFC": "V.F. Corporation",
    "VRSK": "Verisk Analytics Inc.",
    "XYL": "Xylem Inc.",
    "ACIU": "AC Immune SA",
    "AMRC": "Ameresco Inc.",
    "AEP": "American Electric Power Company",
    "AFIN": "American Finance Trust Inc.",
    "AMKR": "Amkor Technology Inc.",
    "AMPH": "Amphastar Pharmaceuticals Inc.",
    "ATRS": "Antares Pharma Inc.",
    "AON": "Aon plc",
    "ARC": "ARC Document Solutions Inc.",
    "ATHX": "Athersys Inc.",
    "AVA": "Avista Corporation",
    "BAND": "Bandwidth Inc.",
    "BYSI": "BeyondSpring Inc.",
    "BHP": "BHP Group Limited",
    "BJ": "BJ's Wholesale Club Holdings I",
    "BBIO": "BridgeBio Pharma Inc.",
    "CVGW": "Calavo Growers Inc.",
    "CVNA": "Carvana Co.",
    "CRNT": "Ceragon Networks Ltd.",
    "XEC": "Cimarex Energy Co",
    "CTXS": "Citrix Systems Inc.",
    "CODI": "Compass Diversified Holdings Sh",
    "CEIX": "CONSOL Energy Inc.",
    "CRTO": "Criteo S.A.",
    "CCRN": "Cross Country Healthcare Inc.",
    "CMI": "Cummins Inc.",
    "DAR": "Darling Ingredients Inc.",
    "DISCK": "Discovery Inc. - Series C",
    "EQR": "Equity Residential",
    "ESPR": "Esperion Therapeutics Inc.",
    "ESS": "Essex Property Trust Inc.",
    "EVR": "Evercore Inc.",
    "ES": "Eversource Energy (D/B/A)",
    "EXTN": "Exterran Corporation",
    "FRG": "Franchise Group Inc.",
    "HEES": "H&E Equipment Services Inc.",
    "HSIC": "Henry Schein Inc.",
    "HBAN": "Huntington Bancshares Incorpora",
    "IDXX": "IDEXX Laboratories Inc.",
    "IHRT": "iHeartMedia Inc.",
    "IMMR": "Immersion Corporation",
    "IP": "International Paper Company",
    "KEY": "KeyCorp",
    "KIM": "Kimco Realty Corporation",
    "KKR": "KKR & Co. Inc.",
    "KTB": "Kontoor Brands Inc.",
    "LMRK": "Landmark Infrastructure Partner",
    "LGC": "Legacy Acquisition Corp.",
    "LBTYK": "Liberty Global plc",
    "LILAK": "Liberty Latin America Ltd.",
    "MTSI": "MACOM Technology Solutions Hold",
    "MRUS": "Merus N.V.",
    "MCHP": "Microchip Technology Incorporat",
    "MTSC": "MTS Systems Corporation",
    "NREF": "NexPoint Real Estate Finance I",
    "NTR": "Nutrien Ltd.",
    "ORA": "Ormat Technologies Inc.",
    "PLAB": "Photronics Inc.",
    "PLD": "Prologis Inc.",
    "PSA": "Public Storage",
    "QRTEA": "Liberty Interactive Corporation",
    "RGP": "Resources Connection Inc.",
    "R": "Ryder System Inc.",
    "SAGE": "Sage Therapeutics Inc.",
    "SBGI": "Sinclair Broadcast Group Inc.",
    "SNA": "Snap-On Incorporated",
    "TRGP": "Targa Resources Inc.",
    "TH": "Target Hospitality Corp.",
    "TMDX": "TransMedics Group Inc.",
    "TRUP": "Trupanion Inc.",
    "UCTT": "Ultra Clean Holdings Inc.",
    "UMH": "UMH Properties Inc.",
    "GWW": "W.W. Grainger Inc.",
    "WTS": "Watts Water Technologies Inc.",
    "WWD": "Woodward Inc.",
    "YUMC": "Yum China Holdings Inc.",
    "JFU": "9F Inc.",
    "ATEN": "A10 Networks Inc.",
    "ACHC": "Acadia Healthcare Company Inc.",
    "ADNT": "Adient plc",
    "AEIS": "Advanced Energy Industries Inc",
    "ACM": "AECOM",
    "A": "Agilent Technologies Inc.",
    "AMED": "Amedisys Inc",
    "AMN": "AMN Healthcare Services Inc AMN",
    "PLAN": "Anaplan Inc.",
    "ANAB": "AnaptysBio Inc.",
    "ANIK": "Anika Therapeutics Inc.",
    "APPF": "AppFolio Inc.",
    "AROC": "Archrock Inc.",
    "AIZ": "Assurant Inc.",
    "ATOM": "Atomera Incorporated",
    "AVT": "Avnet Inc.",
    "AXS": "Axis Capital Holdings Limited",
    "BGS": "B&G Foods Inc. B&G Foods Inc.",
    "BMRN": "BioMarin Pharmaceutical Inc.",
    "BJRI": "BJ's Restaurants Inc.",
    "BKH": "Black Hills Corporation",
    "EPAY": "Bottomline Technologies Inc.",
    "BV": "BrightView Holdings Inc.",
    "CDNS": "Cadence Design Systems Inc.",
    "CAMP": "CalAmp Corp.",
    "CARA": "Cara Therapeutics Inc.",
    "CF": "CF Industries Holdings Inc.",
    "CHTR": "Charter Communications Inc.",
    "COLL": "Collegium Pharmaceutical Inc.",
    "CAG": "ConAgra Brands Inc.",
    "BAP": "Credicorp Ltd.",
    "CRESY": "Cresud S.A.C.I.F. y A.",
    "CUE": "Cue Biopharma Inc.",
    "DAKT": "Daktronics Inc.",
    "DISH": "DISH Network Corporation",
    "DEI": "Douglas Emmett Inc.",
    "SATS": "EchoStar Corporation",
    "ENIC": "Enel Chile S.A.",
    "MRAM": "Everspin Technologies Inc.",
    "EXR": "Extra Space Storage Inc",
    "FDS": "FactSet Research Systems Inc.",
    "FAST": "Fastenal Company",
    "FLT": "FleetCor Technologies Inc.",
    "GTHX": "G1 Therapeutics Inc.",
    "GTX": "Garrett Motion Inc.",
    "GNTX": "Gentex Corporation",
    "HLNE": "Hamilton Lane Incorporated",
    "HCA": "HCA Healthcare Inc.",
    "HUBS": "HubSpot Inc.",
    "INVH": "Invitation Homes Inc.",
    "IQ": "iQIYI Inc.",
    "KW": "Kennedy-Wilson Holdings Inc.",
    "KBAL": "Kimball International Inc.",
    "KNSA": "Kiniksa Pharmaceuticals Ltd.",
    "KEP": "Korea Electric Power Corporatio",
    "LRCX": "Lam Research Corporation",
    "LORL": "Loral Space and Communications",
    "LUNA": "Luna Innovations Incorporated",
    "MNTX": "Manitex International Inc.",
    "MCHX": "Marchex Inc.",
    "MATW": "Matthews International Corporat",
    "MITK": "Mitek Systems Inc.",
    "MIXT": "MiX Telematics Limited",
    "MPLX": "MPLX LP",
    "NBIX": "Neurocrine Biosciences Inc.",
    "NXTC": "NextCure Inc.",
    "NICE": "NICE Ltd",
    "NSC": "Norfolk Southern Corporation",
    "NTRS": "Northern Trust Corporation",
    "OMER": "Omeros Corporation",
    "OSW": "OneSpaWorld Holdings Limited",
    "PDCO": "Patterson Companies Inc.",
    "PSXP": "Phillips 66 Partners LP",
    "DOC": "Physicians Realty Trust",
    "PFPT": "Proofpoint Inc.",
    "QADB": "QAD Inc.",
    "QLYS": "Qualys Inc.",
    "RDUS": "Radius Health Inc.",
    "RPD": "Rapid7 Inc.",
    "RDVT": "Red Violet Inc.",
    "RDHL": "Redhill Biopharma Ltd.",
    "RPAY": "Repay Holdings Corporation",
    "KRMD": "Repro Med Systems Inc.",
    "SPNS": "Sapiens International Corporati",
    "SCSC": "ScanSource Inc.",
    "SCWX": "SecureWorks Corp.",
    "SRE": "Sempra Energy",
    "SREV": "ServiceSource International In",
    "SLP": "Simulations Plus Inc.",
    "SLM": "SLM Corporation",
    "SGH": "SMART Global Holdings Inc.",
    "SMCI": "Super Micro Computer Inc.",
    "SYKE": "Sykes Enterprises Incorporated",
    "TAL": "TAL Education Group",
    "BX": "The Blackstone Group Inc.",
    "PLCE": "Children's Place Inc. (The)",
    "SHYF": "The Shyft Group Inc.",
    "TSCO": "Tractor Supply Company",
    "WCN": "Waste Connections Inc.",
    "WHR": "Whirlpool Corporation",
    "WIX": "Wix.com Ltd.",
    "WDAY": "Workday Inc.",
    "XNET": "Xunlei Limited",
    "SRCE": "1st Source Corporation",
    "AOS": "A.O. Smith Corporation",
    "ABMD": "ABIOMED Inc.",
    "ASIX": "AdvanSix Inc.",
    "ADVM": "Adverum Biotechnologies Inc.",
    "AGYS": "Agilysys Inc.",
    "AIMT": "Aimmune Therapeutics Inc.",
    "AIRG": "Airgain Inc.",
    "ALG": "Alamo Group Inc.",
    "ALBO": "Albireo Pharma Inc.",
    "ARE": "Alexandria Real Estate Equities",
    "ALL": "Allstate Corporation (The)",
    "AOSL": "Alpha and Omega Semiconductor L",
    "APLT": "Applied Therapeutics Inc.",
    "ARQT": "Arcutis Biotherapeutics Inc.",
    "AROW": "Arrow Financial Corporation",
    "ASB": "Associated Banc-Corp",
    "ASUR": "Asure Software Inc",
    "ATO": "Atmos Energy Corporation",
    "AN": "AutoNation Inc.",
    "AVY": "Avery Dennison Corporation",
    "AVRO": "AVROBIO Inc.",
    "AWRE": "Aware Inc.",
    "BMI": "Badger Meter Inc.",
    "BAX": "Baxter International Inc.",
    "BILL": "Bill.com Holdings Inc.",
    "BEAT": "BioTelemetry Inc.",
    "BAH": "Booz Allen Hamilton Holding Cor",
    "BRC": "Brady Corporation",
    "BRX": "Brixmor Property Group Inc.",
    "BRO": "Brown & Brown Inc.",
    "BC": "Brunswick Corporation",
    "BKE": "Buckle Inc. (The)",
    "BLDR": "Builders FirstSource Inc.",
    "CAI": "CAI International Inc.",
    "CPB": "Campbell Soup Company",
    "CATY": "Cathay General Bancorp",
    "CE": "Celanese Corporation Celanese C",
    "COLB": "Columbia Banking System Inc.",
    "CPRT": "Copart Inc.",
    "COR": "CoreSite Realty Corporation",
    "CTVA": "Corteva Inc.",
    "CRVL": "CorVel Corp.",
    "CZZ": "Cosan Limited",
    "CSGP": "CoStar Group Inc.",
    "CACC": "Credit Acceptance Corporation",
    "CREE": "Cree Inc.",
    "CSGS": "CSG Systems International Inc.",
    "CW": "Curtiss-Wright Corporation",
    "CYBE": "CyberOptics Corporation",
    "CTMX": "CytomX Therapeutics Inc.",
    "DVA": "DaVita Inc.",
    "DGII": "Digi International Inc.",
    "DMRC": "Digimarc Corporation",
    "DOV": "Dover Corporation",
    "DSPG": "DSP Group Inc.",
    "EGBN": "Eagle Bancorp Inc.",
    "EIX": "Edison International",
    "ESI": "Element Solutions Inc.",
    "ECPG": "Encore Capital Group Inc",
    "DAVA": "Endava plc",
    "FFIN": "First Financial Bankshares Inc",
    "FTS": "Fortis Inc.",
    "FEIM": "Frequency Electronics Inc.",
    "FREQ": "Frequency Therapeutics Inc.",
    "FULT": "Fulton Financial Corporation",
    "FUTU": "Futu Holdings Limited",
    "GDDY": "GoDaddy Inc.",
    "GDEN": "Golden Entertainment Inc.",
    "AJX": "Great Ajax Corp.",
    "HTLF": "Heartland Financial USA Inc.",
    "HLF": "Herbalife Nutrition Ltd.",
    "HCCI": "Heritage-Crystal Clean Inc.",
    "HNP": "Huaneng Power Intl",
    "HPP": "Hudson Pacific Properties Inc.",
    "HUM": "Humana Inc.",
    "INFO": "IHS Markit Ltd.",
    "INCY": "Incyte Corporation",
    "IPG": "Interpublic Group of Companies",
    "KALA": "Kala Pharmaceuticals Inc.",
    "K": "Kellogg Company",
    "KEQU": "Kewaunee Scientific Corporation",
    "KLAC": "KLA Corporation",
    "KFY": "Korn Ferry",
    "KRYS": "Krystal Biotech Inc.",
    "LNTH": "Lantheus Holdings Inc.",
    "LDOS": "Leidos Holdings Inc.",
    "MKTX": "MarketAxess Holdings Inc.",
    "MXIM": "Maxim Integrated Products Inc.",
    "MGTX": "MeiraGTx Holdings plc",
    "MIME": "Mimecast Limited",
    "MC": "Moelis & Company",
    "MPWR": "Monolithic Power Systems Inc.",
    "NSTG": "NanoString Technologies Inc.",
    "EDU": "New Oriental Education & Techno",
    "NWSA": "News Corporation",
    "ORLY": "O'Reilly Automotive Inc.",
    "ON": "ON Semiconductor Corporation",
    "KIDS": "OrthoPediatrics Corp.",
    "PLMR": "Palomar Holdings Inc.",
    "PASG": "Passage Bio Inc.",
    "PCTI": "PCTEL Inc.",
    "PLXS": "Plexus Corp.",
    "PRVB": "Provention Bio Inc.",
    "QADA": "QAD Inc.",
    "RMBS": "Rambus Inc.",
    "RF": "Regions Financial Corporation",
    "RCII": "Rent-A-Center Inc.",
    "RGCO": "RGC Resources Inc.",
    "RYTM": "Rhythm Pharmaceuticals Inc.",
    "RCKT": "Rocket Pharmaceuticals Inc.",
    "RUHN": "Ruhnn Holding Limited",
    "BFS": "Saul Centers Inc.",
    "SIGI": "Selective Insurance Group Inc.",
    "SSTK": "Shutterstock Inc.",
    "SWIR": "Sierra Wireless Inc.",
    "SWK": "Stanley Black & Decker Inc.",
    "STOK": "Stoke Therapeutics Inc.",
    "SYNA": "Synaptics Incorporated",
    "SNPS": "Synopsys Inc.",
    "TROW": "T. Rowe Price Group Inc.",
    "TXRH": "Texas Roadhouse Inc.",
    "GBX": "Greenbrier Companies Inc. (The",
    "TSBK": "Timberland Bancorp Inc.",
    "TKR": "Timken Company (The)",
    "TSC": "TriState Capital Holdings Inc.",
    "TTMI": "TTM Technologies Inc.",
    "ULTA": "Ulta Beauty Inc.",
    "URI": "United Rentals Inc.",
    "USM": "United States Cellular Corporat",
    "VREX": "Varex Imaging Corporation",
    "VRNS": "Varonis Systems Inc.",
    "VECO": "Veeco Instruments Inc.",
    "VRTU": "Virtusa Corporation",
    "VYGR": "Voyager Therapeutics Inc.",
    "VMC": "Vulcan Materials Company (Holdi",
    "WAFD": "Washington Federal Inc.",
    "WK": "Workiva Inc.",
    "ZION": "Zions Bancorporation N.A.",
    "QFIN": "360 Finance Inc.",
    "ACIW": "ACI Worldwide Inc.",
    "ADUS": "Addus HomeCare Corporation",
    "AAP": "Advance Auto Parts Inc Advance ",
    "AERI": "Aerie Pharmaceuticals Inc.",
    "AMG": "Affiliated Managers Group Inc.",
    "AGIO": "Agios Pharmaceuticals Inc.",
    "ADC": "Agree Realty Corporation",
    "AKCA": "Akcea Therapeutics Inc.",
    "AKRO": "Akero Therapeutics Inc.",
    "ALC": "Alcon Inc.",
    "ALX": "Alexander's Inc.",
    "ALLK": "Allakos Inc.",
    "ALLE": "Allegion plc",
    "LNT": "Alliant Energy Corporation",
    "APEI": "American Public Education Inc.",
    "AMSWA": "American Software Inc.",
    "CRMT": "America's Car-Mart Inc.",
    "AMSF": "AMERISAFE Inc.",
    "AME": "AMETEK Inc.",
    "ADI": "Analog Devices Inc.",
    "ATEX": "Anterix Inc.",
    "AMEH": "Apollo Medical Holdings Inc.",
    "APRE": "Aprea Therapeutics Inc.",
    "ARDX": "Ardelyx Inc.",
    "AGX": "Argan Inc.",
    "ASGN": "ASGN Incorporated",
    "AC": "Associated Capital Group Inc.",
    "ATNX": "Athenex Inc.",
    "AUB": "Atlantic Union Bankshares Corpo",
    "ATNI": "ATN International Inc.",
    "ATHM": "Autohome Inc.",
    "AZO": "AutoZone Inc.",
    "AVNS": "Avanos Medical Inc.",
    "AVTR": "Avantor Inc.",
    "AXNX": "Axonics Modulation Technologies",
    "BCPC": "Balchem Corporation",
    "BLL": "Ball Corporation",
    "BECN": "Beacon Roofing Supply Inc.",
    "BEAM": "Beam Therapeutics Inc.",
    "BDC": "Belden Inc",
    "BHE": "Benchmark Electronics Inc.",
    "BTAI": "BioXcel Therapeutics Inc.",
    "BCOR": "Blucora Inc.",
    "BOKF": "BOK Financial Corporation",
    "BWA": "BorgWarner Inc.",
    "BOMN": "Boston Omaha Corporation",
    "BDGE": "Bridge Bancorp Inc.",
    "BCOV": "Brightcove Inc.",
    "BRKS": "Brooks Automation Inc.",
    "BURL": "Burlington Stores Inc.",
    "CABO": "Cable One Inc.",
    "CCMP": "Cabot Microelectronics Corporat",
    "CATM": "Cardtronics plc",
    "CDNA": "CareDx Inc.",
    "CSL": "Carlisle Companies Incorporated",
    "CSTL": "Castle Biosciences Inc.",
    "CNTG": "Centogene N.V.",
    "CERN": "Cerner Corporation",
    "CEVA": "CEVA Inc.",
    "CHUY": "Chuy's Holdings Inc.",
    "CTAS": "Cintas Corporation",
    "CHCO": "City Holding Company",
    "CMS": "CMS Energy Corporation",
    "COHR": "Coherent Inc.",
    "CFX": "Colfax Corporation",
    "CBU": "Community Bank System Inc.",
    "CPSI": "Computer Programs and Systems ",
    "CTG": "Computer Task Group Incorporat",
    "CRNX": "Crinetics Pharmaceuticals Inc.",
    "CTS": "CTS Corporation",
    "CVBF": "CVB Financial Corporation",
    "DHI": "D.R. Horton Inc.",
    "DJCO": "Daily Journal Corp. (S.C.)",
    "DMTK": "DermTech Inc.",
    "DIOD": "Diodes Incorporated",
    "DTE": "DTE Energy Company",
    "EGRX": "Eagle Pharmaceuticals Inc.",
    "LOCO": "El Pollo Loco Holdings Inc.",
    "ENTA": "Enanta Pharmaceuticals Inc.",
    "ENV": "Envestnet Inc",
    "EVA": "Enviva Partners LP",
    "PLUS": "ePlus inc.",
    "EFX": "Equifax Inc.",
    "ERIE": "Erie Indemnity Company",
    "ESTA": "Establishment Labs Holdings Inc",
    "EXPI": "eXp World Holdings Inc.",
    "EXPO": "Exponent Inc.",
    "FFIV": "F5 Networks Inc.",
    "FGEN": "FibroGen Inc",
    "FITB": "Fifth Third Bancorp",
    "FCNCA": "First Citizens BancShares Inc.",
    "FHB": "First Hawaiian Inc.",
    "FORM": "FormFactor Inc.",
    "FORR": "Forrester Research Inc.",
    "FTDR": "frontdoor inc.",
    "GATX": "GATX Corporation",
    "GCP": "GCP Applied Technologies Inc.",
    "GFN": "General Finance Corporation",
    "GL": "Globe Life Inc.",
    "GSHD": "Goosehead Insurance Inc.",
    "GHG": "GreenTree Hospitality Group Ltd",
    "GDYN": "Grid Dynamics Holdings Inc.",
    "GSIT": "GSI Technology Inc.",
    "HIG": "Hartford Financial Services Gro",
    "HSTM": "HealthStream Inc.",
    "HSII": "Heidrick & Struggles Internatio",
    "HMSY": "HMS Holdings Corp",
    "HUBB": "Hubbell Inc",
    "IMAB": "I-MAB",
    "ICHR": "Ichor Holdings",
    "IBKR": "Interactive Brokers Group Inc.",
    "IFF": "Internationa Flavors & Fragranc",
    "ISBC": "Investors Bancorp Inc.",
    "IPGP": "IPG Photonics Corporation",
    "ITRI": "Itron Inc.",
    "JBHT": "J.B. Hunt Transport Services I",
    "MAYS": "J. W. Mays Inc.",
    "JBL": "Jabil Inc.",
    "J": "Jacobs Engineering Group Inc.",
    "JRVR": "James River Group Holdings Ltd",
    "JBT": "John Bean Technologies Corporat",
    "KAI": "Kadant Inc",
    "KE": "Kimball Electronics Inc.",
    "KURA": "Kura Oncology Inc.",
    "LKFN": "Lakeland Financial Corporation",
    "TREE": "LendingTree Inc.",
    "LNC": "Lincoln National Corporation",
    "LFUS": "Littelfuse Inc.",
    "RAMP": "LiveRamp Holdings Inc.",
    "MANH": "Manhattan Associates Inc.",
    "MAN": "ManpowerGroup",
    "MLM": "Martin Marietta Materials Inc.",
    "MAS": "Masco Corporation",
    "MXL": "MaxLinear Inc.",
    "MGEE": "MGE Energy Inc.",
    "MTEM": "Molecular Templates Inc.",
    "MORF": "Morphic Holding Inc.",
    "COOP": "Mr. Cooper Group Inc.",
    "MUSA": "Murphy USA Inc.",
    "NSSC": "NAPCO Security Technologies In",
    "NTCT": "NetScout Systems Inc.",
    "NEWR": "New Relic Inc.",
    "NWS": "News Corporation",
    "NGM": "NGM Biopharmaceuticals Inc.",
    "NLSN": "Nielsen N.V.",
    "NWBI": "Northwest Bancshares Inc.",
    "NUAN": "Nuance Communications Inc.",
    "NUVA": "NuVasive Inc.",
    "ODT": "Odonate Therapeutics Inc.",
    "ODFL": "Old Dominion Freight Line Inc.",
    "ONB": "Old National Bancorp",
    "OLLI": "Ollie's Bargain Outlet Holdings",
    "OFIX": "Orthofix Medical Inc.",
    "OSIS": "OSI Systems Inc.",
    "OI": "O-I Glass Inc.",
    "OYST": "Oyster Point Pharma Inc.",
    "PCAR": "PACCAR Inc.",
    "PKE": "Park Aerospace Corp.",
    "PTNR": "Partner Communications Company ",
    "PCTY": "Paylocity Holding Corporation",
    "PDFS": "PDF Solutions Inc.",
    "PEGA": "Pegasystems Inc.",
    "PRGO": "Perrigo Company plc",
    "PPD": "PPD Inc.",
    "PAHC": "Phibro Animal Health Corporatio",
    "PNFP": "Pinnacle Financial Partners In",
    "POR": "Portland General Electric Co",
    "POWL": "Powell Industries Inc.",
    "POWI": "Power Integrations Inc.",
    "PRVL": "Prevail Therapeutics Inc.",
    "PGR": "Progressive Corporation (The)",
    "PRO": "PROS Holdings Inc.",
    "PRTA": "Prothena Corporation plc",
    "PWR": "Quanta Services Inc.",
    "RAPT": "RAPT Therapeutics Inc.",
    "RP": "RealPage Inc.",
    "REPL": "Replimune Group Inc.",
    "RVNC": "Revance Therapeutics Inc.",
    "RXN": "Rexnord Corporation",
    "RMNI": "Rimini Street Inc.",
    "RMR": "The RMR Group Inc.",
    "ROK": "Rockwell Automation Inc.",
    "ROP": "Roper Technologies Inc.",
    "RUBY": "Rubius Therapeutics Inc.",
    "SAFT": "Safety Insurance Group Inc.",
    "SAFM": "Sanderson Farms Inc.",
    "SASR": "Sandy Spring Bancorp Inc.",
    "SCHN": "Schnitzer Steel Industries Inc",
    "SRRK": "Scholar Rock Holding Corporatio",
    "SMTC": "Semtech Corporation",
    "SHW": "Sherwin-Williams Company (The)",
    "SCVL": "Shoe Carnival Inc.",
    "SIBN": "SI-BONE Inc.",
    "SIGA": "SIGA Technologies Inc.",
    "SIGM": "SIFCO Industries Inc. Common S",
    "SILC": "Silicom Ltd",
    "SLAB": "Silicon Laboratories Inc.",
    "SINA": "Sina Corporation",
    "SITE": "SiteOne Landscape Supply Inc.",
    "SITM": "SiTime Corporation",
    "SOHU": "Sohu.com Limited",
    "SBSI": "Southside Bancshares Inc.",
    "SWX": "Southwest Gas Holdings Inc.",
    "SPSC": "SPS Commerce Inc.",
    "SPXC": "SPX Corporation",
    "FLOW": "SPX FLOW Inc.",
    "SSNC": "SS&C Technologies Holdings Inc",
    "SXI": "Standex International Corporati",
    "SRCL": "Stericycle Inc.",
    "STRA": "Strategic Education Inc.",
    "SUI": "Sun Communities Inc.",
    "SGRY": "Surgery Partners Inc.",
    "SRDX": "Surmodics Inc.",
    "SNDX": "Syndax Pharmaceuticals Inc.",
    "SNX": "Synnex Corporation",
    "TARO": "Taro Pharmaceutical Industries ",
    "TNC": "Tennant Company",
    "TTEK": "Tetra Tech Inc.",
    "TCBI": "Texas Capital Bancshares Inc.",
    "HSY": "The Hershey Company",
    "BLD": "TopBuild Corp.",
    "TRNS": "Transcat Inc.",
    "TBIO": "Translate Bio Inc.",
    "TRU": "TransUnion",
    "TCDA": "Tricida Inc.",
    "TRMB": "Trimble Inc.",
    "UMBF": "UMB Financial Corporation",
    "UBSI": "United Bankshares Inc.",
    "UIHC": "United Insurance Holdings Corp.",
    "UTL": "UNITIL Corporation",
    "UHS": "Universal Health Services Inc.",
    "VCYT": "Veracyte Inc.",
    "VRSN": "VeriSign Inc.",
    "VSEC": "VSE Corporation",
    "WAT": "Waters Corporation",
    "WLDN": "Willdan Group Inc.",
    "WING": "Wingstop Inc.",
    "WTFC": "Wintrust Financial Corporation",
    "ZBRA": "Zebra Technologies Corporation",
    "ZBH": "Zimmer Biomet Holdings Inc.",
    "ZUMZ": "Zumiez Inc."]

// MARK: -- For Logo Loading

let myDic_Symb2Img: [String:String] =
    ["AMZN": "amazon.com",
    "BA": "boeing.com",
    "TSLA": "tesla.com",
    "TLRY": "tilray.com",
    "AAPL": "apple.com",
    "NIO": "nio.com",
    "AAL": "aa.com",
    "DAL": "deltaairlines-flights.com",
    "MSFT": "microsoft.com",
    "KO": "coca-colacompany.com",
    "DIS": "waltdisney.org",
    "GOOGL": "google.com",
    "BYND": "beyondmeat.com",
    "FB": "facebook.com",
    "MCD": "mcdonalds.com.au",
    "NFLX": "netflix.com",
    "SDC": "smiledirectclub.com",
    "SNE": "sony.net",
    "AMD": "amd.com",
    "NVDA": "nvidia.com",
    "UBER": "uber.com",
    "UAA": "underarmour.com",
    "BABA": "alibabagroup.com",
    "T": "att.com",
    "IVR": "invesco.com",
    "RCL": "rccl.com",
    "WORK": "slack.com",
    "SPCE": "virgingalactic.com",
    "CPE": "callon.com",
    "ZM": "zoom.us",
    "NKE": "nike.com",
    "OXY": "oxy.com",
    "V": "visa.com",
    "APHA": "aphriainc.com",
    "SNAP": "snapchat.com",
    "BAC": "bankofamerica.com",
    "CGC": "canopygrowth.com",
    "JNJ": "jnj.com",
    "PYPL": "paypal.com",
    "KOS": "kosmosenergy.com",
    "MA": "mastercard.com.au",
    "SBUX": "starbucks.com",
    "VFF": "villagefarms.com",
    "GE": "generalelectric-eg.com",
    "PTON": "onepeloton.com",
    "LUV": "southwest.com",
    "IBM": "ibm.com",
    "O": "realtyincome.com",
    "SQ": "squareup.com",
    "PFE": "pfizer.com",
    "TWTR": "twitter.com",
    "ADBE": "adobe.com",
    "CRON": "thecronosgroup.com",
    "GILD": "gilead.com",
    "HAL": "halliburton.com",
    "GRUB": "grubhub.com",
    "MRO": "marathonoil.com",
    "RIG": "deepwater.com",
    "WMT": "walmart.com",
    "SHOP": "shopify.com",
    "SAVE": "spirit.com",
    "AXP": "americanexpress.com",
    "INTC": "intel.com",
    "QCOM": "qualcomm.com",
    "NOK": "nokia.com",
    "PEP": "pepsico.com",
    "ABBV": "abbvie.com.",
    "ATVI": "activisionblizzard.com",
    "EA": "ea.com",
    "MDT": "medtronic.com",
    "GOOG": "google.com",
    "MO": "altria.com",
    "TLRD": "tailoredbrands.com",
    "BMO": "bmo.com",
    "PK": "pkhotelsandresorts.com",
    "CAR": "avisbudgetgroup.com",
    "GWPH": "gwpharm.com",
    "JD": "jd.com",
    "LTRPA": "tripadvisor.com",
    "MAC": "macerich.com",
    "ZNGA": "zynga.com",
    "GM": "gm.com",
    "MAR": "marriott.com",
    "STOR": "storecapital.com",
    "APA": "apachecorp.com",
    "CRBP": "corbuspharma.com",
    "SPOT": "spotify.com",
    "CRWD": "crowdstrike.com",
    "COTY": "coty.com",
    "NAT": "###",
    "PINS": "pinterest.com",
    "COST": "costco.com",
    "TSM": "tsmc.com",
    "PRGS": "progress.com",
    "AGNC": "###",
    "LAKE": "lakeland.com",
    "TSN": "tysonfoodservice.com",
    "EBAY": "ebay.com",
    "OKTA": "okta.com",
    "SYY": "sysco.com",
    "ABT": "abbott.com",
    "GS": "goldmansachs.com",
    "LYFT": "lyft.com",
    "WBA": "walgreensbootsalliance.com",
    "NET": "cloudflare.com",
    "ROKU": "roku.com",
    "HPE": "hpe.com",
    "DXCM": "dexcom.com",
    "LVGO": "livongo.com",
    "BCRX": "biocryst.com",
    "TDOC": "teladochealth.com",
    "BKNG": "bookingholdings.com",
    "EB": "eventbrite.com",
    "GCI": "gannett.com",
    "RVLV": "revolve.com",
    "KHC": "kraftheinzcompany.com",
    "ORCL": "oracle.com",
    "ENPH": "enphase.com",
    "LMT": "lmco.com",
    "PSX": "phillips.com",
    "TTWO": "take2games.com",
    "SABR": "sabre.com",
    "PM": "pmi.com",
    "GNPX": "genprex.com",
    "CAT": "caterpillar.com",
    "ELF": "elfcosmetics.com",
    "MAIN": "mainstcapital.com",
    "SONO": "sonos.com",
    "DDOG": "datadoghq.com",
    "FSLY": "fastly.com",
    "KMI": "kindermorgan.com",
    "FUV": "arcimoto.com",
    "EPD": "enterpriseproducts.com",
    "LTC": "ltcreit.com",
    "CCI": "crowncastle.com",
    "MANU": "manutd.com",
    "MRVL": "marvell.com",
    "SLB": "slb.com",
    "TWLO": "twilio.com",
    "TRIP": "tripadvisor.com",
    "IRM": "ironmountain.com",
    "SE": "sealimited.com",
    "AKTS": "akoustis.com",
    "AMGN": "amgen.com",
    "BE": "bloomenergy.com",
    "PBA": "pembina.com",
    "BBBY": "bedbathandbeyond.com",
    "OMP": "###",
    "BIDU": "baidu.com",
    "ENB": "enbridge.com",
    "FL": "footlocker.com",
    "GPRO": "gopro.com",
    "HPQ": "hp.com",
    "SEDG": "solaredge.com",
    "AUY": "yamana.com",
    "EPR": "eprkc.com",
    "PSEC": "prospectcap.com",
    "STAG": "stagindustrial.com",
    "AVGO": "broadcom.com",
    "LLY": "lilly.com",
    "KSS": "kohls.com",
    "FTI": "technipfmc.com",
    "BNTX": "biontech.de",
    "IRBT": "irobot.com",
    "BTU": "peabodyenergy.com",
    "PBI": "pitneybowes.com",
    "LEG": "leggett.com",
    "SWKS": "skyworksinc.com",
    "TXMD": "therapeuticsmd.com",
    "CNK": "cinemark.com ",
    "INMD": "inmode.com",
    "JWN": "nordstrom.com",
    "UNP": "up.com",
    "COP": "conocophillips.com",
    "MPC": "marathonpetroleum.com",
    "UPS": "ups.com",
    "CPTA": "capitalagroup.com",
    "ENDP": "endicia.com",
    "NEM": "newmont.com",
    "PRU": "prudential.com",
    "SYK": "stryker.com",
    "AAXN": "enterprises.co.uk",
    "EOG": "eogresources.com",
    "APPN": "appian.com",
    "KOPN": "kopin.com",
    "GT": "goodyeartrucktires.com",
    "MDB": "mongodb.com",
    "BEP": "evolugen.com",
    "FSLR": "firstsolar.com",
    "IVZ": "invesco.com",
    "VSLR": "vivintsolar.com",
    "SIRI": "siriusxm.com",
    "AMT": "americantower.com",
    "CL": "colgatepalmolive.com",
    "PLYA": "playaresorts.com",
    "APPS": "digitalturbine.com",
    "EDIT": "editasmedicine.com",
    "KMB": "kimberly-clark.com",
    "TXN": "ti.com",
    "BPY": "###",
    "SO": "southerncompany.com",
    "ACOR": "acorda.com",
    "HRL": "hormelfoods.com",
    "WDC": "westerndigital.com",
    "CHWY": "chewy.com",
    "FANG": "diamondback.com",
    "FRT": "federalrealty.com",
    "PNC": "pnc.com",
    "AFL": "aflac.com",
    "NOV": "nov.com",
    "CLX": "thecloroxcompany.com",
    "TJX": "tjx.com",
    "ATRO": "astronics.com",
    "VRTX": "vrtx.com",
    "ARCO": "arcosdorados.com",
    "DELL": "delltechnologies.com",
    "D": "dominionenergy.com",
    "JKS": "jinkosolar.com",
    "PBR": "petrobras.com.br",
    "SJR": "shaw.ca",
    "RY": "rbcroyalbank.com",
    "CRSP": "crisprtx.com",
    "FIT": "fitbit.com",
    "GERN": "geron.com",
    "MAXR": "maxar.com",
    "RGLD": "royalgold.com",
    "SWN": "swn.com",
    "TMUS": "t-mobile.pl",
    "NVTA": "invitae.com",
    "MPW": "medicalpropertiestrust.com",
    "SFIX": "stitchfix.com",
    "WSR": "whitestonereit.com",
    "ANIP": "###",
    "CQP": "cheniere.com",
    "GLW": "corning.com",
    "ESTC": "elastic.co",
    "HAS": "hasbro.com",
    "STNE": "###",
    "TEVA": "tevausa.com",
    "WATT": "energous.com",
    "IIPR": "innovativeindustrialproperties.com",
    "PVH": "pvh.com",
    "BGFV": "big5sportinggoods.com",
    "CCEP": "cokecce.com",
    "ED": "coned.com",
    "DRI": "darden.com",
    "LADR": "ladderfunds.com",
    "NEP": "nexteraenergypartners.com",
    "ADPT": "adaptivebiotech.com",
    "BIIB": "biogen.com",
    "ILMN": "illumina.com",
    "LOW": "lowes.com",
    "PCG": "Pacific Gas & Electric Co.",
    "PDD": "Pinduoduo Inc.",
    "QD": "Qudian Inc.",
    "BNS": "Bank Nova Scotia Halifax Pfd 3",
    "ZTS": "Zoetis Inc.",
    "ARLP": "Alliance Resource Partners L.P",
    "ADP": "Automatic Data Processing Inc.",
    "BKR": "Baker Hughes Company",
    "LYB": "LyondellBasell Industries NV",
    "NRG": "NRG Energy Inc.",
    "SMAR": "Smartsheet Inc.",
    "XBIT": "XBiotech Inc.",
    "AA": "Alcoa Corporation",
    "DISCA": "Discovery Inc. - Series A",
    "EMR": "Emerson Electric Company",
    "EL": "Estee Lauder Companies Inc. (T",
    "SLG": "SL Green Realty Corp",
    "ZS": "Zscaler Inc.",
    "ALB": "Albemarle Corporation",
    "BBY": "Best Buy Co. Inc.",
    "BPYU": "Brookfield Property REIT Inc.",
    "CAN": "Canaan Inc.",
    "DOW": "Dow Inc.",
    "GPC": "Genuine Parts Company",
    "INSG": "Inseego Corp.",
    "OHI": "Omega Healthcare Investors Inc",
    "UNM": "Unum Group",
    "VNOM": "Viper Energy Partners LP",
    "WRTC": "Wrap Technologies Inc.",
    "AIR": "AAR Corp.",
    "BIP": "Brookfield Infrastructure Partn",
    "CHL": "China Mobile Limited",
    "GIS": "General Mills Inc.",
    "GEOS": "Geospace Technologies Corporati",
    "LIN": "Linde plc",
    "NPTN": "NeoPhotonics Corporation",
    "NVO": "Novo Nordisk A/S",
    "RUTH": "Ruth's Hospitality Group Inc.",
    "SCM": "Stellus Capital Investment Corp",
    "REAL": "The RealReal Inc.",
    "VERI": "Veritone Inc.",
    "AVAV": "AeroVironment Inc.",
    "ADM": "Archer-Daniels-Midland Company",
    "TEAM": "Atlassian Corporation Plc",
    "GLOG": "GasLog Ltd.",
    "MMP": "Magellan Midstream Partners L.P",
    "NUE": "Nucor Corporation",
    "VIR": "Vir Biotechnology Inc.",
    "AMAT": "Applied Materials Inc.",
    "DFS": "Discover Financial Services",
    "GAIN": "Gladstone Investment Corporatio",
    "LBTYA": "Liberty Global plc",
    "LTHM": "Livent Corporation",
    "MET": "MetLife Inc.",
    "NMRK": "Newmark Group Inc.",
    "PING": "Ping Identity Holding Corp.",
    "TM": "Toyota Motor Corporation",
    "XLNX": "Xilinx Inc.",
    "AER": "AerCap Holdings N.V.",
    "ADSK": "Autodesk Inc.",
    "BCEI": "Bonanza Creek Energy Inc.",
    "CPRI": "Capri Holdings Limited",
    "ECL": "Ecolab Inc.",
    "GOGO": "Gogo Inc.",
    "INTU": "Intuit Inc.",
    "LEVI": "Levi Strauss & Co",
    "NK": "NantKwest Inc.",
    "SUNS": "Solar Senior Capital Ltd.",
    "SPWR": "SunPower Corporation",
    "CHEF": "The Chefs' Warehouse Inc.",
    "VMW": "Vmware Inc.",
    "WPC": "W. P. Carey Inc. REIT",
    "ADS": "Alliance Data Systems Corporati",
    "LAND": "Gladstone Land Corporation",
    "GLUU": "Glu Mobile Inc.",
    "TMO": "Thermo Fisher Scientific Inc",
    "UXIN": "Uxin Limited",
    "WWE": "World Wrestling Entertainment ",
    "AES": "The AES Corporation",
    "ARI": "Apollo Commercial Real Estate F",
    "CM": "Canadian Imperial Bank of Comme",
    "HOG": "Harley-Davidson Inc.",
    "SKYW": "SkyWest Inc.",
    "SSYS": "Stratasys Ltd.",
    "SNCR": "Synchronoss Technologies Inc.",
    "ZEN": "Zendesk Inc.",
    "Z": "Zillow Group Inc.",
    "BZUN": "Baozun Inc.",
    "BSM": "Black Stone Minerals L.P.",
    "BYD": "Boyd Gaming Corporation",
    "CNP": "CenterPoint Energy Inc (Holdin",
    "COUP": "Coupa Software Incorporated",
    "GFL": "GFL Environmental Inc. Subordin",
    "EAF": "GrafTech International Ltd.",
    "HUYA": "HUYA Inc.",
    "IMMU": "Immunomedics Inc.",
    "MAT": "Mattel Inc.",
    "NOW": "ServiceNow Inc.",
    "SRT": "StarTek Inc.",
    "TD": "Toronto Dominion Bank (The)",
    "WRK": "Westrock Company",
    "AGRX": "Agile Therapeutics Inc.",
    "COG": "Cabot Oil & Gas Corporation",
    "GOOS": "Canada Goose Holdings Inc. Subo",
    "COF": "Capital One Financial Corporati",
    "CRT": "Cross Timbers Royalty Trust",
    "FIVN": "Five9 Inc.",
    "GLOP": "GasLog Partners LP",
    "HP": "Helmerich & Payne Inc.",
    "NLOK": "NortonLifeLock Inc.",
    "URBN": "Urban Outfitters Inc.",
    "WB": "Weibo Corporation",
    "ANF": "Abercrombie & Fitch Company",
    "AEM": "Agnico Eagle Mines Limited",
    "NLY": "Annaly Capital Management Inc",
    "CINF": "Cincinnati Financial Corporatio",
    "BEN": "Franklin Resources Inc.",
    "MNK": "Mallinckrodt plc",
    "NTES": "NetEase Inc.",
    "PBCT": "People's",
    "DTIL": "Precision BioSciences Inc.",
    "PBYI": "Puma Biotechnology Inc",
    "TWOU": "2U Inc.",
    "AKAM": "Akamai Technologies Inc.",
    "ANSS": "ANSYS Inc.",
    "BHC": "Bausch Health Companies Inc.",
    "BDSI": "BioDelivery Sciences Internatio",
    "BG": "Bunge Limited Bunge Limited",
    "CWH": "Camping World Holdings Inc.",
    "FUN": "Cedar Fair L.P.",
    "CMG": "Chipotle Mexican Grill Inc.",
    "EXC": "Exelon Corporation",
    "HBI": "Hanesbrands Inc.",
    "HRZN": "Horizon Technology Finance Corp",
    "MKC": "McCormick & Company Incorporat",
    "PDLI": "PDL BioPharma Inc.",
    "QRVO": "Qorvo Inc.",
    "SHAK": "Shake Shack Inc.",
    "SPLK": "Splunk Inc.",
    "SPT": "Sprout Social Inc",
    "STWD": "STARWOOD PROPERTY TRUST INC. S",
    "UVV": "Universal Corporation",
    "ALXN": "Alexion Pharmaceuticals Inc.",
    "BB": "BlackBerry Limited",
    "CRDF": "Cardiff Oncology Inc.",
    "CHU": "China Unicom (Hong Kong) Ltd",
    "CXW": "CoreCivic Inc.",
    "DLPH": "Delphi Technologies PLC",
    "EMN": "Eastman Chemical Company",
    "FTCH": "Farfetch Limited",
    "FIS": "Fidelity National Information S",
    "FLIR": "FLIR Systems Inc.",
    "GOOD": "Gladstone Commercial Corporatio",
    "LB": "L Brands Inc.",
    "MYL": "Mylan N.V.",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "RESN": "Resonant Inc.",
    "SPH": "Suburban Propane Partners L.P.",
    "VICI": "VICI Properties Inc.",
    "AL": "Air Lease Corporation",
    "KERN": "Akerna Corp.",
    "BNFT": "Benefitfocus Inc.",
    "BGSF": "BG Staffing Inc",
    "BXP": "Boston Properties Inc.",
    "SCHW": "Charles Schwab Corporation (The",
    "CLVS": "Clovis Oncology Inc.",
    "CME": "CME Group Inc.",
    "DLTR": "Dollar Tree Inc.",
    "EHTH": "eHealth Inc.",
    "FISV": "Fiserv Inc.",
    "FLR": "Fluor Corporation",
    "HASI": "Hannon Armstrong Sustainable In",
    "HBIO": "Harvard Bioscience Inc.",
    "IRDM": "Iridium Communications Inc",
    "JCI": "Johnson Controls International ",
    "NTAP": "NetApp Inc.",
    "PANW": "Palo Alto Networks Inc.",
    "TRUE": "TrueCar Inc.",
    "WSG": "Wanda Sports Group Company Limi",
    "W": "Wayfair Inc.",
    "WYND": "Wyndham Destinations Inc.",
    "APD": "Air Products and Chemicals Inc",
    "AZRE": "Azure Power Global Limited",
    "BBSI": "Barrett Business Services Inc.",
    "BLMN": "Bloomin' Brands Inc.",
    "CI": "Cigna Corporation",
    "CSX": "CSX Corporation",
    "DE": "Deere & Company",
    "EW": "Edwards Lifesciences Corporatio",
    "ENIA": "Enel Americas S.A.",
    "FTNT": "Fortinet Inc.",
    "FNV": "Franco-Nevada Corporation",
    "ITW": "Illinois Tool Works Inc.",
    "NTLA": "Intellia Therapeutics Inc.",
    "LAUR": "Laureate Education Inc.",
    "LAZ": "Lazard LTD. Lazard LTD.",
    "LEN": "Lennar Corporation",
    "LX": "LexinFintech Holdings Ltd.",
    "MELI": "MercadoLibre Inc.",
    "MCRI": "Monarch Casino & Resort Inc.",
    "NTGR": "NETGEAR Inc.",
    "PD": "PagerDuty Inc.",
    "PAA": "Plains All American Pipeline L",
    "QTT": "Qutoutiao Inc.",
    "SHO": "Sunstone Hotel Investors Inc. ",
    "TER": "Teradyne Inc.",
    "MOS": "Mosaic Company (The)",
    "TIF": "Tiffany & Co.",
    "VLY": "Valley National Bancorp",
    "VKTX": "Viking Therapeutics Inc.",
    "WES": "Western Midstream Partners LP",
    "ALEX": "Alexander & Baldwin Inc.",
    "AMBA": "Ambarella Inc.",
    "AWR": "American States Water Company",
    "ANET": "Arista Networks Inc.",
    "BIG": "Big Lots Inc.",
    "CHRS": "Coherus BioSciences Inc.",
    "CONE": "CyrusOne Inc",
    "EQT": "EQT Corporation",
    "EXTR": "Extreme Networks Inc.",
    "HEP": "Holly Energy Partners L.P.",
    "IMGN": "ImmunoGen Inc.",
    "IPHI": "Inphi Corporation",
    "ICE": "Intercontinental Exchange Inc.",
    "JEF": "Jefferies Financial Group Inc.",
    "JNPR": "Juniper Networks Inc.",
    "LSCC": "Lattice Semiconductor Corporati",
    "LIZI": "LIZHI INC.",
    "LITE": "Lumentum Holdings Inc.",
    "MCY": "Mercury General Corporation",
    "MDP": "Meredith Corporation",
    "MHK": "Mohawk Industries Inc.",
    "NDAQ": "Nasdaq Inc.",
    "NAVI": "Navient Corporation",
    "PACB": "Pacific Biosciences of Californ",
    "PAVM": "PAVmed Inc.",
    "PAYX": "Paychex Inc.",
    "PRFT": "Perficient Inc.",
    "QIWI": "QIWI plc",
    "SSTI": "ShotSpotter Inc.",
    "SPWH": "Sportsman's Warehouse Holdings",
    "SUPN": "Supernus Pharmaceuticals Inc.",
    "VRNT": "Verint Systems Inc.",
    "VIRT": "Virtu Financial Inc.",
    "WY": "Weyerhaeuser Company",
    "YNDX": "Yandex N.V.",
    "YJ": "Yunji Inc. - American Depositor",
    "ACCO": "Acco Brands Corporation",
    "ALRM": "Alarm.com Holdings Inc.",
    "MDRX": "Allscripts Healthcare Solutions",
    "ARCT": "Arcturus Therapeutics Holdings ",
    "ARLO": "Arlo Technologies Inc.",
    "ATRA": "Atara Biotherapeutics Inc.",
    "AVDL": "Avadel Pharmaceuticals plc",
    "AVID": "Avid Technology Inc.",
    "BBDC": "Barings BDC Inc.",
    "BLUE": "bluebird bio Inc.",
    "BSX": "Boston Scientific Corporation",
    "BOX": "Box Inc.",
    "CCJ": "Cameco Corporation",
    "CARG": "CarGurus Inc.",
    "KMX": "CarMax Inc",
    "CTSH": "Cognizant Technology Solutions ",
    "COMM": "CommScope Holding Company Inc.",
    "TACO": "Del Taco Restaurants Inc.",
    "DKS": "Dick's Sporting Goods Inc",
    "EPAM": "EPAM Systems Inc.",
    "FCPT": "Four Corners Property Trust In",
    "FOXA": "Fox Corporation",
    "HRB": "H&R Block Inc.",
    "IVAC": "Intevac Inc.",
    "LILA": "Liberty Latin America Ltd.",
    "LPSN": "LivePerson Inc.",
    "L": "Loews Corporation",
    "MDU": "MDU Resources Group Inc.",
    "VIVO": "Meridian Bioscience Inc.",
    "MNR": "Monmouth Real Estate Investment",
    "MYGN": "Myriad Genetics Inc.",
    "NC": "NACCO Industries Inc.",
    "NH": "NantHealth Inc.",
    "PH": "Parker-Hannifin Corporation",
    "PT": "Pintec Technology Holdings Limi",
    "QTNT": "Quotient Limited",
    "ROST": "Ross Stores Inc.",
    "SEAC": "SeaChange International Inc.",
    "SYNC": "Synacor Inc.",
    "TRP": "TC Energy Corporation",
    "TDC": "Teradata Corporation",
    "VFC": "V.F. Corporation",
    "VRSK": "Verisk Analytics Inc.",
    "XYL": "Xylem Inc.",
    "ACIU": "AC Immune SA",
    "AMRC": "Ameresco Inc.",
    "AEP": "American Electric Power Company",
    "AFIN": "American Finance Trust Inc.",
    "AMKR": "Amkor Technology Inc.",
    "AMPH": "Amphastar Pharmaceuticals Inc.",
    "ATRS": "Antares Pharma Inc.",
    "AON": "Aon plc",
    "ARC": "ARC Document Solutions Inc.",
    "ATHX": "Athersys Inc.",
    "AVA": "Avista Corporation",
    "BAND": "Bandwidth Inc.",
    "BYSI": "BeyondSpring Inc.",
    "BHP": "BHP Group Limited",
    "BJ": "BJ's Wholesale Club Holdings I",
    "BBIO": "BridgeBio Pharma Inc.",
    "CVGW": "Calavo Growers Inc.",
    "CVNA": "Carvana Co.",
    "CRNT": "Ceragon Networks Ltd.",
    "XEC": "Cimarex Energy Co",
    "CTXS": "Citrix Systems Inc.",
    "CODI": "Compass Diversified Holdings Sh",
    "CEIX": "CONSOL Energy Inc.",
    "CRTO": "Criteo S.A.",
    "CCRN": "Cross Country Healthcare Inc.",
    "CMI": "Cummins Inc.",
    "DAR": "Darling Ingredients Inc.",
    "DISCK": "Discovery Inc. - Series C",
    "EQR": "Equity Residential",
    "ESPR": "Esperion Therapeutics Inc.",
    "ESS": "Essex Property Trust Inc.",
    "EVR": "Evercore Inc.",
    "ES": "Eversource Energy (D/B/A)",
    "EXTN": "Exterran Corporation",
    "FRG": "Franchise Group Inc.",
    "HEES": "H&E Equipment Services Inc.",
    "HSIC": "Henry Schein Inc.",
    "HBAN": "Huntington Bancshares Incorpora",
    "IDXX": "IDEXX Laboratories Inc.",
    "IHRT": "iHeartMedia Inc.",
    "IMMR": "Immersion Corporation",
    "IP": "International Paper Company",
    "KEY": "KeyCorp",
    "KIM": "Kimco Realty Corporation",
    "KKR": "KKR & Co. Inc.",
    "KTB": "Kontoor Brands Inc.",
    "LMRK": "Landmark Infrastructure Partner",
    "LGC": "Legacy Acquisition Corp.",
    "LBTYK": "Liberty Global plc",
    "LILAK": "Liberty Latin America Ltd.",
    "MTSI": "MACOM Technology Solutions Hold",
    "MRUS": "Merus N.V.",
    "MCHP": "Microchip Technology Incorporat",
    "MTSC": "MTS Systems Corporation",
    "NREF": "NexPoint Real Estate Finance I",
    "NTR": "Nutrien Ltd.",
    "ORA": "Ormat Technologies Inc.",
    "PLAB": "Photronics Inc.",
    "PLD": "Prologis Inc.",
    "PSA": "Public Storage",
    "QRTEA": "Liberty Interactive Corporation",
    "RGP": "Resources Connection Inc.",
    "R": "Ryder System Inc.",
    "SAGE": "Sage Therapeutics Inc.",
    "SBGI": "Sinclair Broadcast Group Inc.",
    "SNA": "Snap-On Incorporated",
    "TRGP": "Targa Resources Inc.",
    "TH": "Target Hospitality Corp.",
    "TMDX": "TransMedics Group Inc.",
    "TRUP": "Trupanion Inc.",
    "UCTT": "Ultra Clean Holdings Inc.",
    "UMH": "UMH Properties Inc.",
    "GWW": "W.W. Grainger Inc.",
    "WTS": "Watts Water Technologies Inc.",
    "WWD": "Woodward Inc.",
    "YUMC": "Yum China Holdings Inc.",
    "JFU": "9F Inc.",
    "ATEN": "A10 Networks Inc.",
    "ACHC": "Acadia Healthcare Company Inc.",
    "ADNT": "Adient plc",
    "AEIS": "Advanced Energy Industries Inc",
    "ACM": "AECOM",
    "A": "Agilent Technologies Inc.",
    "AMED": "Amedisys Inc",
    "AMN": "AMN Healthcare Services Inc AMN",
    "PLAN": "Anaplan Inc.",
    "ANAB": "AnaptysBio Inc.",
    "ANIK": "Anika Therapeutics Inc.",
    "APPF": "AppFolio Inc.",
    "AROC": "Archrock Inc.",
    "AIZ": "Assurant Inc.",
    "ATOM": "Atomera Incorporated",
    "AVT": "Avnet Inc.",
    "AXS": "Axis Capital Holdings Limited",
    "BGS": "B&G Foods Inc. B&G Foods Inc.",
    "BMRN": "BioMarin Pharmaceutical Inc.",
    "BJRI": "BJ's Restaurants Inc.",
    "BKH": "Black Hills Corporation",
    "EPAY": "Bottomline Technologies Inc.",
    "BV": "BrightView Holdings Inc.",
    "CDNS": "Cadence Design Systems Inc.",
    "CAMP": "CalAmp Corp.",
    "CARA": "Cara Therapeutics Inc.",
    "CF": "CF Industries Holdings Inc.",
    "CHTR": "Charter Communications Inc.",
    "COLL": "Collegium Pharmaceutical Inc.",
    "CAG": "ConAgra Brands Inc.",
    "BAP": "Credicorp Ltd.",
    "CRESY": "Cresud S.A.C.I.F. y A.",
    "CUE": "Cue Biopharma Inc.",
    "DAKT": "Daktronics Inc.",
    "DISH": "DISH Network Corporation",
    "DEI": "Douglas Emmett Inc.",
    "SATS": "EchoStar Corporation",
    "ENIC": "Enel Chile S.A.",
    "MRAM": "Everspin Technologies Inc.",
    "EXR": "Extra Space Storage Inc",
    "FDS": "FactSet Research Systems Inc.",
    "FAST": "Fastenal Company",
    "FLT": "FleetCor Technologies Inc.",
    "GTHX": "G1 Therapeutics Inc.",
    "GTX": "Garrett Motion Inc.",
    "GNTX": "Gentex Corporation",
    "HLNE": "Hamilton Lane Incorporated",
    "HCA": "HCA Healthcare Inc.",
    "HUBS": "HubSpot Inc.",
    "INVH": "Invitation Homes Inc.",
    "IQ": "iQIYI Inc.",
    "KW": "Kennedy-Wilson Holdings Inc.",
    "KBAL": "Kimball International Inc.",
    "KNSA": "Kiniksa Pharmaceuticals Ltd.",
    "KEP": "Korea Electric Power Corporatio",
    "LRCX": "Lam Research Corporation",
    "LORL": "Loral Space and Communications",
    "LUNA": "Luna Innovations Incorporated",
    "MNTX": "Manitex International Inc.",
    "MCHX": "Marchex Inc.",
    "MATW": "Matthews International Corporat",
    "MITK": "Mitek Systems Inc.",
    "MIXT": "MiX Telematics Limited",
    "MPLX": "MPLX LP",
    "NBIX": "Neurocrine Biosciences Inc.",
    "NXTC": "NextCure Inc.",
    "NICE": "NICE Ltd",
    "NSC": "Norfolk Southern Corporation",
    "NTRS": "Northern Trust Corporation",
    "OMER": "Omeros Corporation",
    "OSW": "OneSpaWorld Holdings Limited",
    "PDCO": "Patterson Companies Inc.",
    "PSXP": "Phillips 66 Partners LP",
    "DOC": "Physicians Realty Trust",
    "PFPT": "Proofpoint Inc.",
    "QADB": "QAD Inc.",
    "QLYS": "Qualys Inc.",
    "RDUS": "Radius Health Inc.",
    "RPD": "Rapid7 Inc.",
    "RDVT": "Red Violet Inc.",
    "RDHL": "Redhill Biopharma Ltd.",
    "RPAY": "Repay Holdings Corporation",
    "KRMD": "Repro Med Systems Inc.",
    "SPNS": "Sapiens International Corporati",
    "SCSC": "ScanSource Inc.",
    "SCWX": "SecureWorks Corp.",
    "SRE": "Sempra Energy",
    "SREV": "ServiceSource International In",
    "SLP": "Simulations Plus Inc.",
    "SLM": "SLM Corporation",
    "SGH": "SMART Global Holdings Inc.",
    "SMCI": "Super Micro Computer Inc.",
    "SYKE": "Sykes Enterprises Incorporated",
    "TAL": "TAL Education Group",
    "BX": "The Blackstone Group Inc.",
    "PLCE": "Children's Place Inc. (The)",
    "SHYF": "The Shyft Group Inc.",
    "TSCO": "Tractor Supply Company",
    "WCN": "Waste Connections Inc.",
    "WHR": "Whirlpool Corporation",
    "WIX": "Wix.com Ltd.",
    "WDAY": "Workday Inc.",
    "XNET": "Xunlei Limited",
    "SRCE": "1st Source Corporation",
    "AOS": "A.O. Smith Corporation",
    "ABMD": "ABIOMED Inc.",
    "ASIX": "AdvanSix Inc.",
    "ADVM": "Adverum Biotechnologies Inc.",
    "AGYS": "Agilysys Inc.",
    "AIMT": "Aimmune Therapeutics Inc.",
    "AIRG": "Airgain Inc.",
    "ALG": "Alamo Group Inc.",
    "ALBO": "Albireo Pharma Inc.",
    "ARE": "Alexandria Real Estate Equities",
    "ALL": "Allstate Corporation (The)",
    "AOSL": "Alpha and Omega Semiconductor L",
    "APLT": "Applied Therapeutics Inc.",
    "ARQT": "Arcutis Biotherapeutics Inc.",
    "AROW": "Arrow Financial Corporation",
    "ASB": "Associated Banc-Corp",
    "ASUR": "Asure Software Inc",
    "ATO": "Atmos Energy Corporation",
    "AN": "AutoNation Inc.",
    "AVY": "Avery Dennison Corporation",
    "AVRO": "AVROBIO Inc.",
    "AWRE": "Aware Inc.",
    "BMI": "Badger Meter Inc.",
    "BAX": "Baxter International Inc.",
    "BILL": "Bill.com Holdings Inc.",
    "BEAT": "BioTelemetry Inc.",
    "BAH": "Booz Allen Hamilton Holding Cor",
    "BRC": "Brady Corporation",
    "BRX": "Brixmor Property Group Inc.",
    "BRO": "Brown & Brown Inc.",
    "BC": "Brunswick Corporation",
    "BKE": "Buckle Inc. (The)",
    "BLDR": "Builders FirstSource Inc.",
    "CAI": "CAI International Inc.",
    "CPB": "Campbell Soup Company",
    "CATY": "Cathay General Bancorp",
    "CE": "Celanese Corporation Celanese C",
    "COLB": "Columbia Banking System Inc.",
    "CPRT": "Copart Inc.",
    "COR": "CoreSite Realty Corporation",
    "CTVA": "Corteva Inc.",
    "CRVL": "CorVel Corp.",
    "CZZ": "Cosan Limited",
    "CSGP": "CoStar Group Inc.",
    "CACC": "Credit Acceptance Corporation",
    "CREE": "Cree Inc.",
    "CSGS": "CSG Systems International Inc.",
    "CW": "Curtiss-Wright Corporation",
    "CYBE": "CyberOptics Corporation",
    "CTMX": "CytomX Therapeutics Inc.",
    "DVA": "DaVita Inc.",
    "DGII": "Digi International Inc.",
    "DMRC": "Digimarc Corporation",
    "DOV": "Dover Corporation",
    "DSPG": "DSP Group Inc.",
    "EGBN": "Eagle Bancorp Inc.",
    "EIX": "Edison International",
    "ESI": "Element Solutions Inc.",
    "ECPG": "Encore Capital Group Inc",
    "DAVA": "Endava plc",
    "FFIN": "First Financial Bankshares Inc",
    "FTS": "Fortis Inc.",
    "FEIM": "Frequency Electronics Inc.",
    "FREQ": "Frequency Therapeutics Inc.",
    "FULT": "Fulton Financial Corporation",
    "FUTU": "Futu Holdings Limited",
    "GDDY": "GoDaddy Inc.",
    "GDEN": "Golden Entertainment Inc.",
    "AJX": "Great Ajax Corp.",
    "HTLF": "Heartland Financial USA Inc.",
    "HLF": "Herbalife Nutrition Ltd.",
    "HCCI": "Heritage-Crystal Clean Inc.",
    "HNP": "Huaneng Power Intl",
    "HPP": "Hudson Pacific Properties Inc.",
    "HUM": "Humana Inc.",
    "INFO": "IHS Markit Ltd.",
    "INCY": "Incyte Corporation",
    "IPG": "Interpublic Group of Companies",
    "KALA": "Kala Pharmaceuticals Inc.",
    "K": "Kellogg Company",
    "KEQU": "Kewaunee Scientific Corporation",
    "KLAC": "KLA Corporation",
    "KFY": "Korn Ferry",
    "KRYS": "Krystal Biotech Inc.",
    "LNTH": "Lantheus Holdings Inc.",
    "LDOS": "Leidos Holdings Inc.",
    "MKTX": "MarketAxess Holdings Inc.",
    "MXIM": "Maxim Integrated Products Inc.",
    "MGTX": "MeiraGTx Holdings plc",
    "MIME": "Mimecast Limited",
    "MC": "Moelis & Company",
    "MPWR": "Monolithic Power Systems Inc.",
    "NSTG": "NanoString Technologies Inc.",
    "EDU": "New Oriental Education & Techno",
    "NWSA": "News Corporation",
    "ORLY": "O'Reilly Automotive Inc.",
    "ON": "ON Semiconductor Corporation",
    "KIDS": "OrthoPediatrics Corp.",
    "PLMR": "Palomar Holdings Inc.",
    "PASG": "Passage Bio Inc.",
    "PCTI": "PCTEL Inc.",
    "PLXS": "Plexus Corp.",
    "PRVB": "Provention Bio Inc.",
    "QADA": "QAD Inc.",
    "RMBS": "Rambus Inc.",
    "RF": "Regions Financial Corporation",
    "RCII": "Rent-A-Center Inc.",
    "RGCO": "RGC Resources Inc.",
    "RYTM": "Rhythm Pharmaceuticals Inc.",
    "RCKT": "Rocket Pharmaceuticals Inc.",
    "RUHN": "Ruhnn Holding Limited",
    "BFS": "Saul Centers Inc.",
    "SIGI": "Selective Insurance Group Inc.",
    "SSTK": "Shutterstock Inc.",
    "SWIR": "Sierra Wireless Inc.",
    "SWK": "Stanley Black & Decker Inc.",
    "STOK": "Stoke Therapeutics Inc.",
    "SYNA": "Synaptics Incorporated",
    "SNPS": "Synopsys Inc.",
    "TROW": "T. Rowe Price Group Inc.",
    "TXRH": "Texas Roadhouse Inc.",
    "GBX": "Greenbrier Companies Inc. (The",
    "TSBK": "Timberland Bancorp Inc.",
    "TKR": "Timken Company (The)",
    "TSC": "TriState Capital Holdings Inc.",
    "TTMI": "TTM Technologies Inc.",
    "ULTA": "Ulta Beauty Inc.",
    "URI": "United Rentals Inc.",
    "USM": "United States Cellular Corporat",
    "VREX": "Varex Imaging Corporation",
    "VRNS": "Varonis Systems Inc.",
    "VECO": "Veeco Instruments Inc.",
    "VRTU": "Virtusa Corporation",
    "VYGR": "Voyager Therapeutics Inc.",
    "VMC": "Vulcan Materials Company (Holdi",
    "WAFD": "Washington Federal Inc.",
    "WK": "Workiva Inc.",
    "ZION": "Zions Bancorporation N.A.",
    "QFIN": "360 Finance Inc.",
    "ACIW": "ACI Worldwide Inc.",
    "ADUS": "Addus HomeCare Corporation",
    "AAP": "Advance Auto Parts Inc Advance ",
    "AERI": "Aerie Pharmaceuticals Inc.",
    "AMG": "Affiliated Managers Group Inc.",
    "AGIO": "Agios Pharmaceuticals Inc.",
    "ADC": "Agree Realty Corporation",
    "AKCA": "Akcea Therapeutics Inc.",
    "AKRO": "Akero Therapeutics Inc.",
    "ALC": "Alcon Inc.",
    "ALX": "Alexander's Inc.",
    "ALLK": "Allakos Inc.",
    "ALLE": "Allegion plc",
    "LNT": "Alliant Energy Corporation",
    "APEI": "American Public Education Inc.",
    "AMSWA": "American Software Inc.",
    "CRMT": "America's Car-Mart Inc.",
    "AMSF": "AMERISAFE Inc.",
    "AME": "AMETEK Inc.",
    "ADI": "Analog Devices Inc.",
    "ATEX": "Anterix Inc.",
    "AMEH": "Apollo Medical Holdings Inc.",
    "APRE": "Aprea Therapeutics Inc.",
    "ARDX": "Ardelyx Inc.",
    "AGX": "Argan Inc.",
    "ASGN": "ASGN Incorporated",
    "AC": "Associated Capital Group Inc.",
    "ATNX": "Athenex Inc.",
    "AUB": "Atlantic Union Bankshares Corpo",
    "ATNI": "ATN International Inc.",
    "ATHM": "Autohome Inc.",
    "AZO": "AutoZone Inc.",
    "AVNS": "Avanos Medical Inc.",
    "AVTR": "Avantor Inc.",
    "AXNX": "Axonics Modulation Technologies",
    "BCPC": "Balchem Corporation",
    "BLL": "Ball Corporation",
    "BECN": "Beacon Roofing Supply Inc.",
    "BEAM": "Beam Therapeutics Inc.",
    "BDC": "Belden Inc",
    "BHE": "Benchmark Electronics Inc.",
    "BTAI": "BioXcel Therapeutics Inc.",
    "BCOR": "Blucora Inc.",
    "BOKF": "BOK Financial Corporation",
    "BWA": "BorgWarner Inc.",
    "BOMN": "Boston Omaha Corporation",
    "BDGE": "Bridge Bancorp Inc.",
    "BCOV": "Brightcove Inc.",
    "BRKS": "Brooks Automation Inc.",
    "BURL": "Burlington Stores Inc.",
    "CABO": "Cable One Inc.",
    "CCMP": "Cabot Microelectronics Corporat",
    "CATM": "Cardtronics plc",
    "CDNA": "CareDx Inc.",
    "CSL": "Carlisle Companies Incorporated",
    "CSTL": "Castle Biosciences Inc.",
    "CNTG": "Centogene N.V.",
    "CERN": "Cerner Corporation",
    "CEVA": "CEVA Inc.",
    "CHUY": "Chuy's Holdings Inc.",
    "CTAS": "Cintas Corporation",
    "CHCO": "City Holding Company",
    "CMS": "CMS Energy Corporation",
    "COHR": "Coherent Inc.",
    "CFX": "Colfax Corporation",
    "CBU": "Community Bank System Inc.",
    "CPSI": "Computer Programs and Systems ",
    "CTG": "Computer Task Group Incorporat",
    "CRNX": "Crinetics Pharmaceuticals Inc.",
    "CTS": "CTS Corporation",
    "CVBF": "CVB Financial Corporation",
    "DHI": "D.R. Horton Inc.",
    "DJCO": "Daily Journal Corp. (S.C.)",
    "DMTK": "DermTech Inc.",
    "DIOD": "Diodes Incorporated",
    "DTE": "DTE Energy Company",
    "EGRX": "Eagle Pharmaceuticals Inc.",
    "LOCO": "El Pollo Loco Holdings Inc.",
    "ENTA": "Enanta Pharmaceuticals Inc.",
    "ENV": "Envestnet Inc",
    "EVA": "Enviva Partners LP",
    "PLUS": "ePlus inc.",
    "EFX": "Equifax Inc.",
    "ERIE": "Erie Indemnity Company",
    "ESTA": "Establishment Labs Holdings Inc",
    "EXPI": "eXp World Holdings Inc.",
    "EXPO": "Exponent Inc.",
    "FFIV": "F5 Networks Inc.",
    "FGEN": "FibroGen Inc",
    "FITB": "Fifth Third Bancorp",
    "FCNCA": "First Citizens BancShares Inc.",
    "FHB": "First Hawaiian Inc.",
    "FORM": "FormFactor Inc.",
    "FORR": "Forrester Research Inc.",
    "FTDR": "frontdoor inc.",
    "GATX": "GATX Corporation",
    "GCP": "GCP Applied Technologies Inc.",
    "GFN": "General Finance Corporation",
    "GL": "Globe Life Inc.",
    "GSHD": "Goosehead Insurance Inc.",
    "GHG": "GreenTree Hospitality Group Ltd",
    "GDYN": "Grid Dynamics Holdings Inc.",
    "GSIT": "GSI Technology Inc.",
    "HIG": "Hartford Financial Services Gro",
    "HSTM": "HealthStream Inc.",
    "HSII": "Heidrick & Struggles Internatio",
    "HMSY": "HMS Holdings Corp",
    "HUBB": "Hubbell Inc",
    "IMAB": "I-MAB",
    "ICHR": "Ichor Holdings",
    "IBKR": "Interactive Brokers Group Inc.",
    "IFF": "Internationa Flavors & Fragranc",
    "ISBC": "Investors Bancorp Inc.",
    "IPGP": "IPG Photonics Corporation",
    "ITRI": "Itron Inc.",
    "JBHT": "J.B. Hunt Transport Services I",
    "MAYS": "J. W. Mays Inc.",
    "JBL": "Jabil Inc.",
    "J": "Jacobs Engineering Group Inc.",
    "JRVR": "James River Group Holdings Ltd",
    "JBT": "John Bean Technologies Corporat",
    "KAI": "Kadant Inc",
    "KE": "Kimball Electronics Inc.",
    "KURA": "Kura Oncology Inc.",
    "LKFN": "Lakeland Financial Corporation",
    "TREE": "LendingTree Inc.",
    "LNC": "Lincoln National Corporation",
    "LFUS": "Littelfuse Inc.",
    "RAMP": "LiveRamp Holdings Inc.",
    "MANH": "Manhattan Associates Inc.",
    "MAN": "ManpowerGroup",
    "MLM": "Martin Marietta Materials Inc.",
    "MAS": "Masco Corporation",
    "MXL": "MaxLinear Inc.",
    "MGEE": "MGE Energy Inc.",
    "MTEM": "Molecular Templates Inc.",
    "MORF": "Morphic Holding Inc.",
    "COOP": "Mr. Cooper Group Inc.",
    "MUSA": "Murphy USA Inc.",
    "NSSC": "NAPCO Security Technologies In",
    "NTCT": "NetScout Systems Inc.",
    "NEWR": "New Relic Inc.",
    "NWS": "News Corporation",
    "NGM": "NGM Biopharmaceuticals Inc.",
    "NLSN": "Nielsen N.V.",
    "NWBI": "Northwest Bancshares Inc.",
    "NUAN": "Nuance Communications Inc.",
    "NUVA": "NuVasive Inc.",
    "ODT": "Odonate Therapeutics Inc.",
    "ODFL": "Old Dominion Freight Line Inc.",
    "ONB": "Old National Bancorp",
    "OLLI": "Ollie's Bargain Outlet Holdings",
    "OFIX": "Orthofix Medical Inc.",
    "OSIS": "OSI Systems Inc.",
    "OI": "O-I Glass Inc.",
    "OYST": "Oyster Point Pharma Inc.",
    "PCAR": "PACCAR Inc.",
    "PKE": "Park Aerospace Corp.",
    "PTNR": "Partner Communications Company ",
    "PCTY": "Paylocity Holding Corporation",
    "PDFS": "PDF Solutions Inc.",
    "PEGA": "Pegasystems Inc.",
    "PRGO": "Perrigo Company plc",
    "PPD": "PPD Inc.",
    "PAHC": "Phibro Animal Health Corporatio",
    "PNFP": "Pinnacle Financial Partners In",
    "POR": "Portland General Electric Co",
    "POWL": "Powell Industries Inc.",
    "POWI": "Power Integrations Inc.",
    "PRVL": "Prevail Therapeutics Inc.",
    "PGR": "Progressive Corporation (The)",
    "PRO": "PROS Holdings Inc.",
    "PRTA": "Prothena Corporation plc",
    "PWR": "Quanta Services Inc.",
    "RAPT": "RAPT Therapeutics Inc.",
    "RP": "RealPage Inc.",
    "REPL": "Replimune Group Inc.",
    "RVNC": "Revance Therapeutics Inc.",
    "RXN": "Rexnord Corporation",
    "RMNI": "Rimini Street Inc.",
    "RMR": "The RMR Group Inc.",
    "ROK": "Rockwell Automation Inc.",
    "ROP": "Roper Technologies Inc.",
    "RUBY": "Rubius Therapeutics Inc.",
    "SAFT": "Safety Insurance Group Inc.",
    "SAFM": "Sanderson Farms Inc.",
    "SASR": "Sandy Spring Bancorp Inc.",
    "SCHN": "Schnitzer Steel Industries Inc",
    "SRRK": "Scholar Rock Holding Corporatio",
    "SMTC": "Semtech Corporation",
    "SHW": "Sherwin-Williams Company (The)",
    "SCVL": "Shoe Carnival Inc.",
    "SIBN": "SI-BONE Inc.",
    "SIGA": "SIGA Technologies Inc.",
    "SIGM": "SIFCO Industries Inc. Common S",
    "SILC": "Silicom Ltd",
    "SLAB": "Silicon Laboratories Inc.",
    "SINA": "Sina Corporation",
    "SITE": "SiteOne Landscape Supply Inc.",
    "SITM": "SiTime Corporation",
    "SOHU": "Sohu.com Limited",
    "SBSI": "Southside Bancshares Inc.",
    "SWX": "Southwest Gas Holdings Inc.",
    "SPSC": "SPS Commerce Inc.",
    "SPXC": "SPX Corporation",
    "FLOW": "SPX FLOW Inc.",
    "SSNC": "SS&C Technologies Holdings Inc",
    "SXI": "Standex International Corporati",
    "SRCL": "Stericycle Inc.",
    "STRA": "Strategic Education Inc.",
    "SUI": "Sun Communities Inc.",
    "SGRY": "Surgery Partners Inc.",
    "SRDX": "Surmodics Inc.",
    "SNDX": "Syndax Pharmaceuticals Inc.",
    "SNX": "Synnex Corporation",
    "TARO": "Taro Pharmaceutical Industries ",
    "TNC": "Tennant Company",
    "TTEK": "Tetra Tech Inc.",
    "TCBI": "Texas Capital Bancshares Inc.",
    "HSY": "The Hershey Company",
    "BLD": "TopBuild Corp.",
    "TRNS": "Transcat Inc.",
    "TBIO": "Translate Bio Inc.",
    "TRU": "TransUnion",
    "TCDA": "Tricida Inc.",
    "TRMB": "Trimble Inc.",
    "UMBF": "UMB Financial Corporation",
    "UBSI": "United Bankshares Inc.",
    "UIHC": "United Insurance Holdings Corp.",
    "UTL": "UNITIL Corporation",
    "UHS": "Universal Health Services Inc.",
    "VCYT": "Veracyte Inc.",
    "VRSN": "VeriSign Inc.",
    "VSEC": "VSE Corporation",
    "WAT": "Waters Corporation",
    "WLDN": "Willdan Group Inc.",
    "WING": "Wingstop Inc.",
    "WTFC": "Wintrust Financial Corporation",
    "ZBRA": "Zebra Technologies Corporation",
    "ZBH": "Zimmer Biomet Holdings Inc.",
    "ZUMZ": "Zumiez Inc."]
